### PR TITLE
fixes #3221 - service file surviving hard resets

### LINKED ISSUE #3221: Update the docs' cadvisor unit file
Hi,

Newbie here. As you've seen in the previous issue ;).

I'm testing the platform, randomly resetting machines and seeing if I can manage to nurse the clusters back to health again. It seems to be doing alright, but of course, there's no load on the platform.

Anyway, as a part of trying to get some diagnostics into each of the services running in docker, I installed cadvisor according [to the docs](http://docs.deis.io/en/latest/managing_deis/platform_monitoring/#cadvisor) with a unit file that I did `fleetctl start cadvisor.service`, which started it across all three nodes that I have in my vagrant cluster.

I then reset a single node, node 3 and watched whether things would still show up and route properly. They did.

Now I started it again.

Here's where the first question comes: if a node reboots, why doesn't `deisctl status` tell me about it? It's just blank, exiting 0.

Also, when the node goes back up, not all unit are automatically started, even though they should optimally be started as soon as possible to ensure availability: specifically:

deis-store-daemon.service		169914f2.../172.17.8.102	activating	start-pre

and 

deis-logspout.service			169914f2.../172.17.8.102	activating	auto-restart

I had to run `deisctl start platform` for them to start. I didn't manage any `fleetctl` command that made a difference. At this point it was a bit opaque.

When they had started, I noticed that cadvisor looked like this:

```
UNIT					MACHINE				ACTIVE		SUB
cadvisor.service			169914f2.../172.17.8.102	failed		failed
cadvisor.service			21d1548b.../172.17.8.100	active		running
cadvisor.service			28ed8692.../172.17.8.101	active		running
deis-builder.service			21d1548b.../172.17.8.100	active		running
# snip
```

As it turns out, it didn't want to start again, because, according to journalctl (deisctl journal didn't want to give me anything:

```
$ deisctl journal cadvisor
Unable to get journal for global unit cadvisor.service. Check the logs on the host using journalctl.
```
) despite it being a global unit.

```
$ journalctl -fu cadvisor
Mar 06 23:00:33 deis-03 systemd[1]: Starting Google Container Advisor...
Mar 06 23:00:33 deis-03 systemd[1]: Started Google Container Advisor.
Mar 06 23:00:33 deis-03 docker[3135]: time="2015-03-06T23:00:33Z" level="fatal" msg="Error response from daemon: Conflict, The name cadvisor is already assigned to 0dc97d3eb6b8. You have to delete (or rename) that container to be able to assign cadvisor to a container again."
Mar 06 23:00:33 deis-03 systemd[1]: cadvisor.service: main process exited, code=exited, status=1/FAILURE
Mar 06 23:00:33 deis-03 systemd[1]: Unit cadvisor.service entered failed state.
Mar 06 23:00:33 deis-03 systemd[1]: cadvisor.service failed.
```

How to start cadvisor again? Do I have to manually go through and SSH to all machines to `docker rm -f cadvisor` the containers and their images?

And why don't needed containers, such as the ceph monitor container, start when the node goes back up? I'm absolutely certain a restart will bite me in the ass at some point, me failing to notice it and then another node crashing, pulling everything down with it. So I'd rather save my ass when I have time to learn how to do it. ;)

### PR DESCRIPTION
**Pull request by haf**
fixes #3221

### CODE REVIEW

**Comment by bacongobbler** [comment]
Lgtm

**Comment by carmstrong** [comment]
Thanks @haf. Could you amend your commit to something like `docs(platform_monitoring): make cAdvisor unit more resilient`? That's in line with our commit style guidelines. 

I edited the PR body so it'll automatically close #3221. Thanks!

**Comment by haf** [comment]
Done

**Comment by haf** [comment]
Done, ping

**Comment by carmstrong** [comment]
> Done, ping

Can you remove the "fixes" prefix from the commit? We need them to start with our commit style guidelines so they're picked up by the script which generates the changelog for our releases. It should just be: `docs(platform_monitoring): make cAdvisor unit more resilient`.

**Comment by haf** [comment]
Yes

**Comment by mboersma** [comment]
These are nice improvements to the cAdvisor docs. LGTM.

**Comment by carmstrong** [comment]
Thanks @haf! Merging, as this is a safe docs change.

**Pull request merged**
