### PR TITLE
chore(buildpacks): update heroku-buildpack-python to v78

### PR DESCRIPTION
**Pull request by mboersma**
See https://github.com/heroku/heroku-buildpack-python/compare/v77...v78

### CODE REVIEW

**Comment by krancour** [comment]
@mboersma I've done this before and now I can't remember how...

How can I test with a custom build of the slugbuilder based on this branch?

**Comment by krancour** [comment]
Will a custom build of builder bring this along with it?

**Comment by mboersma** [comment]
> Will a custom build of builder bring this along with it?

@krancour yes--`make -C builder deploy` should do it.

**Comment by krancour** [comment]
@mboersma I'll check out all the buildpack updates as soon as I have a window.

**Comment by mboersma** [comment]
@krancour thanks--no rush. It would be nice to get these updates in for the LTS release, but not strictly required.

**Comment by mboersma** [comment]
I tested this with [example-python-django](https://github.com/deis/example-python-django) and [example-python-flask](https://github.com/deis/example-python-flask). 

See also deis/example-python-django#6.

**Pull request merged**
