### PR TITLE
fix(router): add set-misc module to nginx build

### LINKED ISSUE #3964: AffinityArg hangs router on 1.7.3
I'm trying to apply the affinityArg setting on the router…

```
deisctl config router set affinityArg=sid
```

…but I keep getting this error on the logs:

```
[INFO] - 2015/07/04 09:01:12 [emerg] 136#0: unknown directive "set_random" in /opt/nginx/conf/.nginx.conf102133528:140
[INFO] - waiting for confd to write initial templates...
```

If I remove the setting, everything goes back as normal.

Have I done something wrong?

### PR DESCRIPTION
**Pull request by fabiob**
This is the missing piece, so that the PR #3768 can work.

Fixes #3964.

### CODE REVIEW

**Comment by wenzowski** [comment]
well done @fabiob, thanks!

**Comment by technosophos** [comment]
This is necessary to get `set_if_empty` and `set_random`, right?

LGTM

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by mboersma** [comment]
Could you rebase this off current Deis master? Sorry for the hassle. Unfortunately nothing's going to pass CI now unless it includes #3968.

**Comment by fabiob** [comment]
I don't know if I did it right…

**Comment by bacongobbler** [comment]
Looks like a bunch of other commits made it in here. No worries, we can just cherry-pick your commit and test that against master :)

**Comment by fabiob** [comment]
I think those additional commits are from deis:master… I rebased and pushed my branch before rebasing my own master, so the PR tool on Github thinks they are new. But it should merge fine.

**Comment by fabiob** [comment]
In the meantime… Is there any instructions on how to build this image, so I can use it as a custom router image? I tried to build using `docker build .`, but the resulting image fails to run with:

```
Error response from daemon: No command specified
```

**Comment by bacongobbler** [comment]
http://docs.deis.io/en/latest/contributing/hacking/ should help you get started with building custom images :)

**Comment by mboersma** [comment]
@fabiob I cherry-picked the commit and opened #3965--hope that's ok. Thanks again!

**Pull request closed without merging**
