### PR TITLE
ref(controller): share common scheduler code

### PR DESCRIPTION
**Pull request by mboersma**
Defines a `SchedulerClient` class to represent the interface that schedulers should implement, and subclasses existing schedulers from that. `attach` was unimplemented anywhere, so I removed it.

Also normalizes some code comments and removes extra code.

### CODE REVIEW

**Comment by bacongobbler** [comment]
LGTM. Everything was based from MockScheduler but it's better to have something like this. Perhaps to be clear, should this be called AbstractSchedulerClient? What's the convention here?

**Comment by mboersma** [comment]
> Everything was based from MockScheduler

Actually only ChaosScheduler subclassed that (and still does); all other schedulers derived from `object`. I can call it `AbstractSchedulerClient`, that's probably more conventional.

**Comment by carmstrong** [comment]
Code LGTM. Note that merging this will require yet another rebase for #3975, so we may want to merge that PR first and then add k8s to this PR.

**Comment by mboersma** [comment]
Agreed--I'll update this after k8s is merged, which will provide still more reason for sharing common scheduler code and defining the interface.

**Pull request merged**
