### PR TITLE
docs(docs/using_deis/register-user.rst): note re controller on 8000 for

### PR DESCRIPTION
**Pull request by ianmiell**
dockers

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
If you set up the DNS records correctly as per http://docs.deis.io/en/latest/managing_deis/configure-dns/#configure-dns, `http://deis.deisapp.com` will forward traffic to your controller. Could you please explain your issue more clearly as well as the instructions on how you got there?

For example, I have my DNS records set up for Digital Ocean like so (no load balancing available, so I'm using round robin DNS instead):

```
><> dig +noall +answer deis.fishworks.io
deis.fishworks.io.	1796	IN	CNAME	deis-1.fishworks.io.
deis-1.fishworks.io.	1796	IN	CNAME	deis-2.fishworks.io.
deis-2.fishworks.io.	1796	IN	CNAME	deis-3.fishworks.io.
deis-3.fishworks.io.	1796	IN	A	104.130.198.72
```

Note to others, this refs https://github.com/deis/deis/issues/291#issuecomment-71442655

**Comment by ianmiell** [comment]
That seems to contradict what's on here:

http://docs.deis.io/en/latest/installing_deis/digitalocean/

or am I missing something?

**Comment by bacongobbler** [comment]
From that same section:

> One way to configure this on DigitalOcean is to setup round-robin DNS via the DNS control panel. To do this, add the following records to your domain:

>- A wildcard CNAME record at your top-level domain, i.e. a CNAME record with * as the name, and @ as the canonical hostname
>- For each CoreOS machine created, an A-record that points to the TLD, i.e. an A-record named @, with the droplet’s public IP address

After you're done that, `deis.domain.com` will route to the controller, provided that there's a router on the host you connected to.

**Comment by mboersma** [comment]
You shouldn't access the controller at port 8000, but at port 80 prefixed by `deis`.
```console
$ deis register http://deis.mydomain.com/
```
Otherwise, your DNS configuration isn't working correctly.

**Comment by ianmiell** [comment]
Thanks (and thanks for the quick response). I'll try that now.

BTW, this is for this blog post: https://zwischenzugs.wordpress.com/2015/01/26/set-up-a-deis-docker-friendly-paas-on-digital-ocean-for-0-18-per-hour-in-six-easy-steps-using-shutit/

(so you can even repro the steps to set up yourself if you're so inclined; it's how I'm testing it now).

The code is here: https://github.com/ianmiell/shutit-coreos-do/blob/master/deis/deis.py

**Comment by ianmiell** [comment]
That worked a treat, thanks.

"Note that you always use deis.<domain> to communicate with the controller."

I failed to read the docs properly. Closing.

**Comment by ianmiell** [comment]
(Actually, I recall reading that and thinking it was referring to the deis binary and that the dot was a typo. Duh.)

**Pull request closed without merging**
