### PR TITLE
feature(deisctl): add install wizard

### PR DESCRIPTION
**Pull request by krancour**
Addresses #2812

I would not consider actually merging this!  I'm putting it out there as a straw man for constructive criticism on the approach.  I could also use some help figuring out how to test this.

Documentation is missing.  I'll amend the PR with doc updates once we settle on an approach.

### CODE REVIEW

**Comment by bacongobbler** [comment]
How do you want us to test this? Without proper documentation we don't have anything to nitpick or follow when testing these new features.

As for tests, I'd break out the `start/stop/install/uninstallServices()` into two separate functions:

 - `getServices()` which takes a supplied install config (from the wizard or from `start platform`) that will return the services requested to install
 - `startServices()` which tells the backend to boot said services

There won't be a way to test `startServices()` because it's hard to mock fleet, but we should be able to write unit tests for supplying a config and getting back a list of services to install.

**Comment by krancour** [comment]
@bacongobbler Sorry... like I said... a straw man.  Didn't invest time in documentation knowing this was all likely to change.  Here's some micro doc:

Traditional install; works the same as it always has:
```
$ deisctl install platform
```

(Caveat to the above is that if you have previously run the wizard, then uninstalled, and are now re-installing, the options you selected the first time around will still be respected since they're stored in etcd.)

Wizard-based:
```
$ deisctl install platform --wizard
```

Or this works too:
```
$ deisctl install platform -w
```

Unattended:
```
$ deisctl install platform --config=<file>
```

File takes the following form:
```
/any/etcd/key=value
/another/etcd/key=value
```

Re: breaking functions like `start/stopServices()` into separate `getServices()` and `start/stopServices()` functions as you have suggested-- I totally like the idea (it sounds cleaner), but even just looking at existing code in the master branch, wouldn't such a change be complicated by the logic needed to start/stop things in a certain order and wait for certain things?  For example, if starting the whole platform, we couldn't just rip through a list of `[ store-monitor, store-daemon, ..., publisher, router@* ]` and start each in turn.  There is (existing) logic that knows where to wait and what things can be started in parallel.  Same goes for the order in which things comes down.

Maybe `getServices()` could return a two dimensional array?  We could then iterate over _groups_ of things to start / stop / etc., with `wg.Wait()` between groups.  If we did that, we'd have to find some clever way to also maintain the output channel messages about different subsystems.  It would call for a more complex data structure than the two dimensional array.  Something like the following:

```
[
  { subsystem: 'subsys-1', services: [ [ 'service-1' ], [ 'service-2', 'service-3' ] ] },
  { subsystem: 'subsys-2', services: [ [ 'service-4' ] ] }
]
```

Seems doable, but then knowing that the order to stop thing varies from the order in which to start things, requiring us to wait in different points, what we'd end up with is logic that looks almost identical to the existing logic, just in a different method.  So I wonder if we'd just end up with code very similar to what we started with.

Just thinking out lout.

**Comment by krancour** [comment]
Cross posting: #3262 affects / is affected by this PR.

**Comment by krancour** [comment]
@bacongobbler thinking more about your advice to separate some logic from the `start/stop/etc()` functions into a separate `getServices()` function.  I still think that complicates things a little, but I also think I get where you were going with it now.  You mentioned that it's tough to actually test against `fleet`, so was your line of thinking that the data structure produced by `getServices()` is something that we could more easily make assertions against without having to involve `fleet`?  Sorry if I didn't pick up on that right away.

What if there's another way to make unit testing easier wherever actual `fleet` integration is a concern we wish to avoid?  I come (most recently) from the Ruby world where its dynamic nature means we don't think twice about mocking/stubbing a dependency.  With Go being compiled and statically typed, that's a more difficult proposition here, but not impossible.  What if I were to invest the time in creating an alternate implementation of the `Backend` interface that's specifically aimed at enabling more isolated tests?  Such an implementation could simply keep track of what services are loaded, started, stopped, destroyed, etc.  This could be injected into any other code under test that's normally dependent on `fleet` and any such test can conclude by querying the test implementation of the `Backend` interface to assert that the things that were suppose to happen on the backend _would have_?

In this manner, we could _easily_ test that the right things get loaded and started in the various scenarios where a an operator opts into or out of a particular component or subsystem.

I think this would be useful beyond testing just this install wizard feature as well.  It seems it could be used in a lot of places where tests are maybe lighter than they should be, owing to their dependency on fleet.

What do you think?

P.S. Testing the interactive aspects of the wizard will still be a pain.  Still thinking through that.  Gexpect looked promising, initially, but now I have my doubts.

**Comment by bacongobbler** [comment]
> was your line of thinking that the data structure produced by getServices() is something that we could more easily make assertions against without having to involve fleet? Sorry if I didn't pick up on that right away.

yes indeed. Some coverage is better than no coverage :)

> What if I were to invest the time in creating an alternate implementation of the Backend interface that's specifically aimed at enabling more isolated tests?

I'd be so happy if you could write out a backend that works for tests. If you can come up with one for deisctl so we can rely on them instead of having to rely on testing by hand, I'll give you all of my shiniest marbles. I once tried to do this but was sidetracked with other feature work so I never got around to it.

**Comment by krancour** [comment]
If I do it, it won't be anything too crazy... just something to keep track of what would have happened on the backend if it were real.  Think that's adequate for now?

**Comment by bacongobbler** [comment]
sure, that'd be adequate

**Comment by mboersma** [comment]
I realize this is a WIP, but just to note this PR currently fails with a `gofmt` error:
```console
make[1]: Entering directory `/var/lib/jenkins/jobs/test-ec2/workspace@2/src/github.com/deis/deis/deisctl'
gofmt -l backend client cmd config utils deisctl.go deisctl_test.go
cmd/cmd.go
cmd/wizard/wizard.go
gofmt check failed.
make[1]: *** [test-style] Error 1
```

**Comment by bacongobbler** [comment]
@krancour according to your latest comment on the bug, it seems like you're retracting from this proposal. In that case, should we close this?

**Comment by krancour** [comment]
@bacongobbler I'm honestly not sure at this point.  I'm strongly of the opinion that it needs to be easier to customize Deis clusters.  #2182 started with a few folks wanting it to be easier to install Deis without the storage subsystem.  I think it's easy enough to make something like that optional by means of an install wizard.  I think such an approach could easily take the pain out of all the most _common_ configuration options (log drains, etc.)

On the other hand, I get the sense that the level of customization that some people do is far more extensive and a framework for permitting such people to orchestrate the launch of Deis with their customizations seems like it would be a useful addition.  (My own use case is Deis with customized unit files and images - storage subsystem + monitoring stack.)

I think at this point I'm convinced that the latter has more value for myself, but I'm also interested in what provides the most value to the _community_.  Maybe there is room for both approaches?  Idk.  I'm really interested in hearing others sound off on this.

**Comment by carmstrong** [comment]
@krancour Does it make sense to close this until an implementation is agreed upon in #3635?

**Comment by krancour** [comment]
@carmstrong I think they may be unrelated.  I think I see this issue as having to do with _what_ runs, while seeing #3635 as having more to do with _where_ things run (as a consequence of a cluster's architecture).

That being said, I have backed off on the notion of an install wizard a little bit, because I think a framework for customizing and orchestrating install and launch of units might be more valuable.  (Tangent: such a framework need not even be Deis-specific.)

Ultimately, I might come back to this, but for right now, I'm not thinking so.  It should come off the radar for now.

**Pull request closed without merging**
