### PR TITLE
fix(client): only delete local ~/.deis/client.json if cancelling logged in user

### LINKED ISSUE #4896: [client] `deis auth:cancel --username=someuser` removes ~/.deis/client.json
When calling `deis auth:cancel --username=someuser` to remove a user different than the one which is currently logged in, the deis client removes `~/.deis/client.json`. This is only the expected behaviour when   removing the currently logged in user (e.g. without the --username argument).

### PR DESCRIPTION
**Pull request by helgi**
Fixes #4896

### CODE REVIEW

**Comment by carmstrong** [comment]
Failure seems to be relevant:
```
auth:register http://deis.test-d838656bca.deis.works --username=cancel-test --password=test --email=test@test.co.nz
Registered cancel-test
Logged in as cancel-test
ok
auth:login http://deis.test-d838656bca.deis.works --username=test --password=asdf1234
Logged in as test
ok
auth:cancel --username=cancel-test --yes
Account cancelled
ok
auth:whoami
You are test at http://deis.test-d838656bca.deis.works
--- FAIL: TestAuth (11.66s)
	itutils.go:262: <nil>
FAIL
exit status 1
FAIL	github.com/deis/deis/tests	11.660s
godep: go exit status 1
make[1]: *** [test-full] Error 1
make[1]: Leaving directory `/home/jenkins/workspace/test-ec2/src/github.com/deis/deis/tests'
make: *** [test-integration] Error 2
```

**Comment by bacongobbler** [comment]
indeed. I tried restarting the job a few times to verify but this does look like a legit failure.

**Comment by carmstrong** [comment]
@Joshua-Anderson Any chance you have an idea as to what's happening here?

**Comment by Joshua-Anderson** [comment]
[This line](https://github.com/deis/deis/blob/master/tests/auth_test.go#L53) was checking that the admin is logged out after deleting another user. Apparently this was the behavior of the old python client and the bug that is fixed in this PR happened to persist it in the golang rewrite. You could change this line to make sure the command *doesn't* fail now.

**Comment by bacongobbler** [comment]
rebased and PR'd the changes at #5010. Closing!

**Pull request closed without merging**
