### PR TITLE
feat(router): allow customizing controller subdomain

### LINKED ISSUE #3488: Feature request: customize controller host name
Is there a config option to set the deis controller url? (deis.example.com)
if not there should be. I am runnig in a corporate environment with strict DNS rules

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #3488

### CODE REVIEW

**Comment by carmstrong** [comment]
Is `validate_reserved_names` covered by unit tests for various names?

**Comment by carmstrong** [comment]
We need to add this setting to "Customizing Controller".

**Comment by carmstrong** [comment]
There are also numerous places where we refer to "deis.<domain>". While I think updating all of these to include a disclaimer for a custom subdomain, we should evaluate all uses of it.

**Comment by bacongobbler** [comment]
> Is validate_reserved_names covered by unit tests for various names?

Yes: https://github.com/deis/deis/blob/master/controller/api/tests/test_app.py#L158-L162

> we should evaluate all uses of it.

I'm not quite sure on what "it" is supposed to represent. Do you mean that we add disclaimers where we say `deis.example.com`?

**Comment by carmstrong** [comment]
> I can add tests for this.

:+1:

> I'm not quite sure on what "it" is supposed to represent.

Sorry - looks like GitHub stripped out my `deis.<domain>`. I just want to look at places where we say `deis.<domain>` in the docs and see if we should mention the fact that the host is customizable. 

I just did a quick pass, and if we call this out anywhere, it looks like http://docs.deis.io/en/latest/using_deis/register-user/#register-with-a-controller is the place. Maybe add a note there saying that while deis. is the default, this is a customizable setting, and link to Customizing Controller?

**Comment by bacongobbler** [comment]
Awesome. Thanks for clarifying. I'll update the docs and check for anywhere else :)

**Comment by carmstrong** [comment]
> I'll update the docs and check for anywhere else :)

Cool. We probably don't need it anywhere we're just using it as an example command, but if we're talking about the controller and how to talk to it, we should probably mention the fact that it's customizable. "Register User" is the only place I found, but it's worth another pass. :+1:

**Comment by bacongobbler** [comment]
done!

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by mboersma** [comment]
Code LGTM.

**Pull request merged**
