### PR TITLE
fix(controller) : fix regex for deis limits

### PR DESCRIPTION
**Pull request by pmelmon**
fixes https://github.com/deis/deis/issues/3354

make  deis client regex compatible to docker memory limits

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by mboersma** [comment]
We should add unit tests for the `MEMLIMIT_MATCH` regex, probably to a new `test_limits.py` file in the [api tests](https://github.com/deis/deis/blob/master/controller/api/tests/) directory. We could also tweak [`limits_test.go`](https://github.com/deis/deis/blob/master/tests/limits_test.go#L14) to test variations other than `256M`.

**Comment by mboersma** [comment]
Also it should be `re.IGNORECASE` (dot, not comma) and it needs a space before it:
```console
venv/bin/flake8
./api/serializers.py:20:66: E231 missing whitespace after ','
./api/serializers.py:20:69: E231 missing whitespace after ','
./api/serializers.py:20:70: F821 undefined name 'IGNORECASE'
make[1]: *** [test-style] Error 1
```

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by mboersma** [comment]
Code LGTM. Thanks!

**Pull request merged**
