### PR TITLE
feat(router) nginx status; log http_host, upstream and request times

### PR DESCRIPTION
**Pull request by lorieri**
Improve monitoring of the deis cluster

 * Added stub_status
 * More stats in the log
  * request_time
  * upstream_response_time

### CODE REVIEW

**Comment by lorieri** [comment]
When a request come with an old removed app the request returns 200 making hard to detect problems, the http_host in the log can help checking if a app exists

upstream and request times helps to detect buggy apps and/or units

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by aledbf** [comment]
@lorieri why not append the new fields in log_format at the end? Just in case someone it's parsing the output

**Comment by lorieri** [comment]
@aledbf ok, I grouped by "meaning", let me change it

**Comment by mboersma** [comment]
stub_status is built in I see. This adds some useful data. Code LGTM.

**Comment by lorieri** [comment]
@mboersma I tested the stub with deis-router image
cheers

**Pull request merged**
