### PR TITLE
ref(contrib): do not enable proxyProtocol on AWS

### LINKED ISSUE #4400: Force SSL behind AWS ELB results in a redirect loop.
`deisctl config router set enforceHTTPS=true`

Results in redirect loop on Cephless 1.9 install.

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #4400

### CODE REVIEW

**Comment by carmstrong** [comment]
ping @blystad and @johanneswuerbach - proxy protocol support was first attempted in #2717 and then implemented in #3096. I want to ensure we're fully aware of the implications of disabling it.

**Comment by Blystad** [comment]
Ping acknowledged (thanks!).

I've briefly read into the issue...We redirect port 80 -> 80 and 443 -> 443...couldn't we simply get if it's HTTP or HTTPS from the port?

Something like:
```
if incoming port = 443
   type = HTTPS
else
   type = HTTP
```

**Comment by johanneswuerbach** [comment]
Thanks for the ping :-) Disabling proxy protocol will basically limit you to the features exposed by elb, no websocket, no elb, no custom ssl. Did somebody use that, I can't tell.

**Comment by Blystad** [comment]
We used websockets, which was my motivation for contributing this. It would be great to get rid of it...but AWS seems to want to add service #1001 rather than improve their existing services :(

**Comment by bacongobbler** [comment]
To be clear the motivation is to keep this a part of the router, but disable it by default. There have been issues with SSL redirection with proxy protocol enabled because certain headers typically populated by the ELB like `http_x_forwarded_proto` were not being sent, which is what SSL redirection relies on.

If you still want websocket support you'll just have to run `deisctl config router set proxy protocol=1` to enable it and everything is all honkey-dory. If you're upgrading from an older cluster this setting was already enabled so the upgrade path is not broken with this change either. This just turns it off by default so users who are aware of this feature can enable it, but it won't hurt others working with other nginx modules. Makes sense? :)

**Comment by bacongobbler** [comment]
To elaborate, the TCP listener in the ELB does not send those HTTP headers other modules were expecting, not proxy protocol itself. By changing the listener type to TCP we lost those headers, but nobody really noticed until 6 releases later :)

**Comment by Blystad** [comment]
Right, but can't we assign the headers based on the incoming port?

It's not just running deisctl blablabla, you also have to run various AWS
commands to enable proxy protocol on the ELB.

This PR feels like it tries to solve the symptom rather than the problem.

**Comment by krancour** [comment]
I'd like to experiment with this a bit before we consider merging.

**Comment by bacongobbler** [comment]
I'm doing exactly that. I want to check what headers are available and what are not when proxy protocol is enabled/disabled.

**Comment by krancour** [comment]
@bacongobbler per comments in #4400 (which I have now closed), I don't think this solves anything.  I would move that we close this PR as well.

**Pull request closed without merging**
