### PR TITLE
fix(client): require the tag for builds:create

### LINKED ISSUE #2830: Docker image pull hangs if latest tag does not exist
Steps to reproduce:
 - deis create foo
 - deis pull giorgos/masterfirefoxos

waits forever while it should return saying that no 'latest' tag exists and that user should define a tag to pull.

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #2830

### CODE REVIEW

**Comment by carmstrong** [comment]
Should we also enforce this at the backend/API level, or is not worth bothering?

**Comment by bacongobbler** [comment]
I recall us having this discussion last week and we decided that it was fine to just patch it in the client for now

**Comment by carmstrong** [comment]
> I recall us having this discussion last week and we decided that it was fine to just patch it in the client for now

That's fine, that's why I was asking :)

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by mboersma** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
One thing I haven't tested was `deis pull ip-addr:5000/deis/example-go`, which would pass. I think it's high time we add client unit tests. Would that be acceptable?

**Comment by carmstrong** [comment]
> One thing I haven't tested was deis pull ip-addr:5000/deis/example-go, which would pass.

Good point.

> think it's high time we add client unit tests. Would that be acceptable?

Rewriting the client in Go was one thing @Joshua-Anderson mentioned he'd be interested in taking a stab at once he starts :) I think that'd be a good time to write unit tests, as well.

**Comment by bacongobbler** [comment]
okay, I've just imported the `parse_repository_tag` method from docker-py so we don't have to install another library. The logic is simple enough, anyhoo. I'll punt on client tests :sheep:

**Comment by carmstrong** [comment]
Amended code LGTM.

**Comment by mboersma** [comment]
LGTM++.

**Pull request merged**
