### PR TITLE
feat(pkg/prettyprint) support colorizing terminal text

### PR DESCRIPTION
**Pull request by technosophos**
This provides pretty printing features for the following:

- Colorized Deis logos
- Colorized messages
- Line replacement messages (i.e. when one line overwrites the previous line)

### CODE REVIEW

**Comment by bacongobbler** [comment]
deisify all the things!

LGTM

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by carmstrong** [comment]
@mboersma Would like to delay merging this.

**Comment by mboersma** [comment]
I just wanted to make the commit subject more compliant--looks good now. (50-character restriction debate continues offline).

Code LGTM.

**Pull request merged**
