### PR TITLE
docs(contributing): remove reference to `deisctl ssh`

### PR DESCRIPTION
**Pull request by carmstrong**
@mhahn pointed out in IRC that this command doesn't actually exist.

### CODE REVIEW

**Comment by carmstrong** [comment]
I killed Jenkins after it passed the docs: https://ci.deis.io/job/test-integration/2162/console

**Comment by bacongobbler** [comment]
Doesn't `deisctl list` show the internal IPs which means that you cannot directly SSH into the nodes unless you're in the cluster?

**Comment by carmstrong** [comment]
> Doesn't deisctl list show the internal IPs which means that you cannot directly SSH into the nodes unless you're in the cluster?

Yes, but I'm assuming they're either on the cluster or can translate the internal IP to map to the proper machine.

**Comment by bacongobbler** [comment]
Okay, sounds good. lgtm :)

**Comment by mboersma** [comment]
Oops, thanks for catching the doc-bug. LGTM.

**Pull request merged**
