### PR TITLE
chore(router): update nginx to 1.8

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Changes: http://nginx.org/en/CHANGES-1.8

### CODE REVIEW

**Comment by carmstrong** [comment]
@aledbf Had mentioned waiting for 1.9 mainline, since TCP support will be pulled into nginx proper rather than relying on an external patch.

Thoughts?

**Comment by bacongobbler** [comment]
> *) Bugfix: in the ngx_http_spdy_module

We use this module so I'm wondering what the relevant bugfix was for it.

**Comment by johanneswuerbach** [comment]
Oh, I didn't know about that. Despite that I think it should still be bumped to 1.8 as 1.8 includes a few bug fixes and 1.9 might not work ootb.

**Comment by mboersma** [comment]
My only issue is the "optics" of being on the 1.8 Release branch versus the 1.9 Dev branch (at least that's how I understand nginx to be). I know we switched off 1.6 to 1.7 at some point, and that real nginx users say there's little difference in stability between the two, but the even-numbered versions *should* be more stable.

So that's an indirect argument in favor of this PR versus waiting for 1.9.

**Comment by carmstrong** [comment]
I'm fine with shipping this now and discussing the 1.9 bump when it's time. Code LGTM.

**Comment by mboersma** [comment]
Code LGTM. Let's have @aledbf or @bacongobbler glance at this too before we merge it.

**Comment by aledbf** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
I've been silently following this issue. Code LGTM

**Pull request merged**
