### PR TITLE
fix(controller): change one-off resp body to dict

### PR DESCRIPTION
**Pull request by spg**
http://docs.deis.io/en/latest/reference/api-v1.5/#run-one-off-commands
Changes response body from [0, "hi"] to {"rc": 0, "output": "hi"}.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by carmstrong** [comment]
Jenkins, add to whitelist.

**Comment by Joshua-Anderson** [comment]
ref #3988 

This is a backwards incomparable change, so this will probably require a api version bump to v2.

I personally like the change. Returning JSON is much cleaner than a dynamic array!

It's odd that this code isn't covered by tests ( some of the run errors are, but not the actual response itself).

**Comment by bacongobbler** [comment]
I swore we had unit tests but I guess not. @spg would you mind adding some to https://github.com/deis/deis/blob/master/controller/api/tests/test_app.py so this won't be accidentally changed in the future? Thanks!

**Comment by bacongobbler** [comment]
We'll also need to bump the API to v2 as @Joshua-Anderson mentioned.

**Comment by spg** [comment]
@bacongobbler sure thing

**Comment by spg** [comment]
@bacongobbler test added! 

For some reason, I had to use `TransactionTestCase`, otherwise, when running my test, I'd get:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/spg/deis/controller/api/models.py", line 52, in _close_db_connections
    ret = func(*args, **kwargs)
  File "/Users/spg/deis/controller/api/models.py", line 522, in create
    kwargs = {'memory': self.release.config.memory,
  File "/Users/spg/.virtualenvs/deis/lib/python2.7/site-packages/django/db/models/fields/related.py", line 320, in __get__
    rel_obj = qs.get()
  File "/Users/spg/.virtualenvs/deis/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: Config matching query does not exist.
```

All tests in `api.AppTest` pass using `TransactionTestCase`

**Comment by bacongobbler** [comment]
@carmstrong does this look good to you? I'll follow up with an API bump to 2.0 after this is merged.

**Comment by carmstrong** [comment]
> does this look good to you?

Code looks fine to me, but I'm wondering how big of a deal bumping the API to 2 is. Are there other things we want to get in as part of it?

/cc @mboersma

**Comment by Joshua-Anderson** [comment]
@carmstrong We could fully deprecate the X prefixed headers.

**Comment by carmstrong** [comment]
I'd like @mboersma's thoughts on this one.

**Comment by kalbasit** [comment]
Accidentally closed the PR.

**Comment by Joshua-Anderson** [comment]
@spg For V2, deis was broken up into a repository for each component. I've reused some of your changes in a PR for the deis V2 controller (deis/workflow#58). Feel free to review and comment. :smiley:

I'm going to close this PR since backwards incompatible changes are not going to be accepted in deis V1 and there is a equivalent PR for deis V2.

Thank you so much for your contribution!

**Pull request closed without merging**
