### PR TITLE
chore(tests): update vendored docker code to 1.5.0

### PR DESCRIPTION
**Pull request by Joshua-Anderson**

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
I have no idea why these tests are failing on jenkins, as they pass locally.

**Comment by sgoings** [comment]
Fails on my machine with the same error:

```
 ~/go/src/github.com/deis/deis  ⑂ v1.8.0-116-g6eeb01b +    make -C builder test-functional
godep go test -v ./tests/...
go build github.com/docker/docker/pkg/symlink: no buildable Go source files in
go build github.com/docker/docker/pkg/urlutil: no buildable Go source files in
FAIL	github.com/deis/deis/builder/tests [build failed]
godep: go exit status 1
make: *** [test-functional] Error 1
```

**Comment by Joshua-Anderson** [comment]
@sgoings I didn't add some new packages to godeps, but godep fell back to `$GOPATH` and found them. Should be fixed now!

**Comment by Joshua-Anderson** [comment]
The tests seem to be failing because `--- Publish etcd keys and values` hangs. I don't think this is related to this PR, as I am also consistently seeing it in #4116

**Comment by mboersma** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
code LGTM

**Pull request merged**
