### PR TITLE
feat(client-go): add config endpoint

### PR DESCRIPTION
**Pull request by Joshua-Anderson**

### CODE REVIEW

**Comment by mboersma** [comment]
Code LGTM.

**Comment by Joshua-Anderson** [comment]
I pulled out the config list tabbed printing into `pkg/prettyprint` to be more DRY (I need to use the code in another branch).

**Comment by technosophos** [comment]
Code LGTM

**Comment by carmstrong** [comment]
@Joshua-Anderson Rebase needed :cry:

**Comment by Joshua-Anderson** [comment]
Rebased!

**Comment by carmstrong** [comment]
We should probably let Jenkins pass this again given the changes to the root Makefile.

**Comment by carmstrong** [comment]
Build failure seemed to be unrelated, so I kicked off another one: https://ci.deis.io/job/test-ec2/2042/

**Pull request merged**
