### PR TITLE
docs(installing_deis): etcd doesn't require an odd # of nodes

### PR DESCRIPTION
**Pull request by mboersma**
ping @gabrtv.

### CODE REVIEW

**Comment by gabrtv** [comment]
Thanks for the quick turnaround. LGTM!

**Comment by carmstrong** [comment]
We say that because of https://coreos.com/docs/cluster-management/scaling/etcd-optimal-cluster-size/

"The other important cluster optimization is to always have an odd active cluster size (i.e. activeSize). Adding an odd node to the number of peers doesn't change the size of the majority and therefore doesn't increase the total latency of the majority as described above. But, you gain a higher tolerance for peer failure by adding the extra machine. You can see this in practice when comparing two even and odd sized clusters:"

Maybe require is too strong a word, but I've always thought it was a best practice for failure tolerance.

**Comment by gabrtv** [comment]
While it's true a standalone etcd cluster needs an odd number of nodes, this has not been true of Deis clusters since introduction of standby mode in etcd 0.4: https://coreos.com/blog/etcd-0.4.0/

**Comment by mboersma** [comment]
Thanks @carmstrong--I knew that was in there somewhere but couldn't find it. Sounds like an odd-sized cluster is somewhere between an optimization and best practice, but not strictly required. We could change the wording here to "recommended"...

**Comment by carmstrong** [comment]
@gabrtv I guess I still don't understand why standby mode changes this, since it has to do with failure tolerance. I thought standby mode was for larger clusters so we're not waiting on writes to persist throughout the whole cluster?

**Comment by gabrtv** [comment]
After some reading it seems standby mode has been deprecated for proxy mode in etcd2: https://github.com/coreos/etcd/blob/556713739c01fa1ebafdf53c8d1f87d6d33367bf/Documentation/backward_compatibility.md#standby

Either way we should merge this PR as we don't want to scare folks away from even-sized clusters (either planned or accidental) because they work just fine per the table on: https://coreos.com/docs/cluster-management/scaling/etcd-optimal-cluster-size/#odd-active-cluster-size

**Comment by mboersma** [comment]
We should ensure that we have links to specific etcd docs justifying this and talking about tuning.

**Comment by mboersma** [comment]
Updated with a consistent reference to our Cluster Size section, and added a link to CoreOS' "optimal cluster size" doc.

**Comment by carmstrong** [comment]
LGTM. I see the issue with our "clusters must have an odd number of nodes" language.

**Comment by gabrtv** [comment]
LGTM, thanks everyone!

**Pull request merged**
