### PR TITLE
chore(*): bump CoreOS to 681.0.0

### PR DESCRIPTION
**Pull request by mboersma**
See https://coreos.com/releases/#681.0.0

### CODE REVIEW

**Comment by carmstrong** [comment]
We may as well bump Docker's builder to 1.6.2 as part of this, right? Or is that blocked by registry v2?

**Comment by mboersma** [comment]
> Or is that blocked by registry v2?

Yep. They API changed in an incompatible way, so Docker 1.6.x won't work with the existing registry, but I'm working on that in my [new-dev-registry](https://github.com/mboersma/deis/tree/new-docker-registry) branch.

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by aledbf** [comment]
Code LGTM.

**Pull request merged**
