### PR TITLE
fix(controller): force uniqueness for default app name.

### LINKED ISSUE #2831: fix(controller): generate_app_name should re-roll on duplicate name
Lurking through old comments, I found https://github.com/deis/deis/issues/475#issuecomment-32907618. If we find an existing app name when generating a random app name, we should re-roll `generate_app_name()` until we find a new name for the application, otherwise we will hit a 500 error because the application name already exists.

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
Fixes #2831

### CODE REVIEW

**Comment by bacongobbler** [comment]
code LGTM. Another question would be how we're gonna handle this problem when we theoretically use up at least half of the available app names since we're more or less going to come up with name collisions fairly often.

**Comment by Joshua-Anderson** [comment]
>Another question would be how we're gonna handle this problem when we theoretically use up at least half of the available app names 

Yeah, that could start to cause problems. Luckally I don't think too many people have a significant number of apps with random names. Worst case scenario we can add more weird adjectives and nouns ( or the generate name algorithm can be rewriten to limit itself to selecting names that already exist, but that's much less fun)! :smiling_imp:

**Comment by Joshua-Anderson** [comment]
The CI seems to have timed out. Could somebody please restart it?

**Comment by mboersma** [comment]
This doesn't solve the problem of "diminishing randomly-generated app namespace", but it avoids the occasional collision which I think is of higher concern.

I think it might be cleaner to have `select_app_name` implemented in `models.py` itself. The `utils.py` module was blissfully unaware of all the Django machinery until it imported the `api` module.

**Comment by bacongobbler** [comment]
> I think it might be cleaner to have select_app_name implemented in models.py itself. The utils.py module was blissfully unaware of all the Django machinery until it imported the api module.

I agree. If we're using the models anyways, we should move it over there.

**Comment by Joshua-Anderson** [comment]
I moved the function to `models.py` but the tests timed out again.

**Comment by carmstrong** [comment]
> but the tests timed out again.

Not your PR - we're looking into an issue caused by leftover cruft.

**Comment by carmstrong** [comment]
Code LGTM and Jenkins has passed.

**Comment by mboersma** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
> If we're using the models anyways, we should move it over there.

this is something we can clean up after we merge this :)

**Comment by carmstrong** [comment]
> this is something we can clean up after we merge this :)

He already did it in this PR?

**Comment by bacongobbler** [comment]
Oh! I meant by attaching it to the App model rather than as a standalone function. Not really a huge issue, just nitpicking.

**Pull request merged**
