### PR TITLE
fix(controller): Ignore KeyError

### PR DESCRIPTION
**Pull request by duanhongyi**
1、Execute the following command: `deis apps`,Then the output：

=== Apps
dockerfile-test
celery

2、Execute the following command:`deis apps:destroy --app=celery --confirm=celery`,Then the output：

Destroying celery... 
500 INTERNAL SERVER ERROR

3、Execute the following command:`deisctl journal controller`,Then the output：

Jan 08 07:43:54 deis-3 sh[21544]: response = handler(request, *args, **kwargs)
Jan 08 07:43:54 deis-3 sh[21544]: File "/app/api/views.py", line 220, in destroy
Jan 08 07:43:54 deis-3 sh[21544]: obj.delete()
Jan 08 07:43:54 deis-3 sh[21544]: File "/app/api/models.py", line 147, in delete
Jan 08 07:43:54 deis-3 sh[21544]: return super(App, self).delete(*args, **kwargs)
Jan 08 07:43:54 deis-3 sh[21544]: File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 695, in delete
Jan 08 07:43:54 deis-3 sh[21544]: collector.delete()
Jan 08 07:43:54 deis-3 sh[21544]: File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 282, in delete
Jan 08 07:43:54 deis-3 sh[21544]: sender=model, instance=obj, using=self.using
Jan 08 07:43:54 deis-3 sh[21544]: File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 185, in send
Jan 08 07:43:54 deis-3 sh[21544]: response = receiver(signal=self, sender=sender, **named)
Jan 08 07:43:54 deis-3 sh[21544]: File "/app/api/models.py", line 866, in _etcd_purge_app
Jan 08 07:43:54 deis-3 sh[21544]: _etcd_client.delete('/deis/services/{}'.format(appname), dir=True, recursive=True)
Jan 08 07:43:54 deis-3 sh[21544]: File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 389, in delete
Jan 08 07:43:54 deis-3 sh[21544]: self.key_endpoint + key, self._MDELETE, params=kwds)
Jan 08 07:43:54 deis-3 sh[21544]: File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 582, in api_execute
Jan 08 07:43:54 deis-3 sh[21544]: return self._handle_server_response(response)
Jan 08 07:43:54 deis-3 sh[21544]: File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 598, in _handle_server_response
Jan 08 07:43:54 deis-3 sh[21544]: etcd.EtcdError.handle(**r)
Jan 08 07:43:54 deis-3 sh[21544]: File "/usr/local/lib/python2.7/dist-packages/etcd/__init__.py", line 142, in handle
Jan 08 07:43:54 deis-3 sh[21544]: raise exc(msg)
Jan 08 07:43:54 deis-3 sh[21544]: KeyError: 'Key not found : /deis/services/celery'
Jan 08 07:43:54 deis-3 sh[21544]: 172.17.8.101 "DELETE /v1/apps/celery HTTP/1.0" 500 - "python-requests/2.4.3 CPython/2.7.8 Linux/3.16.0-28-generic"

4、Conclusion

Some special cases can lead to etcd key creation failed,Suggest ignoring some KeyError exception

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
@duanhongyi, thanks very much for the contribution. But I can't reproduce the problem you described. This is using Deis v1.1.1:
```console
$ deis apps
=== Apps
drafty-villager
celery
$ deis apps:destroy --app=celery --confirm=celery
Destroying celery... 
done in 6s
Git remote deis removed
```
Do you have a set of steps I could follow to reproduce the issue from scratch?

**Comment by bacongobbler** [comment]
this was probably due to an etcd failure, which then the key was never populated. The key is generated on apps:create so normally this should not occur.

**Comment by duanhongyi** [comment]
@mboersma

This is a test service, has been running for more than 1 months.
No special operations, midway because of network problems occurred several times database switch.

The hardware and software environment：
32G Memory
Ubuntu 14.04
Vagrant 1.6.5
coreos 4G * 3
Deis v1.1.1

**Comment by duanhongyi** [comment]
@bacongobbler

But once it happens, it will lead to a app never delete.
I think,standing in the angle of design, this should not be a HTTP500 status, nor should it fail to delete.

**Comment by bacongobbler** [comment]
I agree. It should still delete the application, even if we fail to delete the key for whatever reason. It's cleanup more than anything.

code LGTM from my point of view, though I'd remove the misleading commends in the code (I can't think of a way that _etcd_publish_key() would be skipped unless you can reproduce the effect).

**Comment by duanhongyi** [comment]
Very much agree with you:

'I can't think of a way that _etcd_publish_key() would ever be skipped.'

This may be the problem of etcd.

**Comment by carmstrong** [comment]
> This may be the problem of etcd.

This is most definitely an etcd issue. What likely happened here is that etcd experienced a hiccup at the time we tried setting that key.

Unfortunately, this isn't something we can reasonably address in Deis, as catching potential errors in all the cases where we call etcd would result in a lot of error-catching code that is usually unnecessary for healthy clusters. Also, having the stack trace in the debug output will help us immensely in troubleshooting these sorts of problems with our users.

Thanks for taking the time on this one, @duanhongyi - we certainly appreciate it!

**Pull request closed without merging**
