### PR TITLE
fix(contrib/ec2/provision-ec2-cluster.sh): improve timeout handling for ...

### PR DESCRIPTION
**Pull request by tiaz**
...ec2 cluster provisioning

output remaining time for provisioning/waiting for health checks, and
explicitly declare giving up and why.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by bacongobbler** [comment]
@tiaz would you mine rebasing?

code LGTM!

**Comment by tiaz** [comment]
No problem. I've created a new PR since there was a bit of a rewrite around the other changes to this file. https://github.com/deis/deis/pull/3521

**Pull request closed without merging**
