### PR TITLE
feature(builder): remove shim Dockerfile

### PR DESCRIPTION
**Pull request by technosophos**
Instead of a shim Dockerfile, use ONBUILD directives in the slugrunner Dockerfile. This should not break backward compatibility.

A new Dockerfile is still generated, but it is now done dynamically, and has only FROM and ENV GIT_COMMIT set.

### CODE REVIEW

**Comment by carmstrong** [comment]
Protip for reviewers - review/merge #4273 first and then this one will be cake.

**Comment by technosophos** [comment]
Fixed both of @bacongobbler 's reported issues.

**Comment by bacongobbler** [comment]
Code LGTM!

**Comment by technosophos** [comment]
Superseded by #4324.

**Pull request closed without merging**
