### PR TITLE
Fixes typo =)

### PR DESCRIPTION
**Pull request by codextremist**

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
Thanks! Would you mind amending your commit to follow the style guide such that the changelog generation script will pick up your name? Should be something like `style(deisctl): fix typo`.

lgtm otherwise :)

**Comment by codextremist** [comment]
Ok! No prob!

**Comment by carmstrong** [comment]
Thanks @codextremist! I squashed your commits and pushed them directly to master as 528d686983b93f9e8962901aa071679c97ac0972. Thanks for contributing!

**Pull request closed without merging**
