### PR TITLE
ref(controller): remove scheduler previews

### LINKED ISSUE #4860: remove scheduler tech previews for LTS release
The experiment is finally over, and we are migrating Deis on top of kubernetes for Deis v2! We have had some users now still trying the tech previews in v1, which was never meant to be used in production nor is in any working state. For the LTS release, we should remove these tech previews so users won't be shooting themselves in the foot.

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #4860

### CODE REVIEW

**Comment by carmstrong** [comment]
I'd like @helgi to have eyes on this too

**Comment by mboersma** [comment]
This also effectively fixes a `flake8` linting error that somehow appeared in master and has been failing other PR builds. :+1:

**Comment by carmstrong** [comment]
We'll also need to remove all the documentation around choosing a scheduler - specifically, http://docs.deis.io/en/latest/customizing_deis/choosing-a-scheduler/

**Comment by bacongobbler** [comment]
done!

**Comment by carmstrong** [comment]
Looks like we also mention `schedulerModule` in http://docs.deis.io/en/latest/customizing_deis/controller_settings/, so that'll have to be removed too.

**Comment by bacongobbler** [comment]
thank you for catching my doc blunders. I've removed that line now.

**Comment by mboersma** [comment]
There is also `deisctl` support tied to installing and removing the scheduler preview units, the fleet units files themselves (e.g. `deisctl/units/deis-swarm-node.service`), and the `mesos/` and `swarm/` directories. I think those should be removed as well for the next release, unless I am missing some backward-compatibility use case. (And if so, that could be a separate PR IMHO.)

**Comment by bacongobbler** [comment]
600 more LOC removed this round. thanks @mboersma

**Comment by bacongobbler** [comment]
correction: 3,500 lines after removing the `mesos` and `swarm` components as well.

**Comment by bacongobbler** [comment]
pinging @helgi and @mboersma for another look-see. Also @mboersma it looks like you LGTM'd this PR twice so I'll remove one. :)

**Pull request merged**
