### PR TITLE
fix(k8s): deploy app into individual namespace

### PR DESCRIPTION
**Pull request by kmala**

### CODE REVIEW

**Comment by kmala** [comment]
fixes #4161

**Comment by aledbf** [comment]
@kmala can this be optional?

**Comment by kmala** [comment]
I am not sure. @technosophos can you please answer?

**Comment by bacongobbler** [comment]
code LGTM. The rationale behind this is that we want the tech preview to emulate Deis as it is today, which means that apps must be deployed in their own individual namespace. We can address this in the future with something like #4173, which apps can be deployed to the same team (or organization/environment, whatever makes the most sense) and they can share the same namespace.

**Comment by technosophos** [comment]
Code LGTM.

@aledbf This change is just for the preview release. We're planning on allowing explicit control of namespaces in the future. But what we're after now is what @bacongobbler said: We don't want to surprise people by having k8s behave a lot differently than the others.

**Pull request merged**
