### PR TITLE
docs(customizing_deis): clarify usage of registrationMode

### LINKED ISSUE #3653: docs(customizing_deis): clarify usage of registrationMode
Some users are confused on where to find this setting, and how to use it. It would be useful to write a small tutorial on what each setting does and how they apply to their environment.

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
Fixes #3653

### CODE REVIEW

**Comment by carmstrong** [comment]
Thanks @Joshua-Anderson! Looks like there's a formatting issue:
```
Warning, treated as error:
/var/lib/jenkins/jobs/test-ec2/workspace/src/github.com/deis/deis/docs/customizing_deis/controller_settings.rst:113: WARNING: Title underline too short.
```

**Comment by Joshua-Anderson** [comment]
@carmstrong Sorry about that, should be fixed now.

**Comment by bacongobbler** [comment]
Muchas gracias, @Joshua-Anderson. Docs LGTM!

**Comment by mboersma** [comment]
Code LGTM.

**Pull request merged**
