### PR TITLE
docs(logger): change incorrect ref to db component

### PR DESCRIPTION
**Pull request by krancour**
Change an incorrect reference to the database component in the documentation for customizing the logger component.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Code LGTM.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by carmstrong** [comment]
Thanks @krancour! This was my copypaste bad. LGTM.

**Comment by krancour** [comment]
@carmstrong I figured.  We've _all_ done that before.

**Pull request merged**
