### PR TITLE
update doc links to deis.com

### PR DESCRIPTION
**Pull request by bacongobbler**

### CODE REVIEW

**Comment by carmstrong** [comment]
LGTM.

**Comment by mboersma** [comment]
Should we be preferring the `https://` versions for links here? Otherwise LGTM.

**Comment by carmstrong** [comment]
:ship:

**Comment by mboersma** [comment]
I think this would be cleaner if squashed into two commits:
```
fix(docs): remove opdemand cloud logo
ref(docs): link to https://deis.com
```
Otherwise LGTM.

**Comment by bacongobbler** [comment]
Done. I'll wait for doc tests to pass one last time before merging.

**Comment by mboersma** [comment]
Thanks! LGTM.

**Comment by mboersma** [comment]
This did pass the relevant documentation tests, so :ship:.

**Pull request merged**
