### PR TITLE
feat(router): Add server_tokens option

### PR DESCRIPTION
**Pull request by Crispy1975**
Adding the options to turn server tokens on/off and the ability to prevent click-jacking with the `X-Frame-Options` header being present.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by krancour** [comment]
This doc should be updated as part of this PR: https://github.com/deis/deis/blob/master/docs/customizing_deis/router_settings.rst#settings-used-by-router

**Comment by Crispy1975** [comment]
Thanks, will sort that out later.

**Comment by Crispy1975** [comment]
@krancour docs updated.

**Comment by krancour** [comment]
@Crispy1975, thanks for the doc updates. This is looking good. As I consider this further, one nagging question keeps popping into my head, and that is one of whether the value of the `X-Frame-Options` header is better configured per Deis application rather than router-wide. By contrast, disabling server tokens router-wide makes sense to me because that seems like something an ops person would _want_ to enforce cluster-wide if policy dictates. But when it comes to `X-Frame-Options`, I could very easily see application-specific values being necessary. While one application might require `DENY` for security reasons, another, might (let's say a SPA) might require `SAMEORIGIN`, and yet a third (let's say an ad server) might require that this not be restricted.

Obviously, making this configurable per application is a great deal more work, but I also want to make sure we're not hastily adding a feature that impairs overall flexibility.

The possibility also exists that, since we've gotten by without any explicit support for `X-Frame-Options` up until now, that we should continue to do so. I do believe that applications that must set a particular value in that header for one reason or another can easily do so themselves, and the value should pass through in the proxied response.

@Crispy1975, any thoughts on this? I'd like to hear some fellow maintainers weigh in on this as well.

**Comment by Crispy1975** [comment]
@krancour we have actually had this question come up. We have a couple of containers that have nginx inside of them running AngularJS apps and have the `X-Frame-Options` header set inside making it in effect app specific. I actually agree that it would be nice to have app specific. How that would be achieved I am not sure. `etcd` values that correlate with app names then outputting the relevant nginx settings in the `http` blocks? Say `/deis/router/xFrameOptions/<app>` as the key?

I fear that setting this on the deis client side might be beyond me as I am not a Go coder at this time.

**Comment by bacongobbler** [comment]
> I fear that setting this on the deis client side might be beyond me

any keys added via `deis config:set` are available through etcd, as shown [here](https://github.com/deis/deis/blob/9d5feab5fbd5f3dcb518ce81ea65ca1310d74421/router/rootfs/etc/confd/templates/nginx.conf#L228). If you add a key like `/deis/config/appname/deis_x_frame_options` then users can set it via `deis config:set DEIS_X_FRAME_OPTIONS`. :)

**Comment by Crispy1975** [comment]
Thanks @bacongobbler will take a look at that...

**Comment by krancour** [comment]
Personally, I am not in favor of driving this off of environment variables. I've said this many times before in relation to other issues, but environment variables set via `deis config:set` create env vars "owned" by the application. As such, those should affect the behavior of the application itself and _not_ the platform. And in fact, there were places in v1.x where env vars were misused out of convenience and those have been (or are in the process of) being corrected now in v2.x. I cannot in good conscience endorse further abuse of that pattern with the knowledge that it's just one more thing to fix later.

If already this can be handled by the application itself, why is it necessary at all for the router to support this?  I would vote that this PR be pared down to just the parts having to do with disabling server tokens.

**Comment by Crispy1975** [comment]
@krancour I can do that no problem as that would suit our current requirements at the moment, however only two of our apps have nginx inside the containers. The rest are HapiJS/Node.js scaled up so no nginx there to be able to set the `X-Frame-Options` on. I suppose Hapi could be configured to send that header in return also...

**Comment by krancour** [comment]
@Crispy1975 I have to believe _most_ (albeit, probably not all) application frameworks can accommodate this.

**Comment by Crispy1975** [comment]
@krancour worth keeping the existing global `xFrameOptions` setting for those that do want to go universal? Perhaps adding a note to the docs?

If not will remove.

**Comment by krancour** [comment]
@Crispy1975, imo, I'd not include that option.

My reasoning is that, in general, I think the router should handle the most general concerns and the things that applications cannot or should not reasonably be expected to account for themselves-- gzip, SSL termination, anything having to do with proxying the requests / responses (e.g. determining real end user ip). The thing that all of these have in common is that if the router, as a middle-man, doesn't account for them, they don't work (or at the very least aren't easily accomplished by most application frameworks owing to an expectation that the web server handles those concerns). That's not the case with setting an app-specific response header.

If any other maintainer disagrees, I'm happy to hear another perspective on it.

**Comment by Crispy1975** [comment]
OK, happy with that. Unless there are any disagreements I will drop the `X-Frame-Options` setting and just leave the tokens stuff.

**Comment by Crispy1975** [comment]
@krancour `X-Frame-Options` stuff removed, just server tokens left.

**Comment by krancour** [comment]
@Crispy1975 can you squash the commits please and make sure the commit message adheres to the documented [commit style](https://deis.com/docs/workflow/contributing/submitting-a-pull-request/#commit-style). After that, LGTM.  Thanks!

**Comment by Crispy1975** [comment]
@krancour that should be done as request now.

**Comment by Crispy1975** [comment]
Was this ok now @krancour ?

**Comment by krancour** [comment]
@Crispy1975, sorry for the delay. LGTM.

**Comment by krancour** [comment]
And thank you for the work on this.

**Comment by Crispy1975** [comment]
:+1:

**Pull request merged**
