### PR TITLE
fix(tests): test custom buildpacks for example Procfile apps

### LINKED ISSUE #3334: setting DEIS_TEST_APP causes tests to fail
It seems if `DEIS_TEST_APP` is set to something other than the default, the integration tests will fail.
```console
$ DEIS_TEST_APP=example-ruby-sinatra ./tests/bin/test-integration.sh
...
=== configsample
BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-go#98f37cc
POWERED_BY: the Deis team
ok
git push deis master
Warning: Permanently added '[deis.local3.deisapp.com]:2222,[172.17.8.102]:2222' (RSA) to the list of known hosts.
-----> Fetching custom buildpack
-----> no app detected
 !     A .godir is required. For instructions:
 !     http://mmcgrana.github.io/2012/09/getting-started-with-go-on-heroku
To ssh://git@deis.local3.deisapp.com:2222/configsample.git
 * [new branch]      master -> master
ok
--- FAIL: TestConfig (28.52s)
	itutils.go:139: App not started (503)
		Body: (<html>
		<head><title>503 Service Temporarily Unavailable</title></head>
		<body bgcolor="white">
		<center><h1>503 Service Temporarily Unavailable</h1></center>
		<hr><center>nginx/1.6.2</center>
		</body>
		</html>
		)
FAIL
```
We should skip that section of the config test if `DEIS_TEST_APP` isn't what we expect, or else create similar tests for the other example apps.

See also #2879.

### PR DESCRIPTION
**Pull request by mboersma**
Uses a map of deis example app name to buildpack url for the custom buildpack test, and skips it if `DEIS_TEST_APP` doesn't have a map entry.

```console
$ DEIS_TEST_APP=example-ruby-sinatra ./tests/bin/test-integration.sh

>>> Preparing test environment <<<

...
config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-ruby#e99ccea --app=configsample
Creating config... done, v3

=== configsample
BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-ruby#e99ccea
POWERED_BY: the Deis team
ok
git push deis master
Warning: Permanently added '[deis.local3.deisapp.com]:2222,[172.17.8.101]:2222' (RSA) to the list of known hosts.
-----> Fetching custom buildpack        
-----> Ruby app detected        
-----> Compiling Ruby/Rack        
-----> Using Ruby version: ruby-1.9.3        
-----> Installing dependencies using 1.7.12        
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment        
...
       done, configsample:v4 deployed to Deis        
        
       http://configsample.local3.deisapp.com        
        
       To learn more, use `deis help` or visit http://deis.io        
        
To ssh://git@deis.local3.deisapp.com:2222/configsample.git
 * [new branch]      master -> master
ok
Powered by the Deis team
```

Closes #3334.

### CODE REVIEW

**Comment by bacongobbler** [comment]
we'll have to make sure to bump these as well when we bump buildpacks. How come they're all commits instead of the mixture of commits/tags in [install-buildpacks](https://github.com/deis/deis/blob/master/builder/rootfs/usr/local/src/slugbuilder/builder/install-buildpacks)?

**Comment by mboersma** [comment]
> we'll have to make sure to bump these as well when we bump buildpacks

We don't *have* to do that necessarily--these custom buildpack versions will probably work even if they become outdated.

> How come they're all commits...?

I was re-reading the Heroku docs where the only examples they give are with a SHA, then I just did them all that way before the coffee kicked in. I can change them to tags if you prefer.

**Comment by bacongobbler** [comment]
At the very least let's change the ones from commits over to the corresponding tags so at least we're testing that feature as well: https://github.com/deis/deis/pull/3042

**Comment by mboersma** [comment]
@bacongobbler done, I think brain flatulence kept me from using tags in the first place. :stuck_out_tongue_winking_eye:

**Comment by bacongobbler** [comment]
LGTM :)

**Comment by gabrtv** [comment]
Code LGTM.

**Pull request merged**
