### PR TITLE
docs(isolating-etcd): add link to user-data.example

### PR DESCRIPTION
**Pull request by laurrentt**
This confused me at first since I have been using my own cloud-config for a while.

### CODE REVIEW

**Comment by carmstrong** [comment]
Surprised this worked - our convention is usually to wrap links in backticks. This LGTM, although I'm wondering if we should change this to match our convention.

**Comment by laurrentt** [comment]
@carmstrong added the backticks to match your convention

**Comment by krancour** [comment]
@laurrentt the spot where you put the link is the second reference to cloud-config in that section.  And it's in a spot where we're advocating customizing the cloud-config for one's own purposes.

It might help avoid some confusion if the link were moved up to the _previous_ mention of cloud-config where we mention that out-of-the-box cloud-config is adequate.  This way when we say something's adequate, we link them to it, and when we say something requires customization, we let them figure that out.

Does this make sense?

**Comment by laurrentt** [comment]
@krancour I think you're right. Also, I searched a little and found Wikipedia's guidelines about [linking](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Linking#Principles): 
> "[...] as a rule of thumb editors should only link the term's **first occurrence** in the text of the article."

So, yeah, I'll move the link to the previous mention.

**Comment by carmstrong** [comment]
LGTM.

**Comment by carmstrong** [comment]
Jenkins passed docs tests.

**Comment by mboersma** [comment]
> our convention is usually to wrap links in backticks.

If there isn't a space in the link name, ReST doesn't care about backticks.

LGTM.

**Comment by carmstrong** [comment]
> If there isn't a space in the link name, ReST doesn't care about backticks.

Ahhhh that makes sense

**Pull request merged**
