### PR TITLE
fix(router): fix markdown table rendering

### PR DESCRIPTION
**Pull request by linki**
small change so the markdown table is correctly rendered by github

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Nice catch--I didn't notice this markdown table was broken. But this still doesn't render right for me--I think you have to extend the first row of hyphens to have the same length as the header row for it to render properly as a [GitHub table](https://help.github.com/articles/github-flavored-markdown/#tables):

```
|File|Purpose|
|----|-------|
```
That worked for me when previewing.

**Comment by linki** [comment]
thanks, my bad. should have checked it with github before creating the PR :hushed: should work fine now.

**Comment by mboersma** [comment]
LGTM. Thanks @linki!

**Comment by carmstrong** [comment]
LGTM.

**Pull request merged**
