### PR TITLE
V2

### PR DESCRIPTION
**Pull request by Optimus-Nishant**

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

**Comment by krancour** [comment]
Thank you for your interest in the project, but we're going to close this.  It's too big a PR to review and doesn't produce a V2 that fulfills our roadmap.  We would, however, welcome smaller, more focused PRs that advance us toward some of the platform's stated goals.  Roadmap, including links to V2 design is [here](http://docs.deis.io/en/latest/roadmap/roadmap/).

**Comment by bacongobbler** [comment]
I have a feeling that there's a bot somewhere doing this. This has been the second time in 2 weeks.

**Pull request closed without merging**
