### PR TITLE
chore(builder): bump confd to v0.8

### PR DESCRIPTION
**Pull request by bacongobbler**

### CODE REVIEW

**Comment by mboersma** [comment]
Note there is one confd error still reported in the functional test:
```
--- Run deisci/builder:jenkins-test-ec2-228 at 10.0.1.3:54348
Error response from daemon: No such container: deis-builder-jenkins-test-ec2-228
2015-03-24T17:58:06Z dde4c33efea8 confd[89]: WARNING Skipping confd config file.
2015-03-24T17:58:06Z dde4c33efea8 confd[89]: ERROR exit status 123
builder: waiting for confd to write initial templates...
2015-03-24T17:58:11Z dde4c33efea8 confd[141]: WARNING Skipping confd config file.
2015-03-24T17:58:11Z dde4c33efea8 confd[145]: WARNING Skipping confd config file.
time="2015-03-24T17:58:11Z" level="info" msg="+job serveapi(unix:///var/run/docker.sock)" 
```

**Comment by bacongobbler** [comment]
I'm seeing errors in the builder output, and this is the second time that it's failed on `limits:unset`. Taking a look into it

**Comment by mboersma** [comment]
The output remains the same as I noted above. If we can't fix the ERROR output on this round, that's ok, just wanted to point it out.

**Comment by aledbf** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
Yeah I bet that's due to https://github.com/deis/deis/blob/20f6a9484d7fea5305e16fc558bef24f51f36619/builder/image/conf.d/check-repos.toml#L11 failing out before it's templated for the first time... I'll have to look into it further but again it looks to be bug-compatible. Just confusion on how we can run scripts post-templating. I'll submit a feature request for confd

**Comment by mboersma** [comment]
Bug-compatible is fine. Code LGTM.

**Pull request merged**
