### PR TITLE
Fix URL to official docs for azure installation

### PR DESCRIPTION
**Pull request by gvilarino**
Tiny link fix, might be useful for newcomers

### CODE REVIEW

**Comment by carmstrong** [comment]
I wonder when all of our links got switched to requiring .html... this seems to be a recent change. @mboersma are you aware of any changes there?

**Comment by mboersma** [comment]
I think it must be an issue at our ReadTheDocs.org host. All the existing links work fine when you build the docs locally.

**Comment by mboersma** [comment]
This looks like it was a (hopefully transient) issue with our docs host. I rebuilt the docs in their admin panel (which isn't usually necessary--doc builds are triggered by changes at GitHub), and the link http://docs.deis.io/en/latest/installing_deis/azure/ seems to work again.

**Comment by bacongobbler** [comment]
yeah same issue reported here deis/deis.io#76

**Pull request closed without merging**
