### PR TITLE
feat(controller): allow admins to delete users

### LINKED ISSUE #3851: Admins should be able to delete users
On 1.7.1, it looks like you have to know the password of the user when using `deis auth:cancel`.

As an admin, you should be able to delete users even without knowing their passwords.

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
Fixes #3851

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
I think this should probably have some integration tests. I'll add some soon (probably tomorrow).

**Comment by Joshua-Anderson** [comment]
Rebased

**Comment by krancour** [comment]
Code LGTM.

**Comment by carmstrong** [comment]
> I think this should probably have some integration tests. I'll add some soon (probably tomorrow).

Are these tests in now, or are there more that we're waiting on?

**Comment by Joshua-Anderson** [comment]
> Are these tests in now, or are there more that we're waiting on?

I forgot about those, I'll add some in on monday.

**Comment by Joshua-Anderson** [comment]
Rebased and added integration tests.

**Comment by krancour** [comment]
Code LGTM

**Comment by bacongobbler** [comment]
code LGTM

**Pull request merged**
