### PR TITLE
chore(Godeps): bump libcontainer

### PR DESCRIPTION
**Pull request by ngpestelos**

### CODE REVIEW

**Comment by bacongobbler** [comment]
other than for the sake of bumping versions, is there a specific reason you bumped libcontainer to that commit?

**Comment by ngpestelos** [comment]
No other reason. I noticed the difference when I ran `godep save` in my fork.

**Comment by bacongobbler** [comment]
We don't actually use these libraries. `fleet` does, however, which is something that we use in `deisctl`. Let's leave bumping libcontainer up to them. Why fix what ain't broken? :D

**Comment by ngpestelos** [comment]
OK, thank you.

**Pull request closed without merging**
