### PR TITLE
feat(slugbuilder): update nodejs buildpack to v64 (yoga release)

### PR DESCRIPTION
**Pull request by aledbf**
This release provides 2 very importan updates: 

1. the option to specify the [npm version](https://github.com/heroku/heroku-buildpack-nodejs/tree/yoga#specify-an-npm-version) to use
2. support for [scoped packages](https://docs.npmjs.com/misc/scope) (using npm 2.1.x)
3. correct support for chaining buildpacks

### CODE REVIEW

**Comment by bacongobbler** [comment]
code LGTM!

**Comment by mboersma** [comment]
Big update for the NodeJS buildpack. Code LGTM.

**Comment by mboersma** [comment]
Oops @aledbf I noticed a typo in the commit message, should be "buildpack". That one was easy to miss--I must have read it 3 times. :) Could you `git commit --amend`? Thanks again!

**Comment by aledbf** [comment]
@mboersma done

**Comment by carmstrong** [comment]
Thanks @aledbf!

**Pull request merged**
