### PR TITLE
feat(makefile): check that generated go binaries are statically linked

### PR DESCRIPTION
**Pull request by aledbf**
Check to avoid problems like https://github.com/deis/deis/pull/3133

### CODE REVIEW

**Comment by bacongobbler** [comment]
I think this should be part of some form of validation check rather than `make build`

**Comment by bacongobbler** [comment]
otherwise LGTM

**Comment by carmstrong** [comment]
> I think this should be part of some form of validation check rather than make build

:+1: That would allow people to bypass it as well, by skipping the makefile target for `check-static`.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by mboersma** [comment]
Is the suggestion that there be separate, optional `make check-static` targets? I think it's ok to enforce static go binary checking as part of `make build`.

**Comment by aledbf** [comment]
What I need to do: keep this or add a `check-static` target?

**Comment by mboersma** [comment]
This LGTM as-is. ping @bacongobbler @carmstrong--what changes do you want to see in this PR?

**Comment by bacongobbler** [comment]
I think it's fine. lgtm

**Pull request merged**
