### PR TITLE
[WIP] chore(logspout): upgrade logspout

### LINKED ISSUE #4292: Proposal: Upgrade logspout
Logspout has undergone two major refactors in the time since we forked and enhanced it (mainly for the sake of discovering `deis-logger` host and port from etcd and to hijack the message format).

The master branch of logspout (which is trending toward a v3) is significantly more modular than what we've been using.  The possibility exists that we can bend logspout to our will by creating a module for it, rather than by forking it and hacking on it.

The major motivation for this would be the ability to reap the benefits of upstream bug fixes.

Do other maintainers want to weigh in?

### PR DESCRIPTION
**Pull request by krancour**
Fixes #4292 #4293 

This WIP PR uses upstream logspout v3 (without forking it!) along with a deis adapter module.

When merged, this addresses many recent, notable log issues related to discovery, deadlock, Kubernetes, and more.  Some (not all) of these issues have _also_ been fixed in our ancient fork of logspout, but the point is I have attempted to keep this PR in feature / fix parity with what currently exists.

Why is this WIP?

* Release of logspout v3 is pending
* The plugin still requires unit and functional tests

~~Ideally, also, it would be good to find a way to keep the adapter code right here in the deis/deis project.  That, however, would require that we deviate from upstream logspout's own documentation on how to produce custom builds that include our own adapter.  This may be worthwhile to figure out since it will mean one less repository to manage, but my early attempts at doing this have resulted in built images that are (somehow) much, much larger than what their documented custom build process produces.  I do intend to solve that.~~

### CODE REVIEW

**Comment by krancour** [comment]
I've discovered how to produce adequately compact images from a Dockerfile that combines stock logspout with the custom code from _this_ repo.  This eliminates the need to maintain the separate (and very short-lived) deis/logspout-v3-deis repo.  The downside to this build, however, is that it's slow, so I also provide a second, development-optimized build that produces a less compact image, but does so much more quickly.  This seems reasonable to me.

A few unit and functional test are all that stand between this and a review.

**Comment by krancour** [comment]
Although unit and functional tests are still required, I'm encouraged that this passed integration tests.  :)

**Comment by mboersma** [comment]
This needs a rebase now. See also #2158. :pray:

**Comment by kalbasit** [comment]
Accidentally closed the PR.

**Comment by krancour** [comment]
Unless other maintainers disagree, I don't see this getting done.  Logspout v3 is a blocker for this and has been a long time coming.  Meanwhile, Deis v2 won't use logspout at all.  I can't see this as being something that makes it into a v1.x LTS, not can I see it as being something that makes the leap to V2.

**Pull request closed without merging**
