### PR TITLE
[WIP] chore(*): support etcd2

### PR DESCRIPTION
**Pull request by carmstrong**
**Not to be merged as-is!**

This commit updates provision scripts, documentation, and cloud-config
settings to support etcd 2, a significant rewrite which has shown
to be more stable and resilient than etcd 0.x.

This commit will be amended once a CoreOS release with etcd 2 hits
the stable channel, and sufficient testing has been done to have
confidence in etcd 2 for supporting Deis.

### CODE REVIEW

**Comment by carmstrong** [comment]
closes #3564

**Comment by carmstrong** [comment]
ping @iancoffey -- we should investigate and confirm the cleanup script still works for etcd2. The API may have changed.

**Comment by iancoffey** [comment]
@carmstrong I'll check it out!

**Comment by mboersma** [comment]
This needs rebasing, BTW.

**Comment by bacongobbler** [comment]
coudl we list this as a WIP while etcd2 is still out of stable?

**Comment by carmstrong** [comment]
Jenkins just passed this! https://github.com/deis/deis/pull/3748

**Comment by aledbf** [comment]
@carmstrong this could provide an upgrade path from 0.4.x https://github.com/coreos/etcd/tree/master/tools/etcd-migrate

**Comment by mboersma** [comment]
This will need update and migration instructions, and we'll need to think about how to support existing clusters that will continue to run on v0.4.x.

**Comment by mboersma** [comment]
> This commit will be amended once a CoreOS release with etcd 2 hits
the stable channel

Also, that time has come.

**Comment by carmstrong** [comment]
Closing, as this will need to be rebased once we merge #3837. The changes for etcd2 are sound and this should be used as a basis for #3564.

**Pull request closed without merging**
