### PR TITLE
fix(client-go): error deserializing json

### LINKED ISSUE #4423: bug(client-go): error deserializing json
Running `deis config:list` in one application I see this error:
```
panic: interface conversion: interface is float64, not string

goroutine 1 [running]:
github.com/deis/deis/client/cmd.ConfigList(0x8206ee123, 0x12, 0x8206f1c00, 0x0, 0x0)
	/Users/matt/Projects/src/github.com/deis/deis/client/cmd/config.go:50 +0x7d7
github.com/deis/deis/client/parser.configList(0x8206e63b0, 0x1, 0x1, 0x0, 0x0)
	/Users/matt/Projects/src/github.com/deis/deis/client/parser/config.go:67 +0x27a
github.com/deis/deis/client/parser.Config(0x8206e63b0, 0x1, 0x1, 0x0, 0x0)
	/Users/matt/Projects/src/github.com/deis/deis/client/parser/config.go:24 +0x17d
main.Command(0x8206e63b0, 0x1, 0x1, 0x186840)
	/Users/matt/Projects/src/github.com/deis/deis/client/deis.go:89 +0x129b
main.main()
	/Users/matt/Projects/src/github.com/deis/deis/client/deis.go:18 +0x60
```

This application contains one particular configured value: `REDIS_PORT=6381`

### PR DESCRIPTION
**Pull request by aledbf**
closes #4423

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
I'm :+1: on this, but it's odd that you're seeing this error.

[This](https://github.com/deis/deis/blob/master/controller/api/serializers.py#L173) shows that all variables should be converted to strings server side, so it shouldn't be possible to have it return a integer. Was this variable set on a old cluster that didn't have this conversion code?

**Comment by aledbf** [comment]
@Joshua-Anderson yes (it a cluster running since 0.8)

**Comment by Joshua-Anderson** [comment]
@aledbf I think this same bug also affects `tags` and `limits`.

**Comment by aledbf** [comment]
@Joshua-Anderson done

**Comment by bacongobbler** [comment]
code LGTM

**Comment by mboersma** [comment]
@aledbf I can't reproduce the issue this is supposed to fix. I'm using v1.10. I did `deis config:set REDIS_PORT=6381` with both the old Python and new Go clients but couldn't make `deis config:list` produce this error. Any ideas?

**Comment by mboersma** [comment]
LGTM. I tested this with the 1.10 `deis` CLI against a v1.8 Deis cluster after doing `config:set` and was able to reproduce the issue, then verify that this fixes it.

**Pull request merged**
