### PR TITLE
Increase timeout for fetching buildpacks

### PR DESCRIPTION
**Pull request by jacobo**
180 seconds

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

**Comment by jacobo** [comment]
update commit message to match guidelines (I think)

**Comment by jacobo** [comment]
not entirely sure if this is actually working yet (maybe my wifi got better?)

**Comment by jacobo** [comment]
Proof that it works:

    rackapp jburkhart$ git push deis master
    Counting objects: 111, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (68/68), done.
    Writing objects: 100% (111/111), 11.33 KiB | 0 bytes/s, done.
    Total 111 (delta 49), reused 83 (delta 36)
    -----> Intentionally tiny timeout fails, right?
    -----> Ruby app detected
    -----> Compiling Ruby/Rack
           !
           !     An error occurred while installing Ruby ruby-2.0.3
           !     For supported Ruby versions see https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
           !     Note: Only the most recent version of Ruby 2.1 is supported on Cedar-14
           !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 1 --max-time 3 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.0.3.tgz -s -o - | tar zxf - ' failed unexpectedly:
           !
           !     gzip: stdin: unexpected end of file
           !     tar: Child returned status 1
           !     tar: Error is not recoverable: exiting now
           !
    To ssh://git@deis.local.deisapp.com:2222/dainty-keepsake.git
     * [new branch]      master -> master

**Comment by carmstrong** [comment]
Jenkins, add to whitelist.

**Pull request merged**
