### PR TITLE
fix(controller) : remove domain

### PR DESCRIPTION
**Pull request by babarinde**
deis domains:remove was removing all domains instead of single one

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by babarinde** [comment]
I must add that i dont write python. this was just a little effort to fix a problem and it should close
https://github.com/deis/deis/issues/3475

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by carmstrong** [comment]
Thanks for fixing this, @babarinde. This looks like a bad oversight :(

**Comment by carmstrong** [comment]
I think this doesn't actually close #3475, as this bug removes all **certs**, not **domains**.

**Comment by mboersma** [comment]
Code LGTM. Thanks for finding this.

**Comment by carmstrong** [comment]
Code LGTM. Thanks @babarinde!

**Comment by bacongobbler** [comment]
this doesn't fix the root problem, sadly. Nice change though:

```
diff --git a/controller/api/tests/test_domain.py b/controller/api/tests/test_domain.py
index 3d9ba5f..a42c320 100644
--- a/controller/api/tests/test_domain.py
+++ b/controller/api/tests/test_domain.py
@@ -101,6 +101,11 @@ class DomainTest(TestCase):
         with self.assertRaises(Domain.DoesNotExist):
             Domain.objects.get(domain=test_domains[0])

+    def test_delete_domain_does_not_remove_others(self):
+        """https://github.com/deis/deis/issues/3475"""
+        self.test_delete_domain_does_not_remove_latest()
+        self.assertEqual(Domain.objects.all().count(), 1)
+
     def test_manage_domain_invalid_app(self):
         url = '/v1/apps/{app_id}/domains'.format(app_id="this-app-does-not-exist")
         body = {'domain': 'test-domain.example.com'}
```
```
><> venv/bin/python manage.py test api.DomainTest.test_delete_domain_does_not_remove_others
WARNING Cannot synchronize with etcd cluster
Creating test database for alias 'default'...
F
======================================================================
FAIL: test_delete_domain_does_not_remove_others (api.tests.test_domain.DomainTest)
https://github.com/deis/deis/issues/3475
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bacongobbler/go/src/github.com/deis/deis/controller/api/tests/test_domain.py", line 107, in test_delete_domain_does_not_remove_others
    self.assertEqual(Domain.objects.all().count(), 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 1 test in 0.113s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

**Comment by bacongobbler** [comment]
seems to be that `.get_object()` is returning the entire queryset instead of the domain we want to target

**Comment by bacongobbler** [comment]
seems to be that `.get_object()` is returning the entire queryset instead of the domain we want to target

**Pull request merged**
