### PR TITLE
feat(deis/config): remove "===" when listing configs with --oneline

### PR DESCRIPTION
**Pull request by mhahn**
This makes it easier to transfer configs from one app to another.
See: #3016 for reference.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by carmstrong** [comment]
Code LGTM!

**Comment by bacongobbler** [comment]
LGTM as well :)

**Comment by bacongobbler** [comment]
Jenkins, add to whitelist.

**Comment by mboersma** [comment]
Code LGTM. Thanks for doing this @mhahn.

**Comment by mhahn** [comment]
haha simplest change ever. but i wanted to start helping you guys out because deis is a life saver :)

**Comment by carmstrong** [comment]
> but i wanted to start helping you guys out because deis is a life saver :)

And we certainly appreciate it :) Thanks again!

**Pull request merged**
