### PR TITLE
chore(router): update nginx to 1.9.5

### PR DESCRIPTION
**Pull request by mboersma**
See http://nginx.org/en/CHANGES

spdy is gone is favor of http2, so this may be a breaking change. (Team nginx semver foul: fifteen yards and loss of possession.)

### CODE REVIEW

**Comment by helgi** [comment]
https://www.nginx.com/blog/nginx-1-9-5/

> Prerequisites Before upgrading, please remove the spdy parameter from all listen directives in  your configuration. This will ensure the upgrade goes smoothly. 

Do all routers auto get bumped to 1.9.5? Is it via new image? Is there any possibility of the new configuration to be applied on top of a setup that has a 1.9.4 still running?

**Comment by carmstrong** [comment]
> Is there any possibility of the new configuration to be applied on top of a setup that has a 1.9.4 still running?

Great point to double-check, but the template is tied to the version of the component. There shouldn't be the possibility of running a template and nginx out-of-sync -- the entire component is upgraded on a new release.

**Comment by helgi** [comment]
Then it should be safe enough - Would recommend keeping an eye on that in the testing. Would be a rather big blow up if it somehow got itself on top of 1.9.4 and older :)

**Comment by carmstrong** [comment]
> Would be a rather big blow up if it somehow got itself on top of 1.9.4 and older :)

Indeed :)

**Comment by mboersma** [comment]
I'm not saying we need to upgrade (yet)--I looked at the changes and thought about it, but if this isn't strictly backward-compatible for our documented installs then it can be targeted for v2. Deis is pretty intimate with nginx, and this is where nginx is going, plus I know we've flirted with HTTP/2 for solving #117 so this might be a forward-looking change.

**Comment by carmstrong** [comment]
> but if this isn't strictly backward-compatible for our documented installs

I think it should be. @aledbf, what are your thoughts on this?

**Comment by aledbf** [comment]
From the [docs](http://nginx.org/en/docs/http/ngx_http_v2_module.html#example) 1.9.5 requires OpenSSL >= 1.0.2 (where "Application-Layer Protocol Negotiation" is available)
Using alpine 3.1 uses 1.0.1

```
old-mbp:~ aledbf$ docker run -it alpine:3.1 /bin/sh
3.1: Pulling from library/alpine

8dd8107abd2e: Pull complete
Digest: sha256:22b8b96ceccf4d484e4ca62363abb527fc5c2fe01a4097642395c4d830c3471f
Status: Downloaded newer image for alpine:3.1
/ # apk -U add openssl
fetch http://dl-4.alpinelinux.org/alpine/v3.1/main/x86_64/APKINDEX.tar.gz
(1/1) Installing openssl (1.0.1p-r0)
Executing busybox-1.22.1-r15.trigger
OK: 6 MiB in 16 packages
/ #
```

I already tried 1.9.5 but I see different behavior depending on the browser. For now I think 1.9.4 is a safer option.

**Comment by mboersma** [comment]
> For now I think 1.9.4 is a safer option.

Totally agree. We can probably fix that with `alpine:3.2`, but let's not rush into it for this release.

**Comment by mboersma** [comment]
We should look at updating to alpine:3.2 across the board.

**Comment by mboersma** [comment]
> I already tried 1.9.5 but I see different behavior depending on the browser.

@aledbf I updated everything to `alpine:3.2` in master, so OpenSSL is 1.0.2d in deis-router. Does that fix the behavior you noticed, or should we play it safe and skip nginx 1.9.5?

**Comment by aledbf** [comment]
> or should we play it safe and skip nginx 1.9.5?

I think would be a good idea to wait for 1.9.6 before switching to http2.

**Pull request closed without merging**
