### PR TITLE
bug(contrib): check for cloudfront errors on stack creation

### LINKED ISSUE #3481: EC2 provisioning script failed with no error info
During the EY Deis install-a-thon, an EC2 provisioning failed after "Creating instances" with a return code of 1 but no printed error. We think this was due to specifying availability zones that weren't accessible, or possibly due to using an AWS account that didn't have CloudFormation access.

### PR DESCRIPTION
**Pull request by econnell**
add checks to provision script to make sure the stack is either in the creating or created state.  otherwise, error out and show all resources that failed

Closes #3481

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by mboersma** [comment]
Could you add the `CREATE_IN_PROGRESS` text to the second status polling line at https://github.com/deis/deis/blob/master/docs/installing_deis/aws.rst#run-the-provision-script? We have an example of EC2 provisioning in the docs, and that would keep it up-to-date with this change.

...which is awesome BTW, code LGTM otherwise.

**Comment by mboersma** [comment]
I'm going to merge this and make the trivial doc change separately. Thanks again @econnell!

**Pull request merged**
