### PR TITLE
ref(controller/tests): import regex to be tested, don't copy it

### PR DESCRIPTION
**Pull request by mboersma**
When merging #3484 I missed that the regular expression to be tested was duplicated.

### CODE REVIEW

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
ooh yes, good catch. LGTM

**Comment by bacongobbler** [comment]
@mboersma looks like a `flake8` issue with the controller needs to be fixed up

**Comment by mboersma** [comment]
> looks like a flake8 issue 

Fixed.

**Pull request merged**
