### PR TITLE
already don't -> don't already, ot -> to

### PR DESCRIPTION
**Pull request by mikepack**
Fixes a couple minor typos in the Azure docs.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Nice catch, thanks for fixing those up. Code LGTM.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by bacongobbler** [comment]
Would you mind amending your commit such that it follows the style guide as our bot pointed out? That way we can parse the commit message when generating the changelog. Thanks! :)

**Comment by mikepack** [comment]
No problem. How does that commit look?

**Comment by bacongobbler** [comment]
Perfect :)

**Comment by mboersma** [comment]
LGTM.

**Comment by mboersma** [comment]
This passed the relevant doc tests, so I'm merging it.

**Pull request merged**
