### PR TITLE
V2

### PR DESCRIPTION
**Pull request by mstulajt**
Looks good

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

**Comment by mboersma** [comment]
I share your enthusiasm, but v2 of Deis is still a work in progress.

**Comment by nathansamson** [comment]
@mboersma unrleated to this issue, but is there some general discussion / design documents for V2?

From the issues I see a move to kubernetes only (instead of pluggable schedulers). but except for that I missed the discussion around this.

**Comment by mboersma** [comment]
@nathansamson the v2 discussion is currently codified in a bunch of issues on that milestone: https://github.com/deis/deis/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0

> From the issues I see a move to kubernetes only (instead of pluggable schedulers)

Yes, that's the main idea. We have also discussed this at the open planning meetings. @technosophos is leading the effort, so I'll let him fill in the gaps WRT discussion & design docs.

**Pull request closed without merging**
