### PR TITLE
chore(Makefile): bump dev-registry to use 0.9.1

### PR DESCRIPTION
**Pull request by ngpestelos**

### CODE REVIEW

**Comment by bacongobbler** [comment]
@mboersma wasn't there an issue with 0.9.1 during your testing?

**Comment by mboersma** [comment]
@ngpestelos I left this out of the other PR because it crashed on me a couple times, so I left dev-registry at 0.9.0. But I didn't figure out what exactly the problem was. I'll test again with this PR and see if I can reproduce the issue, or if this is good to go. Thanks!

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by mboersma** [comment]
I haven't seen any issues recently using registry:0.9.1. Code LGTM.

**Pull request merged**
