### PR TITLE
docs(reference): fix config list and set examples

### PR DESCRIPTION
**Pull request by Joshua-Anderson**

### CODE REVIEW

**Comment by carmstrong** [comment]
LGTM.

**Comment by mboersma** [comment]
Code LGTM.

**Comment by deis-admin** [comment]
Typo in the commit subject: should be "reference".

**Comment by carmstrong** [comment]
> Typo in the commit subject: should be "reference".

IT'S BECOME SENTIENT!

**Comment by Joshua-Anderson** [comment]
Done! We need to keep an eye on that deis-admin bot though. First GitHub, next the world. :rocket: The

**Comment by mboersma** [comment]
Could you rebase this off current Deis master? Sorry for the hassle. Unfortunately nothing's going to pass CI now unless it includes #3968.

**Comment by Joshua-Anderson** [comment]
@mboersma Rebased!

**Pull request merged**
