### PR TITLE
chore(controller): bump confd to v0.8

### PR DESCRIPTION
**Pull request by bacongobbler**

### CODE REVIEW

**Comment by mboersma** [comment]
This new warning showed up in the functional test:
```
deis-controller running...
2015-03-23T19:40:18Z 40cafdfbebf1 confd[84]: WARNING Skipping confd config file.
[2015-03-23 19:40:18 +0000] [86] [INFO] Starting gunicorn 19.3.0
```

**Comment by bacongobbler** [comment]
yeah that's due to confd expecting a config file yet not respecting it in recent versions, hence the reliance on flags instead. I'm fixing that up.

**Comment by bacongobbler** [comment]
@mboersma kelseyhightower/confd#235

**Comment by bacongobbler** [comment]
FYI because the check script is gone with this PR, we should no longer be seeing "config check failed: exit status 1" any more. We should see more verbose information... Hopefully.

**Comment by bacongobbler** [comment]
I also filed kelseyhightower/confd#236 to track the `--config-file` issue/workaround.

**Comment by mboersma** [comment]
This does make the templates a bit uglier, but I gather there's no alternative if we want to catch up with newer `confd`, which we do. Code LGTM.

**Comment by bacongobbler** [comment]
Also note kelseyhightower/memkv#4 should help make the "get value or default" calls here a lot cleaner.

**Comment by aledbf** [comment]
Code LGTM.

**Pull request merged**
