### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lorieri**
New Relic unit for CoreOS

### CODE REVIEW

**Comment by mboersma** [comment]
Excellent, the more the merrier. @lorieri could you `git commit --amend` the [subject](http://docs.deis.io/en/latest/contributing/standards/#commit-style) to something like `docs(contrib/README): add link to New Relic unit for CoreOS`? Otherwise it won't show up correctly in the [CHANGELOG.md](https://github.com/deis/deis/blob/master/CHANGELOG.md).

**Comment by lorieri** [comment]
sure, I edited it using the browser :smile:

**Comment by carmstrong** [comment]
Thanks @lorieri! LGTM.

**Comment by mboersma** [comment]
LGTM.

**Comment by wenzowski** [comment]
if the answer to lorieri/coreos-newrelic#1 is what I think it is, this solves an important problem and may make new relic monitoring actually usable

**Pull request merged**
