### PR TITLE
docs(reference): Fix response of /v1/apps/<app id>/run endpoint

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
Run returns a dynamic array :anguished:, not a json object as documented.

### CODE REVIEW

**Comment by bacongobbler** [comment]
LGTM, though we should fix this up and cut a v2 for the API (not the platform)

**Comment by carmstrong** [comment]
> though we should fix this up and cut a v2 for the API in the future (not the platform)

Let's file a separate issue for that, @Joshua-Anderson.

Code LGTM for this.

**Comment by Joshua-Anderson** [comment]
@carmstrong #3988

**Comment by carmstrong** [comment]
Passed docs. Merging.

**Pull request merged**
