### PR TITLE
docs(managing_deis): add upgrade Deis clients for in-place upgrade

### PR DESCRIPTION
**Pull request by ecylmz**

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by bacongobbler** [comment]
note that there is duplicate information surrounding this in the docs just slightly above this note:

> Always use a version of `deisctl` that matches the Deis release. Verify this with `deisctl --version`.

**Comment by mboersma** [comment]
We are already specific in this documentation about the need to use a the right `deisctl` version, but we don't mention upgrading `deis` CLI. Maybe if this change said instead:

> As well as upgrading `deisctl` to match the new version of Deis, make sure to upgrade the `deis` client.

and link it to the "Install the Client" section?

**Comment by bacongobbler** [comment]
:+1:

**Comment by mboersma** [comment]
@ecylmz, could you change this PR to something like this?
```
Upgrade Deis clients
^^^^^^^^^^^^^^^^^^^^
As well as upgrading ``deisctl``, make sure to upgrade the :ref:`deis client <install-client>` to match the new version of Deis.
```

**Comment by ecylmz** [comment]
@mboersma, I created new pull request: #3491

**Pull request closed without merging**
