### PR TITLE
feat(*): use confd --watch

### LINKED ISSUE #2160: Use confd watch
Currently it takes up to 5 seconds until a new app is added to nginx (5 seconds polling). Watch support was recently added to confd https://github.com/kelseyhightower/confd/pull/150 so it's time to add it to deis.

Might fix: https://github.com/deis/deis/issues/1927

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #2160

### CODE REVIEW

**Comment by mboersma** [comment]
Code LGTM. See kelseyhightower/confd#150.

**Comment by aledbf** [comment]
Code LGTM

**Comment by johanneswuerbach** [comment]
Yeah, :wave: 5 second delays :boom:

**Comment by johanneswuerbach** [comment]
Yeah, good bye 5 second delays :boom:

**Pull request merged**
