### PR TITLE
Update available datacenters for Digital Ocean

### PR DESCRIPTION
**Pull request by ghostbar**
ams2 and sfo1 now do have metadata and private-networking support.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Right you are--thanks for noticing this. I double-checked in the DO "create droplet" screen, and nyc2 looks like the only region available without metadata (user-data) and private networking support. (nyc1 and ams1 are disabled for creating new droplets currently, but I assume they are still limited.)

Code LGTM.

**Comment by ghostbar** [comment]
Indeed @mboersma, that's what `docl regions --metadata --private-networking` shows and nyc1 nor ams1 are shown.

**Comment by carmstrong** [comment]
Code LGTM after the commit is amended.

**Comment by mboersma** [comment]
@ghostbar we want this in the next Deis release, but we are strict about commit style. I'm going to amend the subject of your commit and open another PR so we can get this fixed ASAP since we are trying to get to a code freeze. I hope that's ok with you--thanks again!

**Pull request closed without merging**
