### PR TITLE
chore(router): update Nginx to 1.7.5 mainline

### PR DESCRIPTION
**Pull request by wenzowski**
yaoweibin/nginx_tcp_proxy_module appears compatible with Nginx 1.7.3
Nginx 1.7.4 & 1.7.5 are security fixes, so use Nginx 1.7.5

wanted for #3088

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by wenzowski** [comment]
Perhaps someone can confirm if this breaks Naxsi? I don't use it myself. For reasons I will probably never understand, all [BrowserChannel] POST requests fail with 400 errors when Naxsi is enabled, and the failures aren't new behaviour as of this commit.

[BrowserChannel]: https://code.google.com/p/libevent-browserchannel-server/wiki/BrowserChannelProtocol

**Comment by wenzowski** [comment]
from what I understand, build [2113] integration test appears to fail [here](https://github.com/dialoghq/deis/blob/17c7375582d8760ecd7cfc8b3fc7b9ae8bd477fd/tests/bin/test-integration.sh#L58)

```
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: ssh: rejected: connect failed (Connection refused)
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 800ms
Error: timeout reached
```

Is the router responsible for proxying etcd?

[2113]: https://ci.deis.io/job/test-integration/2113/consoleFull#-1099781386a722eca2-3efc-471f-b91f-cda7c6bdf4a4

**Comment by wenzowski** [comment]
Hmm, looks green now...
https://ci.deis.io/job/test-integration/2118/console

**Comment by wenzowski** [comment]
I'm currently running this in staging without issue

**Comment by carmstrong** [comment]
I'm generally hesitant to bump nginx from the 1.6.x tree, as that is certifiably stable. Is there a reason we're not bumping to the latest in the 1.7.x tree?

**Comment by aledbf** [comment]
@wenzowski https://github.com/irr/nginx_tcp_proxy_module works with 1.7.9

**Comment by aledbf** [comment]
@carmstrong I'm using 1.7.9 since the last month without any issue.

About how ready is the 1.7.x for production, the commercial version of nginx uses 1.7.7 currently (nginx R5). I have 3 servers with the this version and I don't perceive any difference between the open source and the commercial version (besides the additional functionality provided in the paid version)

**Comment by carmstrong** [comment]
@wenzowski If we're bumping nginx, we may as well bump it to the latest 1.7.x release.

**Comment by carmstrong** [comment]
Closing in favor of #3088.

**Pull request closed without merging**
