### PR TITLE
docs(roadmap): complete production hardening

### PR DESCRIPTION
**Pull request by carmstrong**
This was completed for last release, but I forgot to remove it.

### CODE REVIEW

**Comment by mboersma** [comment]
LGTM.

**Comment by bacongobbler** [comment]
lgtm

**Comment by krancour** [comment]
@carmstrong I think one of those completed for 1.9 and the other for 1.10.  Should the whole section really be removed?

**Comment by carmstrong** [comment]
> I think one of those completed for 1.9 and the other for 1.10.

The dates made it look like both had landed for 1.9, but if not, we shouldn't remove it until after tomorrow. Which is which?

**Comment by krancour** [comment]
Isolating etcd landed in 1.9-- it was really just a combination of doc and etcd upgrade that got us there.  Isolating the control plane was more involved and landed in 1.10.0.

**Comment by carmstrong** [comment]
Closing - will address in a post-release planning PR.

**Pull request closed without merging**
