### PR TITLE
feat(router): avoid regex-based taxing rewrites

### PR DESCRIPTION
**Pull request by wenzowski**
for more see http://wiki.nginx.org/Pitfalls#Taxing_Rewrites

### CODE REVIEW

**Comment by mboersma** [comment]
That should avoid doing regex matching or capturing at all in those cases, as the linked documentation suggests. Nice optimization. Code LGTM.

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by wenzowski** [comment]
rebased.

**Comment by mboersma** [comment]
Needs re-rebasing now. :sweat_smile:

**Comment by wenzowski** [comment]
rebased

**Comment by wenzowski** [comment]
rebased

**Comment by wenzowski** [comment]
[passing](https://ci.deis.io/job/test-vagrant/2530/console) :beer:

**Pull request merged**
