### PR TITLE
feat(client-go): add tags endpoint

### PR DESCRIPTION
**Pull request by Joshua-Anderson**

### CODE REVIEW

**Comment by mboersma** [comment]
This code looks good, but there aren't any tests...

**Comment by Joshua-Anderson** [comment]
@mboersma The `tags` code primarily uses the `config` models package which is heavily tested. This code is responsible for the command line parsing and STDOUT. The `cmd` and `parser` packages, the packages that this PR touched, are very lightly tested as I figured these packages were covered by the integration tests as they only dealt with command line parsing and output.

**Comment by mboersma** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
code LGTM

**Pull request merged**
