### PR TITLE
fix(docs): refer to correct "deis perms:create" command

### PR DESCRIPTION
**Pull request by mboersma**
```console
$ deis perms:add -h
Found no matching command, try `deis help`
Usage: deis <command> [<args>...]
```

### CODE REVIEW

**Comment by bacongobbler** [comment]
saw the conversation on IRC. Nice catch :)

docs LGTM!

**Comment by carmstrong** [comment]
:ship:

**Comment by mboersma** [comment]
This is really a typo fix, and I know it passes documentation tests, so I'm merging it since Jenkins is slow and irritable today.

**Comment by carmstrong** [comment]
> This is really a typo fix, and I know it passes documentation tests, so I'm merging it since Jenkins is slow and irritable today.

:thumbsup:

**Pull request merged**
