### PR TITLE
fix(client): catch and propagate client errors

### LINKED ISSUE #4690: Panic on `deis create` following tutorial
Hi all,

I've paniced the deis client while following the tutorial with vagrant:

```
nick@nite:~/workspace/example-ruby-sinatra$ deis apps:create
Creating Application... panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x548d9d]

goroutine 1 [running]:
github.com/deis/deis/client/controller/models/apps.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/controller/models/apps/apps.go:43 +0x39d
github.com/deis/deis/client/cmd.AppCreate(0x0, 0x0, 0x0, 0x0, 0xc820016efb, 0x4, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/cmd/apps.go:26 +0x181
github.com/deis/deis/client/parser.appCreate(0xc82000a3f0, 0x1, 0x1, 0x0, 0x0)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/parser/apps.go:92 +0x42c
github.com/deis/deis/client/parser.Apps(0xc82000a3f0, 0x1, 0x1, 0x0, 0x0)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/parser/apps.go:30 +0x530
main.Command(0xc82000a3f0, 0x1, 0x1, 0x586db0)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/deis.go:87 +0xdc6
main.main()
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/deis.go:18 +0x60

goroutine 6 [runnable]:
github.com/deis/deis/client/cmd.progress.func1(0xc820017000, 0x4, 0x4, 0xc82001ab40, 0xc820168970, 0x3, 0xc82001aae0)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/cmd/utils.go:20
created by github.com/deis/deis/client/cmd.progress
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/cmd/utils.go:34 +0x166
```

I didn't see an existing issue.

### PR DESCRIPTION
**Pull request by ngauthier**
fixes #4690

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

**Comment by ngauthier** [comment]
oops, my commit message is not following the format

**Comment by ngauthier** [comment]
commit message updated and passes commit hook

**Comment by carmstrong** [comment]
Jenkins, add to whitelist.

**Comment by mboersma** [comment]
Not returning the `err` is an obvious oversight--thanks for fixing this @ngauthier! What was the underlying error that should have been returned in #4690?

**Comment by ngauthier** [comment]
Underlying error was I was not logged in. Needed to run Deis login. Not
sure if it was missing in the vagrant tutorial or if I skipped it. :-)

**Pull request merged**
