### PR TITLE
feat(router): don't copy Godeps, godeps can find it automatically.

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
godeps walks up the directory tree to find a Godeps folder.

### CODE REVIEW

**Comment by bacongobbler** [comment]
yep, this was something long forgotten. Good catch. You'll probably also want to remove the call to `rm -rf Godeps` in `make clean` as well. Thanks!

**Comment by Joshua-Anderson** [comment]
@bacongobbler Done!

**Comment by bacongobbler** [comment]
LGTM

**Comment by mboersma** [comment]
Thanks for finding and fixing this! Code LGTM.

**Pull request merged**
