### PR TITLE
fix(contrib/azure): update template to current API and images

### PR DESCRIPTION
**Pull request by jordanyaker**
The Microsoft API's have changed since this template was published.  These updates ensure the functionality of the template.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
@jordanyaker thanks a ton for keeping Deis LTS current with Azure Cloud!

Could you amend the commit subject to match our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style)? Otherwise it won't get included in the CHANGELOG.md. Something like:
`fix(contrib/azure): update template to current API and images`

**Comment by jordanyaker** [comment]
@mboersma done!

**Comment by bacongobbler** [comment]
@jordanyaker would you also mind amending the commit? It's the commit message that's important rather than the PR title :)

**Comment by jordanyaker** [comment]
@bacongobbler sure.  I will knock that out this evening.

**Comment by jordanyaker** [comment]
@bacongobbler my apologies for this taking so long.  I spent the last week trying to figure out various problems with getting Kubernetes to install on Azure and this kept slipping to the bottom of the stack.

**Pull request merged**
