### PR TITLE
docs(docs/managing_deis/platform_monitoring.rst) Update platform_monitoring.rst - added SPM Performance Monitoring

### PR DESCRIPTION
**Pull request by megastef**
Documentation how to use SPM Performance Monitoring by @sematext with Deis
Background Information: http://blog.sematext.com/2015/06/09/docker-monitoring-support/

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by mboersma** [comment]
This is great stuff @megastef. Docs LGTM, but I'd just like someone on the team to verify the steps before we merge it.

**Comment by megastef** [comment]
Hi, I got some problems doing this. I will create a new pull request. With 2 'clean' commits.

**Pull request closed without merging**
