### PR TITLE
fix(contrib) AWS instances may only have a private IP

### PR DESCRIPTION
**Pull request by sbuss**
If you're creating an aws stack in a VPC, then your instances may not
have a publicly accessible IP. This caused the fleet check to hang, and
the proxyProtocol setting to fail.

This fixes the provision-aws-cluster script to prefer the public IP if
available, but also try connecting to the private IP.

### CODE REVIEW

**Comment by sbuss** [comment]
I wasn't sure if the better behavior would be to `exit 1` when an IP can't be found. Please let me know what you prefer.

**Comment by sbuss** [comment]
@sgoings recommended I `exit 1`, so I added that and amended the commit.

**Comment by krancour** [comment]
The assumption here is that the provisioning script is being run from within the VPC, yes?

**Comment by sbuss** [comment]
@krancour Yes, this happens if you're provisioning a cluster in a VPC and you disable `AssociatePublicIP`. For reference, here's my cloudformation parameters file:

```json
[
    {
        "ParameterKey":     "KeyPair",
        "ParameterValue":   "deis"
    },
    {
        "ParameterKey":     "InstanceType",
        "ParameterValue":   "m3.xlarge"
    },
    {
        "ParameterKey":     "EC2VirtualizationType",
        "ParameterValue":   "HVM"
    },
    {
        "ParameterKey":     "AssociatePublicIP",
        "ParameterValue":   "false"
    },
    {
        "ParameterKey":     "ELBScheme",
        "ParameterValue":   "internal"
    }
]
```

Also the `VPC_ID`, `VPC_SUBNETS`, and `VPC_ZONES` env vars were all set prior to running the `provision-aws-cluster.sh` script.

**Comment by krancour** [comment]
It's occurring to me that there might be a gap in the existing documentation-- that we never point out that when installing into private subnets, you need to run the provisioning script from within the VPC.

**Comment by krancour** [comment]
Also, code LGTM.

**Comment by sbuss** [comment]
>  you need to run the provisioning script from within the VPC

What exactly do you mean by this? When I provision a cluster I do it from my laptop which is connected to our VPN, which has a connection to our VPC in aws. Are you suggesting that I should actually be running this from an aws machine provisioned in the VPC? It's been working fine for me (except for this bit around the public IP)

**Comment by krancour** [comment]
@sbuss you have infrastructure in place that not everyone has-- both client to site and site to site VPN are in play by the sounds of it.  Absent that, someone provisioning Deis onto machines that do not have public IPs would need to do so from within the VPC.

**Comment by carmstrong** [comment]
I'm confused where we left this. @krancour are you still okay with this, or is there something left to discuss based on your latest comment? 

Either way, I'll kick off a new Jenkins run: https://ci.deis.io/job/test-ec2/2839/

**Comment by krancour** [comment]
@carmstrong my LGTM stands.

**Comment by carmstrong** [comment]
Code LGTM.

**Pull request merged**
