### PR TITLE
fix(docs): typo

### PR DESCRIPTION
**Pull request by chrisgogreen**
missing e

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
thanks! :)

**Comment by bacongobbler** [comment]
Would you mind amending your commit such that it follows our style guide as @deis-admin points out? That way your name will get picked up in our release notes.

```
fix(docs): typo
```

**Comment by carmstrong** [comment]
Thanks @chrisgogreen! I amended your commit and pushed to master: 1d2615418530c710baef72b96222ac0def0590c8

Really appreciate the typo fix!

**Pull request closed without merging**
