### PR TITLE
feat(commit-msg): don't prevent a commit, only warn

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
That way you don't loose an entire commit msg if you make a mistake.

### CODE REVIEW

**Comment by bacongobbler** [comment]
LGTM

**Comment by mboersma** [comment]
I prefer the strict version actually, because with this one I'm likely to see the warnings but just commit things anyway. I was already in the habit of copying my commit message in case it got shot down...

**Comment by technosophos** [comment]
Could we at least echo back the message on error so that we can copy/paste it back in and then edit?

**Comment by carmstrong** [comment]
> Could we at least echo back the message on error so that we can copy/paste it back in and then edit?

:+1: I think failing hard and outputting the offending commit message is probably a reasonable middle ground.

**Comment by mboersma** [comment]
I'm ok with this change if this is what others would prefer. I can always tweak my local commit hook to be stricter.

**Comment by Joshua-Anderson** [comment]
My logic for making everything a warning was I figured a big block of red text was pretty obvious, and it is easier to amend a commit message if you mess it up than it is to copy and paste it and then fix it.

I don't have a strong opinion either way, as copying and pasting the commit message isn't ***too*** much work :trollface:.

**Comment by mboersma** [comment]
Code LGTM.

**Pull request merged**
