### PR TITLE
chore(models): move from django-json-field to jsonfield for Django 1.9 compatibility

### PR DESCRIPTION
**Pull request by helgi**
see deis/workflow#179

### CODE REVIEW

**Comment by arschles** [comment]
can we put this into `v2.0-beta1`?

**Comment by bacongobbler** [comment]
this is just a backported fix for deis v1. deis/workflow#179 is the v2 fix, which I think we're punting to beta.

**Comment by bacongobbler** [comment]
@helgi would you mind rebasing this, please? Thanks! <3

**Comment by bacongobbler** [comment]
looks like a doc error:

```
Warning, treated as error:
/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/docs/reference/server/api.admin.rst:7: WARNING: autodoc: failed to import module u'api.admin'; the following exception was raised:
Traceback (most recent call last):
  File "/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/docs/venv/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/controller/api/admin.py", line 10, in <module>
    from guardian.admin import GuardedModelAdmin
  File "/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/docs/venv/local/lib/python2.7/site-packages/guardian/admin.py", line 22, in <module>
    from guardian.models import Group
  File "/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/docs/venv/local/lib/python2.7/site-packages/guardian/models.py", line 93, in <module>
    monkey_patch_user()
  File "/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/docs/venv/local/lib/python2.7/site-packages/guardian/__init__.py", line 24, in monkey_patch_user
    User = get_user_model()
  File "/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/docs/venv/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 127, in get_user_model
    user_model = get_model(app_label, model_name)
  File "/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/docs/venv/local/lib/python2.7/site-packages/django/db/models/loading.py", line 271, in get_model
    self._populate()
  File "/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/docs/venv/local/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/docs/venv/local/lib/python2.7/site-packages/django/db/models/loading.py", line 97, in load_app
    app_module = import_module(app_name)
  File "/home/jenkins/workspace/test-ec2@2/src/github.com/deis/deis/docs/venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named jsonfield
```

**Comment by mboersma** [comment]
There are no plans to move the Deis v1 controller off of trusty 1.6.11, so I'm going to close this. If I'm wrong and this is important, please re-open and fix the `make -C docs/ test` error. :smile_cat:

**Pull request closed without merging**
