### PR TITLE
Move go cli to client/

### PR DESCRIPTION
**Pull request by mboersma**
This moves the `deis` python CLI to client/python and the go CLI from client-go/ to client/ and making the necessary documentation and Makefile adjustments. ~~I'll rebase it and make it easier to review once #4261 is merged, since this also includes those commits.~~ This replaces #4261.

One thing to note is that this removes completely the "[Client Reference](http://docs.deis.io/en/latest/reference/client/)" section of our docs, which was auto-generated from python docstrings. Update: there is a [sphinxcontrib-golangdomain](https://pypi.python.org/pypi/sphinxcontrib-golangdomain/0.1.3dev) plugin, so perhaps there is a way to replace that. I will investigate.

### CODE REVIEW

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
lgtm!

**Comment by mboersma** [comment]
I reworked this to remove the python `deis` CLI completely by popular demand. Negative 3 KLOCs, not too shabby.

**Comment by sgoings** [comment]
You LOC deleter cheater, @mboersma!

**Comment by krancour** [comment]
> Negative 3 KLOCs, not too shabby.

@Joshua-Anderson deserves a contributor of the year award.

**Comment by mboersma** [comment]
> @Joshua-Anderson deserves a contributor of the year award.

So true!

**Comment by bacongobbler** [comment]
still has my seal of approval. :shipit:

**Comment by mboersma** [comment]
To follow up: the sphinxcontrib-golangdomain plugin is ancient and unused. I wasn't able to get it to render any content, even by mimicking its test code examples. So we will have to say adiós to the Client ref section until someone can rehabilitate that plugin or come up with another solution. :disappointed:

**Comment by bacongobbler** [comment]
I'm not sure anyone has ever referenced the client autodocs to write their own client. Most users reference the server API in order to capture the endpoints in their client, so I think it's safe to remove it.

**Comment by carmstrong** [comment]
:ship:

**Pull request merged**
