### PR TITLE
fix(docs): handle changes in Sphinx 1.3.0

### PR DESCRIPTION
**Pull request by mboersma**
We hadn't pinned the version of Sphinx we used, so the 1.3.0 update broke some things. [Insert rant about abuse of [semver](http://semver.org/) here.]

This fixes those details and pins Deis' docs at Sphinx v1.3.0. I generated docs from this branch and [they look ok](http://deis.readthedocs.org/en/sphinx-130/) to me.

### CODE REVIEW

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
:scroll: LGTM

**Comment by mboersma** [comment]
This build failed due to an expired Debian jessie release file:
```
Sending build context to Docker daemon 
Step 0 : FROM golang:1.4
 ---> 8e4531928f57
Step 1 : ADD firewall /tmp/firewall
 ---> 4a79420139f2
Removing intermediate container d5ff5544fdcf
Step 2 : ADD build.sh /go/src/github.com/deis/deis/router/build.sh
 ---> afb2e2d8ed32
Removing intermediate container 1bc800efd605
Step 3 : WORKDIR /go/src/github.com/deis/deis/router
 ---> Running in 7566ffc689a6
 ---> 6d41edc50b51
Removing intermediate container 7566ffc689a6
Step 4 : RUN DOCKER_BUILD=true /go/src/github.com/deis/deis/router/build.sh
 ---> Running in aecfcffdd663
Get:1 http://security.debian.org jessie/updates InRelease [84.1 kB]
Get:2 http://http.debian.net jessie InRelease [199 kB]
[91mE: Release file for http://security.debian.org/dists/jessie/updates/InRelease is expired (invalid since 22h 53min 0s). Updates for this repository will not be applied.
[0m[91m/go/src/github.com/deis/deis/router/build.sh: line 46: patch: command not found
[0mtime="2015-03-11T14:33:31-06:00" level="info" msg="The command [/bin/sh -c DOCKER_BUILD=true /go/src/github.com/deis/deis/router/build.sh] returned a non-zero code: 127" 
make[1]: *** [build] Error 1
make[1]: Leaving directory `/home/jenkins/workspace/test-vagrant/src/github.com/deis/deis/router'
make: *** [build] Error 2
```

:disappointed:

**Comment by mboersma** [comment]
This PR did pass all relevant doc-related tests (then failed on the intermittent 503 error we are trying to pin down). I'm going to merge it since doc builds will be broken unless rebased from this commit.

**Pull request merged**
