### PR TITLE
chore(*): bump etcd to 2.1.3

### PR DESCRIPTION
**Pull request by mboersma**
See https://github.com/coreos/etcd/compare/v2.1.2...v2.1.3 for details of the one bug fix included. (Probably irrelevant to our current testing issues.)

### CODE REVIEW

**Comment by bacongobbler** [comment]
yup, completely irrelevant since it only deals with TLS-backed etcd clusters but still always nice to bump revs.

LGTM

**Comment by carmstrong** [comment]
Should we also bump the graceful shutdown script in user-data.example so it checks for etcd 2.1.3?

**Comment by krancour** [comment]
> Should we also bump the graceful shutdown script in user-data.example so it checks for etcd 2.1.3?

IMO, yes.  In fact, see #4388.  I am wondering if we should just upgrade `etcdctl` in _all_ new clusters (not only when graceful shutdown is enabled).  It adds useful stuff like `cluster-health` and `member list`.

**Comment by mboersma** [comment]
> Should we also bump the graceful shutdown script in user-data.example...

Good catch--I did so.

> I am wondering if we should just upgrade `etcdctl` in *all* new clusters...

Perhaps, but that's not in scope for this PR. Also we will hopefully move up to more current CoreOS very soon, in which case we will have `etcdctl` >= v2.1.2 on the box.

**Comment by krancour** [comment]
Code LGTM

**Comment by kalbasit** [comment]
Accidentally closed the PR.

**Comment by mboersma** [comment]
See #4444 instead, which effectively keeps the `etcd` version at 2.1.2 for now.

**Pull request closed without merging**
