### PR TITLE
fix(builder): fix spelling mistakes

### PR DESCRIPTION
**Pull request by Joshua-Anderson**

### CODE REVIEW

**Comment by mboersma** [comment]
Code LGTM.

**Comment by carmstrong** [comment]
Code LGTM. /cc @technosophos to see if we need to change this in go-builder

**Comment by technosophos** [comment]
Should merge fine with the new Go builder.

LGTM

**Comment by Joshua-Anderson** [comment]
> Should merge fine with the new Go builder.
:+1: Found it when looking through your rewrite :smiley:.

**Pull request merged**
