### PR TITLE
Common spelling error fixes

### PR DESCRIPTION
**Pull request by karthequian**
Hello!

This PR just fixes a bunch of spelling errors in the docs. 

Thanks!

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

**Comment by carmstrong** [comment]
Thank you for finding and fixing these! Would you mind amending your commit to adhere to our style guidelines? Something like `typo(*): fix spelling errors` would work well. Thank you!

**Comment by karthequian** [comment]
done! Sorry about that.

**Comment by carmstrong** [comment]
Awesome. Thanks @karthequian!

**Pull request merged**
