### PR TITLE
feat(router): add optional HTTPs redirect

### LINKED ISSUE #2838: feat(router): Add HTTP to HTTPs redirect
This was attempted in #2635 and again in #2782, but the implementation in those PRs doesn't seem to work. This is a desired feature, so I wanted to track it separately so it wasn't lost.

I've attempted this myself, but it appears the `server` blocks keep conflicting in the nginx template. After several failed attempts at this, I resorted to [asking StackOverflow](http://stackoverflow.com/a/27711250/644992) for help. An answer seems worthy of attempting, but I haven't had the time to get back to this, and likely will be working on other things for the next Deis release.

I wanted to document this so hopefully someone else can pick it up.

### PR DESCRIPTION
**Pull request by carmstrong**
closes #2838
replaces #2976

### CODE REVIEW

**Comment by bacongobbler** [comment]
Was wondering about the implications on `$host$1` but @carmstrong assured me that there is a slash somewhere in there, so it redirects.

code LGTM

**Comment by mboersma** [comment]
@carmstrong let's change `HTTPs` to `HTTPS`.

**Comment by carmstrong** [comment]
> Was wondering about the implications on $host$1 but @carmstrong assured me that there is a slash somewhere in there, so it redirects.

Proof:
```console
$ curl -v http://junior-renegade.local3.deisapp.com/lololol
* Hostname was NOT found in DNS cache
*   Trying 172.17.8.100...
* Connected to junior-renegade.local3.deisapp.com (172.17.8.100) port 80 (#0)
> GET /lololol HTTP/1.1
> User-Agent: curl/7.37.1
> Host: junior-renegade.local3.deisapp.com
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
* Server nginx/1.6.2 is not blacklisted
< Server: nginx/1.6.2
< Date: Fri, 13 Feb 2015 17:35:11 GMT
< Content-Type: text/html
< Content-Length: 184
< Connection: keep-alive
< Location: https://junior-renegade.local3.deisapp.com/lololol
<
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
* Connection #0 to host junior-renegade.local3.deisapp.com left intact
```

> let's change HTTPs to HTTPS.

Done.

**Comment by mboersma** [comment]
Having the option to redirect HTTP -> HTTPS should help with some EC2 situations. Code LGTM.

**Comment by wenzowski** [comment]
:+1: happy to see this

**Pull request merged**
