### PR TITLE
optimize png images using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
20 images were re-compressed by Google's zopflipng losslessly as below:

```
 controller/web/static/img/404.png               | Bin 5170 -> 2364 bytes
 controller/web/static/img/aws-ec2.png           | Bin 14401 -> 10788 bytes
 controller/web/static/img/blog-social.png       | Bin 3106 -> 1359 bytes
 controller/web/static/img/cover-image.png       | Bin 23015 -> 10660 bytes
 controller/web/static/img/deis-graphic.png      | Bin 29035 -> 23412 bytes
 controller/web/static/img/deis_builder.png      | Bin 28223 -> 13544 bytes
 controller/web/static/img/deis_logo.png         | Bin 10104 -> 7626 bytes
 controller/web/static/img/favicon.png           | Bin 324 -> 245 bytes
 controller/web/static/img/fork.png              | Bin 1731 -> 828 bytes
 controller/web/static/img/glyphs.png            | Bin 3854 -> 1538 bytes
 controller/web/static/img/large-social.png      | Bin 18518 -> 7622 bytes
 controller/web/static/img/mag_glass.png         | Bin 307 -> 249 bytes
 controller/web/static/img/menu-logo.png         | Bin 4609 -> 2865 bytes
 controller/web/static/img/social.png            | Bin 3606 -> 2251 bytes
 docs/managing_deis/DeisLoadBalancerDiagram.png  | Bin 154714 -> 137970 bytes
 docs/understanding_deis/DeisControlPlane.png    | Bin 140620 -> 124325 bytes
 docs/understanding_deis/DeisDataPlane.png       | Bin 128625 -> 110011 bytes
 docs/understanding_deis/DeisGitPushWorkflow.png | Bin 190468 -> 166680 bytes
 docs/understanding_deis/DeisRouterMesh.png      | Bin 151402 -> 105056 bytes
 docs/understanding_deis/DeisSystemDiagram.png   | Bin 188336 -> 163582 bytes
```

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
would you mind contributing a script to compress any images in the future, as well as documentation? That would be useful so we can figure out how to allow contributors to do the same to their logos. :)

**Comment by PeterDaveHello** [comment]
@bacongobbler It can be possible, maybe we could put it in another new PR?

**Comment by bacongobbler** [comment]
sure.

**Comment by PeterDaveHello** [comment]
@bacongobbler  do you have any suggestion about the script? Since the zopflipng optimize process takes a long time, it's better not to double compress the same pictures.

**Comment by bacongobbler** [comment]
Just a document on how contributors can compress their images via zopflipng before uploading would do. :)

**Comment by bacongobbler** [comment]
something in CONTRIBUTING.md would be nice. Even just a comment here so we can document it for v2, deis.io etc. would be helpful.

**Pull request merged**
