### PR TITLE
ref(contrib/aws): remove disk replacements that were forgotten in #4444

### PR DESCRIPTION
**Pull request by helgi**
Not needed anymore due to #4444 and moving away from containerized etc2

### CODE REVIEW

**Comment by carmstrong** [comment]
ping @mboersma for other review

**Comment by bacongobbler** [comment]
According to https://github.com/deis/deis/commit/445dbaecfadb1e2690734413cc43f30abcb13b21#commitcomment-14220568 and to https://github.com/deis/deis/blob/master/contrib/coreos/user-data.example#L14, this seems like it was still necessary. Is there somewhere else which we're missing or should we revert this? It sounds like etcd on AWS isn't using the EBS as we expected for new clusters on v1.12.

**Comment by helgi** [comment]
This particular PR removed an ENV var that was no longer used, the original #4444 removed the usage of all of those. This may however need to be included in the actual `user-data` replacement in a different way.

**Comment by bacongobbler** [comment]
Good point. I'll see if I can whip a PR for that

**Pull request merged**
