### PR TITLE
docs(system-requirements): Fix broken link

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
I think [etcd disaster recovery](https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#disaster-recovery) is more relevant here since we're specifically talking about the number of machines etcd requires to maintain quorum. lgtm otherwise!

**Comment by jgmize** [comment]
@bacongobbler I agree, and I've amended the commit to link there instead.

**Comment by carmstrong** [comment]
Thanks for finding this, @jgmize. It looks like we also use this old link on both:

docs/installing_deis/aws.rst
docs/installing_deis/rackspace.rst

Would you mind fixing all of those as well?

**Comment by jgmize** [comment]
@carmstrong sure, I've amended the commit to fix those links, as well.

**Comment by carmstrong** [comment]
LGTM. Thanks @jgmize!

**Pull request merged**
