### PR TITLE
fix('contrib/azure/azure-coreos-cluster'): make this not found error more user friendly

### PR DESCRIPTION
**Pull request by sedouard**
Currently this error spews for any little reason. It helps if we catch and explain some quick things to look for

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by sedouard** [comment]
@timfpark can you take a look?

**Comment by timfpark** [comment]
LGTM

**Comment by carmstrong** [comment]
Great debug message. Code LGTM.

**Comment by mboersma** [comment]
Code LGTM.

**Comment by carmstrong** [comment]
Thanks @sedouard!

**Pull request merged**
