### PR TITLE
chore(*): bump CoreOS to 1010.5.0

### PR DESCRIPTION
**Pull request by mboersma**
See https://coreos.com/releases/#1010.5.0

### CODE REVIEW

**Comment by mboersma** [comment]
This may need an update to docker-py or somesuch. It's currently failing on the first app push with `failed to retrieve configuration`.

**Comment by laurrentt** [comment]
I also get a `raise CannotSendRequest()` whenever the controller tries to make a request to fleet. I'm investigating.

**Comment by bacongobbler** [comment]
keeping @arschles' LGTM, but I'm removing mine until I can actually manually test this as well.

**Comment by laurrentt** [comment]
Can you add this:

```
# allow deis user permission to fleet
if addgroup -g "$(stat -c "%g" /var/run/fleet.sock)" fleet; then
	addgroup deis fleet
fi
```

to controller/bin/boot ? It seems to fix the fleet issue.

**Comment by mboersma** [comment]
Thanks @laurrentt! I was just starting to debug why controller couldn't talk to fleet any longer...

I tested this change locally on vagrant. 👍

**Comment by aledbf** [comment]
@mboersma just in case I'm getting [this](https://github.com/coreos/bugs/issues/1301) error with 1010.5.0  if overlayfs is used (in some nodes)

**Comment by bacongobbler** [comment]
thanks for pointing this out, @aledbf. I'll see if I can reproduce it in my testing environment to see if this is a showstopper and we should wait for 1080.0.0 to get on the stable channel.

**Comment by bacongobbler** [comment]
I was not able to reproduce given the following diff for [example-dockerfile-python](https://github.com/deis/example-dockerfile-python), which is based on alpine:

```
diff --git a/Dockerfile b/Dockerfile
index 1c632ba..644fc63 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,5 +1,6 @@
 FROM gliderlabs/alpine:3.4
-
+MAINTAINER matt fisher <me@bacongobbler.com>
+RUN mkdir -p /tmp/foo
 RUN apk-install python
 ADD . /app
 WORKDIR /app
```

@aledbf do you have a way to reliably repro this bug?

**Comment by aledbf** [comment]
@bacongobbler no but I see this with images that share some intermediate layer

**Comment by aledbf** [comment]
@bacongobbler just in case I reinstalled the cluster with `899.17.0`.

**Comment by mboersma** [comment]
I also tested this by pushing several Dockerfile and buildpack apps on CoreOS 1010.5.0, but I assume the bug isn't that easy to reproduce: worked fine.

**Comment by mboersma** [comment]
@aledbf is this bug easy or difficult to trigger? Is there a workaround?

Given that @bacongobbler and I couldn't reproduce it with initial testing, I'm trying to assess if the severity of coreos/bugs#1301 is enough to affect the [v1.13.2](https://github.com/deis/deis/releases/tag/v1.13.2) maintenance release. Options are:
- release v1.13.2 as-is (essentially same as master), knowing this bug may occur
- revert this PR and ship v1.13.2 with CoreOS 899.17.0
- delay a v1.13.2 release until there is a resolution for coreos/bugs#1301

**Comment by aledbf** [comment]
> Is there a workaround?

No. The only solution (mentioned in a docker issue) is to not use overlay if SELinux is enabled

> is this bug easy or difficult to trigger?

For me after 5 minutes with 1010.5.0 is impossible to start containers in some nodes (apps using buildpacks). Now maybe the issue it is not easy to reproduce with a low number of containers (I have ~3800)

I mentioned this issue here because is not possible to return to 1.9.1 after the upgrade to 1.10.3 which is a huge issue in a production cluster.

**Comment by bacongobbler** [comment]
> Options are:

My vote is to revert this PR to ship v1.13.2, given that [there are a metric ton of good fixes](https://github.com/deis/deis/compare/v1.13.1) in this release. OTOH, coreos/bugs#1301 has been given P1 priority and should hopefully be fixed soon, but we're not sure how long it'll take until said fix will land in the stable channel.

**Comment by laurrentt** [comment]
I've been running this code in staging for the last 2 weeks and in prod for a week and personally, I won't not revert it. So just to be clear, those who use Deis pull are not impacted, right ?

**Comment by mboersma** [comment]
The issue is fixed in https://github.com/coreos/coreos-overlay/pull/2006, but I don't know when that will make it to stable.

**Comment by laurrentt** [comment]
@mboersma Sorry for my confusing post 😕 . Here's my question: Does this CoreOS issue only affects the Deis builder (the only instance of docker inside docker I know in the platform) ? Thank you 😄

**Comment by mboersma** [comment]
> Does this only affect the Deis builder?

I don't know for sure. My assumption was it could also be triggered by the Deis controller component, since it mounts `docker.sock` inside the container. Sorry I wasn't more specific--maybe @aledbf can explain where it was triggered for him?

It seems safer to revert CoreOS to the "known good" version until this bug is resolved--see #5053. Does that make sense to you @laurrentt? You should be able to stay on CoreOS 1010.5.0 if you prefer with the next Deis patch release, if the bug wasn't affecting you.

**Comment by aledbf** [comment]
> Does this CoreOS issue only affects the Deis builder

No, I saw issues with sysdig and `gcr.io/google_containers` images with layers in commons

**Comment by aledbf** [comment]
@laurrentt as @mboersma said if the bug is not affecting you just continue using CoreOS 1010.5.0

**Comment by laurrentt** [comment]
Thanks @mboersma and @aledbf for the precisions. I'm keeping my fingers crossed that it won't happen in my environments and will update my CoreOS as soon as the patch is out.

(Not sure if crossing fingers qualify as best practise though... 😂 but I have faith)

**Pull request merged**
