### PR TITLE
feat(controller): worker processes named as "deis-controller"

### PR DESCRIPTION
**Pull request by mboersma**
[The `-n` gunicorn option](http://docs.gunicorn.org/en/latest/settings.html#proc-name) wasn't working because the python [setproctitle](https://pypi.python.org/pypi/setproctitle/) library wasn't installed. This change also moves config options into a separate file (which facilitates signal handlers, which I've been [~~fighting~~ working with](https://github.com/deis/deis/issues/3035#issuecomment-74346603)), and renames the processes from "deis" to "deis-controller" so they're easier to identify on the host.

Before (cropped, but you get the idea):
```console
root@71881ad2ee93:/app# ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       662  0.0  0.1  18148  3180 ?        S    20:04   0:00 bash
root       680  0.0  0.1  15572  2132 ?        R+   20:04   0:00  \_ ps faux
root         1  0.0  0.1  18008  3016 ?        Ss   20:01   0:00 /bin/bash /app/bin/boot
root       122  0.0  0.1  43000  2260 ?        S    20:01   0:00 sudo -E -u deis gunicorn deis.wsgi -b 0.0.0.0 -w 8 -n deis --t
deis       129  0.0  0.5  48604 11124 ?        S    20:01   0:00  \_ /usr/bin/python /usr/local/bin/gunicorn deis.wsgi -b 0.0.0
deis       134  0.0  0.8  56308 16456 ?        S    20:01   0:00      \_ /usr/bin/python /usr/local/bin/gunicorn deis.wsgi -b 0
deis       135  0.0  0.7  56316 16408 ?        S    20:01   0:00      \_ /usr/bin/python /usr/local/bin/gunicorn deis.wsgi -b 0
deis       136  0.0  0.7  56328 16416 ?        S    20:01   0:00      \_ /usr/bin/python /usr/local/bin/gunicorn deis.wsgi -b 0
deis       137  0.0  0.7  56324 16420 ?        S    20:01   0:00      \_ /usr/bin/python /usr/local/bin/gunicorn deis.wsgi -b 0
deis       138  0.0  0.7  56344 16428 ?        S    20:01   0:00      \_ /usr/bin/python /usr/local/bin/gunicorn deis.wsgi -b 0
deis       139  0.0  0.8  56352 16436 ?        S    20:01   0:00      \_ /usr/bin/python /usr/local/bin/gunicorn deis.wsgi -b 0
deis       140  0.0  0.8  56364 16444 ?        S    20:01   0:00      \_ /usr/bin/python /usr/local/bin/gunicorn deis.wsgi -b 0
deis       141  0.0  0.8  56376 16452 ?        S    20:01   0:00      \_ /usr/bin/python /usr/local/bin/gunicorn deis.wsgi -b 0
root       123  0.0  0.1 254792  3636 ?        Sl   20:01   0:00 confd -node 172.17.8.100:4001 -config-file /app/confd.toml
root       661  0.0  0.0   4352   692 ?        S    20:04   0:00 sleep 5
```

After:
```console
root@53b96dfac6b3:/app# ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        12  0.0  0.1  18148  3112 ?        S    20:12   0:00 bash
root       147  0.0  0.1  15572  2232 ?        R+   20:12   0:00  \_ ps faux
root         1  0.0  0.1  18008  3048 ?        Ss   20:12   0:00 /bin/bash /app/bin/boot
root       108  0.0  0.1  43000  3096 ?        S    20:12   0:00 sudo -E -u deis gunicorn -c deis/gconf.py deis.wsgi
deis       113  1.1  0.7  51128 15760 ?        S    20:12   0:00  \_ gunicorn: master [deis-controller]                        
deis       120  0.5  0.9  58420 19248 ?        S    20:12   0:00      \_ gunicorn: worker [deis-controller]                    
deis       121  0.5  0.9  58432 19136 ?        S    20:12   0:00      \_ gunicorn: worker [deis-controller]                    
deis       122  0.5  0.9  58440 19148 ?        S    20:12   0:00      \_ gunicorn: worker [deis-controller]                    
deis       123  0.6  0.9  58448 19152 ?        S    20:12   0:00      \_ gunicorn: worker [deis-controller]                    
deis       124  0.5  0.9  58456 19160 ?        S    20:12   0:00      \_ gunicorn: worker [deis-controller]                    
deis       125  0.3  0.9  58464 19160 ?        S    20:12   0:00      \_ gunicorn: worker [deis-controller]                    
deis       126  0.3  0.9  58560 19164 ?        S    20:12   0:00      \_ gunicorn: worker [deis-controller]                    
deis       127  0.3  0.9  58488 19176 ?        S    20:12   0:00      \_ gunicorn: worker [deis-controller]                    
root       109  0.0  0.2 179972  6072 ?        Sl   20:12   0:00 confd -node 172.17.8.100:4001 -config-file /app/confd.toml
root       146  0.0  0.0   4352   660 ?        S    20:12   0:00 sleep 5
```

### CODE REVIEW

**Comment by carmstrong** [comment]
Cool - I also like the verbosity with the arguments, as well. I'm a bit confused on how the config file is actually getting written to the filesystem as `deis/gconf.py` - I assume this is some black magic with the image build?

**Comment by mboersma** [comment]
> I'm a bit confused on how the config file is actually getting written...

I added `deis/gconf.py` in this commit. You can specify gunicorn options on the command line, or in a python config file like this one (which is the only way to use custom signal handler funcs).

**Comment by carmstrong** [comment]
> I added deis/gconf.py in this commit.

Right - I meant how are we copying that into the image, but I think https://github.com/deis/deis/blob/656a7fb0b663c911120b91be93de6f913cd90c68/controller/Dockerfile#L29 takes care of that.

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by gabrtv** [comment]
Very nice improvement all around. Clearer host-level process titles should be a big win. LGTM.

**Comment by bacongobbler** [comment]
:+1:

**Pull request merged**
