### PR TITLE
Fixes issue #3764. Dont throw IOError when pipe closes.

### LINKED ISSUE #3764: deis commands throw errors when being piped to head
When output of deis commands exceeds default number of lines `head` accepts (10), it starts throwing python exception. For example:
```
> $ deis logs -a staging -n 11 | head
2015-05-25T21:54:45UTC staging[web.1]:   Rendered shared/_head.html.slim (0.3ms)
2015-05-25T21:54:45UTC staging[web.1]:   Rendered shared/_ga.html.erb (0.2ms)
2015-05-26T08:56:36UTC staging[web.1]: Started GET "/" for 84.19.35.118 at 2015-05-26 08:56:36 +0000
2015-05-26T08:56:36UTC staging[web.1]: Processing by WebsiteController#index as HTML
2015-05-26T08:56:36UTC staging[web.1]: Filter chain halted as :authenticate rendered or redirected
2015-05-26T08:56:36UTC staging[web.1]: Completed 401 Unauthorized in 1ms
2015-05-26T22:06:34UTC staging[web.1]: Started GET "/" for 46.37.55.80 at 2015-05-26 22:06:34 +0000
2015-05-26T22:06:34UTC staging[web.1]: Processing by WebsiteController#index as HTML
2015-05-26T22:06:34UTC staging[web.1]: Filter chain halted as :authenticate rendered or redirected
2015-05-26T22:06:34UTC staging[web.1]: Completed 401 Unauthorized in 1ms
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/build-deis-cli-installer-linux/workspace/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/logging", line 875, in emit
  File "/var/lib/jenkins/jobs/build-deis-cli-installer-linux/workspace/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/logging", line 835, in flush
IOError: [Errno 32] Broken pipe
Logged from file <string>, line 670
```
but
```
> $ deis logs -a staging -n 10 | head
2015-05-25T21:54:45UTC staging[web.1]:   Rendered shared/_ga.html.erb (0.2ms)
2015-05-26T08:56:36UTC staging[web.1]: Started GET "/" for 84.19.35.118 at 2015-05-26 08:56:36 +0000
2015-05-26T08:56:36UTC staging[web.1]: Processing by WebsiteController#index as HTML
2015-05-26T08:56:36UTC staging[web.1]: Filter chain halted as :authenticate rendered or redirected
2015-05-26T08:56:36UTC staging[web.1]: Completed 401 Unauthorized in 1ms
2015-05-26T22:06:34UTC staging[web.1]: Started GET "/" for 46.37.55.80 at 2015-05-26 22:06:34 +0000
2015-05-26T22:06:34UTC staging[web.1]: Processing by WebsiteController#index as HTML
2015-05-26T22:06:34UTC staging[web.1]: Filter chain halted as :authenticate rendered or redirected
2015-05-26T22:06:34UTC staging[web.1]: Completed 401 Unauthorized in 1ms
2015-05-26T22:06:34UTC staging[web.1]: Started GET "/" for 46.37.55.80 at 2015-05-26 22:06:34 +0000
```
Exception output repeats for each line from 11.

This basically means that there is no way to extract first lines of output by `head -n 2`.

### PR DESCRIPTION
**Pull request by olalonde**
Fixes #3764

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
LGTM, tested. Before:
```console

$ deis logs -n 10 | head -2
2015-05-30T03:45:11UTC deluxe-handbill[web.2]: 4 processes at 128MB memory limit.
2015-05-30T03:45:11UTC deluxe-handbill[web.2]: Starting php-fpm...
Traceback (most recent call last):
  File "/Users/matt/Projects/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/logging", line 875, in emit
  File "/Users/matt/Projects/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/logging", line 835, in flush
IOError: [Errno 32] Broken pipe
Logged from file <string>, line 685
```
After:
```console
$ deis logs -n 10 | head -2
2015-05-30T03:45:11UTC deluxe-handbill[web.2]: 4 processes at 128MB memory limit.
2015-05-30T03:45:11UTC deluxe-handbill[web.2]: Starting php-fpm..
```

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by mboersma** [comment]
@olalonde could you `git commit --amend` the subject to comply with our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style)? Otherwise it won't show up in the CHANGELOG.md. Something like:
```
fix(client): don't raise IOError when pipe closes
```

**Comment by olalonde** [comment]
@mboersma ok sure, I just read those guidelines and was about to ask if I should do that :)

**Comment by olalonde** [comment]
Done.

**Comment by carmstrong** [comment]
Code LGTM. Thanks @olalonde!

**Comment by mboersma** [comment]
@olalonde could you rebase this off the current master branch? I think its tests fell victim to #3771, which was fixed in master recently.

**Comment by olalonde** [comment]
Rebased.

**Comment by mboersma** [comment]
Code LGTM.

**Pull request merged**
