### PR TITLE
Change default Availability Zones' index

### PR DESCRIPTION
**Pull request by beechnut**
I received the following error when running `/provision-ec2-cluster.sh` in the us-east-1, which resulted in the deletion of my CloudFormation stack every time:

`Value "us-east-1a" for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1b, us-east-1e, us-east-1c, us-east-1d.`

AZs are selected by choosing the 0th and 1st returned AZs, but the 0th one in us-east-1 is us-east-1a, which is an invalid zone. I changed it to select the 1st and 2nd (1b and 1c, probably), and it builds the stack successfully.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
I think **currently** is the salient word in their error message, however. If you tried tomorrow, you might find `us-east-1a` is back and `us-east-1b` is now unavailable. So shifting the index by one isn't really a safe or long-term fix.

**Comment by carmstrong** [comment]
Yep. And, unfortunately, your availability zones are not mine - see #1601. There's nothing we can account for here unless we rewrite the provision script to probe for AZs and try them all, one-by-one.

**Comment by mboersma** [comment]
And what's really going to bake your noodle:

> your availability zones are not mine

That makes it doubly hard.

> unless we rewrite the provision script to probe for AZs and try them all, one-by-one.

That seems like the right way to do it. Not simple though.

**Comment by carmstrong** [comment]
> And what's really going to bake your noodle:

woah

**Comment by beechnut** [comment]
Thanks, y'all -- that was a great crash course in Availability Zones.

**Pull request closed without merging**
