### PR TITLE
feat(ec2): Adding support to set ELB Scheme

### PR DESCRIPTION
**Pull request by smatejina**
Option to create internal load balancer

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by carmstrong** [comment]
@smatejina rather than overriding this in gen-json.py, we can simply toggle a parameter option in the CloudFormation template itself. See #2625 for an example of this.

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by carmstrong** [comment]
Thanks for this, @smatejina! I cleaned this up in #3074.

**Pull request closed without merging**
