### PR TITLE
feat(contrib): AWS cli profile param

### LINKED ISSUE #3562: Add profile parameter to provision-ec2-cluster.sh
When provisioning a new cluster, the aws cli uses the default profile, it would be nice to specify which cli profile you would like to use.

### PR DESCRIPTION
**Pull request by cleblanc87**
- [X] update-ec2-cluster.sh
- [X] provision-ec2-cluster.sh
- [ ] test-integration-ec2.sh

Closes #3562

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by eMxyzptlk** [comment]
#3575 :)

**Comment by bacongobbler** [comment]
code LGTM. @mboersma know any tricks or a link to the docs for getting set up on EC2?

**Comment by bacongobbler** [comment]
Jenkins, add to whitelist.

**Comment by cleblanc87** [comment]
Does test-integration-ec2 need the profile support? It looks like just setting the env vars might be sufficient?

**Comment by bacongobbler** [comment]
It'd be nice but it's not necessary for this PR. Setting the envvars should be sufficient enough

**Comment by mboersma** [comment]
Currently test-integration-ec2.sh just expects the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables, which are set by the Jenkins job. (Those two are respected by both `boto` and `awscli`, so don't use the older variants just FYI.) I agree: adding profile support there is optional since it works as-is currently.

**Comment by bacongobbler** [comment]
@cleblanc87 wouldyou mind rebasing this PR? I think it's fine to merge as-is. We can address test-integration-ec2 in the future

**Comment by cleblanc87** [comment]
@bacongobbler rebased

**Comment by bacongobbler** [comment]
Looks like Jenkins no longer like this PR :(

> The config profile (default) could not be found

**Comment by cleblanc87** [comment]
Hmm wonder how it passed before. Maybe the profile flag should only be set if is provided instead of sending default.

**Comment by bacongobbler** [comment]
Yeah, something like

```
if [ -z "$AWS_CLI_PROFILE" ]; then
  EXTRA_ARGS+="--profile $AWS_CLI_PROFILE"
fi

STACK_STATUS=$(aws --output text cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].StackStatus' $EXTRA_ARGS)
```

**Comment by carmstrong** [comment]
@cleblanc87 Are you still interested in cleaning this up so the integration tests can pass? Thanks for the work thus far!

**Comment by cleblanc87** [comment]
Updated!

**Comment by carmstrong** [comment]
> Updated!

I think we're still waiting on the changes to `test-integration-ec2.sh`.

**Comment by cleblanc87** [comment]
@carmstrong per this PR thread test-integration-ec2 was decided to be out of scope here, as it relies on env vars.

**Comment by mboersma** [comment]
Code LGTM.

**Pull request merged**
