### PR TITLE
fix(deisctl): fix how target names resolve

### PR DESCRIPTION
**Pull request by krancour**
Addresses #4201 

Ping @technosophos

### CODE REVIEW

**Comment by krancour** [comment]
@technosophos your last bit of feedback has been accounted for.

**Comment by mboersma** [comment]
This looks good. Could there also be tests added for this behavior to [`unit_test.go`](https://github.com/krancour/deis/blob/fix-deisctl-journal/deisctl/backend/fleet/unit_test.go)?

**Comment by krancour** [comment]
@mboersma there could.  I'll add.

**Comment by krancour** [comment]
@mboersma unit test added.

**Comment by mboersma** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
Since we're just checking for the prefix, `deisctl journal c` would probably match against multiple containers, too, though I guess this is intentional for `deisctl journal router`.

Code LGTM

**Comment by carmstrong** [comment]
@krancour This looks good to :ship:!

**Pull request merged**
