### PR TITLE
fix(deisctl): avoid stdout issues in tests

### PR DESCRIPTION
**Pull request by mboersma**
Some unit tests will fail with `GOMAXPROCS` > 1, so this change allows `make test-unit` to pass until there is a proper fix.

### CODE REVIEW

**Comment by sgoings** [comment]
How is stdout related to GOMAXPROCS?

**Comment by mboersma** [comment]
I haven't actually dug into this one, but in the other similar # TODO: cases I think we were reading stdout from a goroutine with improper channel handling or...mumble... I know empirically in these cases it's `GOMAXPROCS` and therefore a concurrency issue.

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by technosophos** [comment]
Code LGTM

**Pull request merged**
