### PR TITLE
feat(client): add --git-hostname option

### LINKED ISSUE #3948: proposal feat(client) allow for custom git hostname
When I was trying to set cloudflare between deis and rest of the world it came to my attention that they will block anything except http/https traffic (for example tcp/2222), I don't know if cloudfront is affected too. 

Maybe I can add support for optional git hostname which will be passed from commandline to client.json, and used for all git related actions. I could implement it myself client code looks clean. 

I just need your opinion.

### PR DESCRIPTION
**Pull request by szymonpk**
--git-hostname=<hostname> option for register/login purposes. If used
'git_hostname' will be added to client.json and used as git server
hostname, when app is created or git:remote is used. It's useful when
controler is behind Cloudflare's Flexible SSL, which will block any
non-HTTP/HTTPS traffic and git server behind different hostname.

It doesn't break any functionality.

Closes #3948.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by bacongobbler** [comment]
looks like this PR failed integration tests:

```

Creating application...  ...  o.. done, created appssample
Creating config...  ... done, v2

=== appssample
BUILDPACK_URL: https://example.com
Traceback (most recent call last):
  File "<string>", line 2566, in <module>
  File "<string>", line 2562, in main
  File "<string>", line 2495, in _dispatch_cmd
  File "<string>", line 534, in apps_create
  File "<string>", line 1625, in _git_remote_create
KeyError: 'git_hostname'
```

**Comment by szymonpk** [comment]
Sorry, haven't noticed earlier :/. I'll fix it asap.

**Comment by mboersma** [comment]
This failed in Deis' [integration tests](https://ci.deis.io/job/test-ec2/1865/consoleFull#682192135502066c60b2236c09cc9bf8):
```
=== appssample
BUILDPACK_URL: https://example.com
Traceback (most recent call last):
  File "<string>", line 2566, in <module>
  File "<string>", line 2562, in main
  File "<string>", line 2495, in _dispatch_cmd
  File "<string>", line 534, in apps_create
  File "<string>", line 1625, in _git_remote_create
KeyError: 'git_hostname'
```

**Comment by mboersma** [comment]
Since [the rewrite](https://github.com/deis/deis/issues/3806) of `deis` CLI to go is nearing completion, it's become counterproductive to add new features to the soon-to-be-deprecated python client. But allowing for a custom git hostname as suggested in #3948 is still a valid use case, so a similar change (with tests!) in the go code under client-go/ would be welcome. Thanks @szymonpk!

**Pull request closed without merging**
