### PR TITLE
fix(contrib/linode): fix discovery url issues in deployment scripts

### PR DESCRIPTION
**Pull request by croemmich**
Fix discovery url replacement and detection caused by user-data changes.

### CODE REVIEW

**Comment by mboersma** [comment]
Thanks so much for patching up Linode after the apparently breaking `#DISCOVERY_URL` change. :disappointed_relieved:  For reference, here is how this was fixed for [Azure](https://github.com/deis/deis/pull/4680) and [GCE](https://github.com/deis/deis/pull/4688).

**Comment by croemmich** [comment]
You bet!

Is there an advantage to `with open(file.name, 'r') as file` as was done for Azure and GCE?

**Comment by mboersma** [comment]
`with open(file)` just ensures that the file is closed explicitly even if an exception occurs under the `with` block. But this should also happen when the file object is garbage-collected, or when the python interpreter exits. So it's good general practice but not a big deal for a read-only file handle in a run-then-exit script like this I'd say.

**Comment by croemmich** [comment]
Good to know. Thanks!

**Pull request merged**
