### PR TITLE
fix(contrib): preseed all images

### PR DESCRIPTION
**Pull request by PierreKircher**
there was a iteration bug .. it just preseeded the builder

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
good catch. Would you mind amending your commit to follow our style guide? Something like `fix(contrib): preseed all images`

**Comment by mboersma** [comment]
@PierreKircher could you `git commit --amend` the commit as well to match this issue's title? I'm glad you caught this bug, thanks!

**Comment by mboersma** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
I started a job and then realized that it wouldn't necessarily test this. I'm just gonna quickly verify this fix

**Comment by mboersma** [comment]
True, Jenkins won't touch this. I copied the relevant lines out of the file and tested before-and-after in my shell. Confirmed that we just hit `builder` before and enumerate all components after this fix.

**Comment by aledbf** [comment]
Code LGTM.

**Pull request merged**
