### PR TITLE
fix(controller): write app event logs via logspout

### LINKED ISSUE #3963: API / controller logging should be via logspout
I haven't dug into the code too deeply yet, but conversation in #3947 exposed that `deis-controller` logs are written _directly_ to a volume that it shares with `deis-logger`.  This means that the route `deis-controller` logs take to their resting place on that volume is _different_ than the route taken by application logs making their way to the same place.  In the case of an application, it's via `STDOUT` --> `deis-logspout` --> `deis-logger` --> the volume.

There's a slight problem that arises from this discrepancy.  In the increasingly common scenario where an operator runs "Ceph-less," Deis is installed sans the storage subsystem components and adequate, external alternatives are provided for those components _and_ any other Deis component that expresses a direct dependency on the storage subsystem (e.g. `deis-database`).  When opting to run this way, `deis-logger` is among the components not installed.  A consequence of this is that `deis-logspout` is configured to forward logs _directly_ to an external log service.  Since application logs are forwarded via `deis-logspout`, those logs all make it to the external service.  `deis-controller` logs, on the other hand, since they take a different route, would never make it to the external log service.

It seems this could be easily corrected by transitioning `deis-controller` to writing its logs via `STDOUT` and `logspout` just as any application does.  This would increase consistency and guarantee that whether running with or without Ceph and `deis-logger`, all logs ultimately land in one common place via a consistent path.

In #3947 @bacongobbler has noted some possible problems with this approach, but we should probably move that discussion here.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #3963 

This works by allowing `deis-controller` to write log messages on behalf of an application simply by prefixing them with `[app-name]:`.  `deis-logspout` has been enhanced to recognize such messages and treat the application as the source instead of the `deis-controller`.  `deis-controller` will be treated as the "pid" instead.

Given the following sequence of events:

```
$ deis create arrogant-kirk
$ git push deis master
$ deis logs
```

Old output would have looked like this:

```
2015-09-08T22:02:32UTC deis[api]: kent created initial release
2015-09-08T22:03:49UTC deis[api]: kent deployed 14fb753
2015-09-08T22:03:49UTC deis[api]: kent scaled containers web=1
2015-09-08T22:04:07UTC arrogant-kirk[web.1]: 2015/09/08 22:28:17 listening on 5000...
```

New output looks like this:

```
2015-09-08T22:02:32UTC arrogant-kirk[deis-controller]: kent created initial release
2015-09-08T22:03:49UTC arrogant-kirk[deis-controller]: kent deployed 14fb753
2015-09-08T22:03:49UTC arrogant-kirk[deis-controller]: kent scaled containers web=1
2015-09-08T22:04:07UTC arrogant-kirk[web.1]: 2015/09/08 22:04:07 listening on 5000...
```

IMO, the format differences are a positive change.  If logs from the former example were viewed in Papertrail or Splunk, for instance, there's nothing in the first three messages that correlates them to the `arrogant-kirk` application at all.  The logs from the latter example do not exhibit that problem.

### CODE REVIEW

**Comment by krancour** [comment]
Note to self: #4347 will require a similar update in the Deis module it implements for logspout v3.

**Comment by krancour** [comment]
Related to #4083

**Comment by mboersma** [comment]
LGTM.

> IMO, the format differences are a positive change.

I agree. I can see in the [test log](https://ci.deis.io/job/test-ec2/3062/consoleFull) this works well. Nice job writing tests and clean, commented code in both languages!

**Comment by bacongobbler** [comment]
Code LGTM. The rationale behind `deis[api]` was to match heroku's log format of `heroku[api]` for any app-related events from their controller, but it's a cosmetic thing so I'm okay with this.

**Pull request merged**
