### PR TITLE
test(deisctl): parallelize all of the things

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
In theory this should speed your builds up. We should test to confirm that there is a performance benefit.

##### Before:

``` shell
$ time make -C deisctl test
...
real 0m21.975s
user 0m15.506s
sys  0m4.569s
```

##### After:

``` shell
$ GOMAXPROCS=4 time make -C deisctl test
...
15.98 real        15.70 user         6.10 sys
```

I'd appreciate it if anybody has any time to test this and report if this had enough impact to warrant merging

### CODE REVIEW

**Comment by mboersma** [comment]
I get numbers roughly like yours when I run the tests, but that's using the default of 1 goroutine. `GOMAXPROCS=4 time make -C deisctl/ test` runs in only 12 seconds, but throws an error:
```
-- PASS: TestDeleteConfig-4 (0.00s)
--- PASS: TestGetConfigError-4 (0.00s)
--- PASS: TestConfigRouterCert-4 (0.00s)
--- PASS: TestConfigRouterKey-4 (0.00s)
--- PASS: TestConfigSSHPrivateKey-4 (0.00s)
PASS
coverage: 45.1% of statements
ok  	github.com/deis/deis/deisctl/config	0.027s	coverage: 45.1% of statements
?   	github.com/deis/deis/deisctl/units	[no test files]
=== RUN TestResolvePath-4
--- PASS: TestResolvePath-4 (0.00s)
PASS
coverage: 33.3% of statements
ok  	github.com/deis/deis/deisctl/utils	0.010s	coverage: 33.3% of statements
godep: go exit status 1
make: *** [test-unit] Error 1
       12.70 real        14.42 user         3.95 sys
```

**Comment by Joshua-Anderson** [comment]
Ah. That explains a lot, I thought the default was #cpu cores. It looks like the `deisctl_tests` are not thread safe, I'll look into that.

**Comment by Joshua-Anderson** [comment]
I disabled parallelism on the `desictl_test` tests as they depended on `STDOUT` and therefore couldn't be parallelized.

**Comment by mboersma** [comment]
With parallelization disabled on the stdout-related tests, I still see a consistent and worthwhile time savings. This is representative of several runs:
```console
$ time make -C deisctl/ test
...
real	0m21.300s
user	0m14.416s
sys	0m4.157s
$ time GOMAXPROCS=4 make -C deisctl/ test
...
real	0m12.841s
user	0m14.552s
sys	0m4.230s
```
Let's fix the commit subject to say "parallelize". :japanese_ogre:

**Comment by Joshua-Anderson** [comment]
@mboersma Done!  Spelling is hard.

**Comment by mboersma** [comment]
Spelling "parallel" in particular is hard, that one always makes me look it up.

**Comment by carmstrong** [comment]
Code LGTM. Jenkins passed.

**Comment by mboersma** [comment]
Code LGTM.

**Pull request merged**
