### PR TITLE
[WIP] ref(contrib/aws): generate discovery url on each provision

### PR DESCRIPTION
**Pull request by helgi**
Fixes the AWS side of #4528

### CODE REVIEW

**Comment by sgoings** [comment]
This will cause 2 `make discovery-url` calls when using `rigger` but I figger that's ok for now.

**Comment by helgi** [comment]
How's that? Is it because you are doing 2 clusters or because of the split up handling and rigger runs both?

**Comment by sgoings** [comment]
https://github.com/deis/rigger/blob/master/commands/provision/script

**Comment by carmstrong** [comment]
If someone is calling an update to an existing stack or making other modifications to a running cluster, chances are they won't want to use a new discovery URL. We should double-check that this doesn't inadvertently result in a split etcd cluster.

**Comment by helgi** [comment]
This only touches provisioning and not updating - No auto thing happening there.

**Comment by carmstrong** [comment]
> This only touches provisioning and not updating

Don't we call `gen-json.py` from within [update-aws-cluster.sh](https://github.com/deis/deis/blob/master/contrib/aws/update-aws-cluster.sh#L35)?

**Comment by helgi** [comment]
Sigh, yeah, brain-fart. Easily resolved. Commit coming

**Comment by helgi** [comment]
Added in a flag for now that tells the template generator if it is in update mode or not.

**Comment by krancour** [comment]
It might be better to apply the same fix to all the different provisioners.  As is, this introduces a feature / safeguard into the AWS provisioner that isn't included in the others.  This puts the burden of that knowledge on the users or perhaps upon rigger.  Longer term, we will be doing ourselves a big favor if we improve overall consistency of use and behavior among each of those.  The result will be the establishment of a defacto interface and spec for any provisioner rigger utilizes.

**Comment by helgi** [comment]
I had this one ready so I threw it in - haven't looked at the other providers. Could have a look when I'm done with my current tickets and see how easy that would be to do.

**Comment by krancour** [comment]
Ok.  I know this feature you're adding is a nice convenience, but let's hold until we can add it for all the provisioners just so we're not adding inconsistencies to the provisioning landscape.

**Comment by carmstrong** [comment]
> but let's hold until we can add it for all the provisioners

Should we close this and file an issue tracking that?

**Comment by mboersma** [comment]
@helgi do you think this could be brought over the finish line in the next week or two so it can go in the Deis v1 LTS release? I know you're busy with Deis v2 tasks, so if this isn't on your near-term roadmap we may want to close it.

**Pull request closed without merging**
