### PR TITLE
chore(*): bump CoreOS to 835.10.0

### PR DESCRIPTION
**Pull request by carmstrong**
https://coreos.com/releases/#835.10.0

### CODE REVIEW

**Comment by bacongobbler** [comment]
looks like a flake8 issue. ping @helgi

**Comment by helgi** [comment]
Oh yeah, it's not the only failure but I did see the same thing in deis/workflow - solution is to move the `and` statements to the previous line but nothing else

**Comment by mboersma** [comment]
The linting error is fixed in #4861, so after that is merged we can rebase this and it should be good.

**Comment by carmstrong** [comment]
CoreOS 835.11.0 is out. Will open a new PR once #4861 is merged to fix the style errors.

**Pull request closed without merging**
