### PR TITLE
chore(database): bump confd to v0.8

### PR DESCRIPTION
**Pull request by bacongobbler**

### CODE REVIEW

**Comment by aledbf** [comment]
Code LGTM.

**Comment by mboersma** [comment]
We still see this in the func test:
```
--- Run deisci/database:jenkins-test-ec2-232 at 10.0.1.15:60807
Error response from daemon: No such container: deis-database-jenkins-test-ec2-232
2015-03-24T19:16:03Z 9a747194c2a8 confd[49]: WARNING Skipping confd config file.
2015-03-24T19:16:03Z 9a747194c2a8 confd[49]: ERROR exit status 127
2015-03-24T19:16:03Z 9a747194c2a8 confd[49]: ERROR exit status 127
database: waiting for confd to write initial templates...
2015-03-24T19:16:08Z 9a747194c2a8 confd[72]: WARNING Skipping confd config file.
database: no existing database found.
database: no backups found. Initializing a new database...
2015-03-24T19:16:08Z 9a747194c2a8 confd[87]: WARNING Skipping confd config file.
```
I was hoping we would be free of the ERROR messages...

**Comment by bacongobbler** [comment]
Hmm, I wonder if that's due to `/usr/local/bin/reload` failing somewhere. I'll check by flipping on `--debug` before running the functional tests locally.

**Comment by bacongobbler** [comment]
Yep:

```
2015-03-24T22:10:21Z 981fdc768375 confd[48]: DEBUG Running /usr/local/bin/reload
2015-03-24T22:10:21Z 981fdc768375 confd[48]: ERROR exit status 127
```

So technically we're bug-compatible with this PR. I'll take a look into it, but it seems like the database isn't running at the time when `reload` is run:

```
2015-03-24T22:10:21Z 981fdc768375 confd[48]: DEBUG "psql: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?\n"
```

**Comment by mboersma** [comment]
> So technically we're bug-compatible with this PR

Makes sense to me. Code LGTM.

**Pull request merged**
