### PR TITLE
docs(installing_deis): Add parameter description about publicDomainName.

### PR DESCRIPTION
**Pull request by monaka**
All deployments will be failed if publicDomainName was brank.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

**Comment by monaka** [comment]
This will fix #4854

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by bacongobbler** [comment]
The test failure was due to an unrelated change which has been fixed in master. Merging!

**Pull request merged**
