### PR TITLE
feat(tests): use m3.medium instances for ec2 integration tests

### PR DESCRIPTION
**Pull request by mboersma**
This change [modifies `cloudformation.json`](http://docs.deis.io/en/latest/installing_deis/aws/#customize-cloudformation-json) temporarily to use `m3.medium` instances during integration tests. If it works reliably, we can reduce our EC2 charges for [CI](https://ci.deis.io/). :moneybag: 

screen shot 2015-03-27 at 12 53 17 pm

Deis still recommends (and defaults to) `m3.large` instances on EC2.

### CODE REVIEW

**Comment by bacongobbler** [comment]
Okay, let's keep this as a trial run since it's just test infra. Previous experience when we lowered our vagrant instances down to 2GB per VM doesn't inspire me, but less :moneybag: spent on test infra is nice.

**Comment by bacongobbler** [comment]
that's promising. Code LGTM!

**Comment by mboersma** [comment]
It's passed three times in a row, so I think this will work for tests.

**Comment by aledbf** [comment]
Code LGTM.

**Pull request merged**
