### PR TITLE
docs(logspout): Fix remote syslog example

### PR DESCRIPTION
**Pull request by theaboutbox**
A tiny tweak to the logspout readme to include the correct Docker incantation to route logs to a syslog endpoint.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
I think the better fix here would be to add this as the entrypoint for the image: https://github.com/deis/deis/blob/master/logspout/image/Dockerfile#L6

**Comment by bacongobbler** [comment]
though ^ is the better fix, we can clean that up. LGTM!

**Comment by carmstrong** [comment]
LGTM. Thanks @theaboutbox

**Comment by mboersma** [comment]
Code LGTM.

**Pull request merged**
