### PR TITLE
fix(contrib): warn if commit subject is too long

### PR DESCRIPTION
**Pull request by mboersma**
[skip ci]

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
:+1: Do we want to use yellow for warnings?

**Comment by mboersma** [comment]
Yes, I'll change it. :yellow_heart:

**Comment by bacongobbler** [comment]
LGTM. The line length was more of a guideline than an enforced rule. I'll update the docs to be less harsh. :)

**Comment by technosophos** [comment]
LGTM

**Pull request merged**
