### PR TITLE
[WIP] Deis doctor

### PR DESCRIPTION
**Pull request by michelleN**

### CODE REVIEW

**Comment by carmstrong** [comment]
This is a cool idea! Some other ideas for Deis Doctor:
* Checks all component logs to see if there are any recent errors
* Makes sure all components are actually publishing etcd keys (host/port)
* Suggests running stateless if the detected platform is AWS
* Ensures installed `deisctl` version matches platform version

**Comment by michelleN** [comment]
@carmstrong o0o0oh I really like the log checking idea.

**Comment by carmstrong** [comment]
Also, we'll want to squash these commits and rename them to follow our style guidelines. A commit like `feat(deisctl): add doctor subcommand` is probably what we'll want.

**Comment by michelleN** [comment]
sure thing.

**Comment by sgoings** [comment]
Can the `doctor` command get some unit tests too? :pray:

**Comment by mboersma** [comment]
@michelleN do you think this could be brought over the finish line in the next week or two so it can go in the Deis v1 LTS release? I know you're busy with [`helm`](https://github.com/helm/helm) and other tasks, so if this isn't on your near-term roadmap we may want to close it.

**Comment by michelleN** [comment]
@mboersma I'd be happy to work on it, but let me make sure that it's okay with @technosophos. :)

**Pull request closed without merging**
