### PR TITLE
chore(controller): No sudo for deis

### PR DESCRIPTION
**Pull request by johanneswuerbach**
The deis user does not need sudo

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Updated to be less invasive.

//cc @bacongobbler as you merged the builder sudo refactor (https://github.com/deis/deis/pull/2875).

**Comment by bacongobbler** [comment]
yeah I guess we just require sudo now to drop privileges over to the deis user in bin/boot. Code LGTM.

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by mboersma** [comment]
Code LGTM.

**Pull request merged**
