### PR TITLE
[WIP] feat(client): laziness option for config:push

### PR DESCRIPTION
**Pull request by klpx**
add laziness option for fast config apply (do not create new release if pushing same config)

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by klpx** [comment]
Hi! I created this PR for just showing idea. If you agree i will test it and will fix docs

**Comment by bacongobbler** [comment]
Hey @klpx, there's actually a server-side validation that if you push the same config, a 409 conflict is returned saying that config was unchanged.

**Comment by bacongobbler** [comment]
@klpx ping. Does this resolve anything that the above does not solve or are you running an older version of Deis?

**Comment by bacongobbler** [comment]
closing this PR due to inactivity/response from OP, but please re-open if you feel https://github.com/deis/deis/pull/5094#issuecomment-245307156 is inadequate and we can chat about alternatives. :)

**Pull request closed without merging**
