### PR TITLE
feat(contrib/ec2): allow easier selection of CoreOS version

### PR DESCRIPTION
**Pull request by fabiob**
This change allows an AWS user to quickly switch the CoreOS
version of the CloudFormation template. Should also help
reduce the work needed by Deis maintainers.

### CODE REVIEW

**Comment by carmstrong** [comment]
@fabiob This is much appreciated! Code LGTM!

**Comment by bacongobbler** [comment]
this will definitely make maintenance much easier on us. Code LGTM.

**Comment by mboersma** [comment]
Somehow this created a template format error when provisioning in CI:
```
>>> Provisioning 3-node CoreOS <<<

sed -e "s,# discovery:,discovery:," -e "s,discovery: https://discovery.etcd.io/.*,discovery: $(curl -s -w '\n' https://discovery.etcd.io/new)," contrib/coreos/user-data.example > contrib/coreos/user-data
Creating CloudFormation stack deis-test-c83022a01b

A client error (ValidationError) occurred when calling the CreateStack operation: Template format error: Every Mappings member CoreOSAMIs must be a map

>>> Error detected, dumping logs <<<
```

**Comment by fabiob** [comment]
Will check.

**Comment by fabiob** [comment]
Should be fixed now.

**Comment by mboersma** [comment]
Tested manually with combinations of `COREOS_CHANNEL=foo COREOS_VERSION=bar`. This works great for EC2. 

If you supply an invalid combination of channel + version, you get a JSON decode error, so we could make that more user-friendly with something like this:
```python
url = "http://{channel}.release.core-os.net/amd64-usr/{version}/coreos_production_ami_all.json".format(**args)
try:
    amis = json.load(urllib.urlopen(url))
except ValueError:
    print "The URL {} is invalid.".format(url)
    raise
```

**Comment by carmstrong** [comment]
Replaced by #4086

**Pull request closed without merging**
