### PR TITLE
chore(builder): bump heroku-buildpack-ruby to v134

### PR DESCRIPTION
**Pull request by bacongobbler**
rebased #3267 off master

### CODE REVIEW

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
I think there's an issue with loading up the cedarish tarball: https://github.com/deis/deis/pull/3267#issuecomment-78432014

Looking into using `docker load` instead as per the cedarish docs: https://github.com/progrium/cedarish/#releases

**Comment by bacongobbler** [comment]
manually tested this PR. builder's up and running again with v134 of heroku-buildpack-ruby.

**Comment by mboersma** [comment]
Tested manually with [example-ruby-sinatra](https://github.com/deis/example-ruby-sinatra) and vagrant `test-integration.sh`. LGTM.

**Comment by bacongobbler** [comment]
yeah the custom buildpack test should be disabled when DEIS_TEST_APP is not example-go, or the buildpack test can be made to be smarter than that but that's another time, another PR

**Comment by mboersma** [comment]
> that's another time, another PR

Yes it is. I will create an issue for that. This PR is good to go.

**Pull request merged**
