### PR TITLE
feat(builder): use a constant mtime to avoid breaking docker's ADD & COPY cache

### PR DESCRIPTION
**Pull request by mhahn**
As @dbrock pointed out in #1334, this preserves the docker cache for ADD
and COPY statements by not updating the mtime each time we archive the
repository.

### CODE REVIEW

**Comment by mboersma** [comment]
I see these warnings during the test run:
```
remote: Gtar: Dockerfile: time stamp 2015-02-20 21:47:05 is 0.028930016 s in the future
remote: Gtar: README.md: time stamp 2015-02-20 21:47:05 is 0.022249633 s in the future
```
Looks like it's not causing any problems, but I can't tell if caching is working by reading the test logs. Need to test this by hand.

**Comment by carmstrong** [comment]
Does `-m` help us here instead of setting to a specific date?
```
-m, --touch
don't extract file modified time
```

**Comment by bacongobbler** [comment]
yeah I'd imagine that stripping the modified time *might* be the right solution

**Comment by carmstrong** [comment]
> Does -m to tar help us here instead of setting to a specific date?

@mhahn What do you think?

**Comment by mhahn** [comment]
The current code is using `-m` and isn't working. Reading through the tar docs, it seems like that would be the solution, but from manual testing that doesn't work.

It does seem very hacky to set the time to some arbitrary value each time and could cause confusion/future issues. I think just waiting for something like this: https://github.com/docker/docker/issues/4351 and being able to support those parameters when building the images would be a better solution.

**Comment by bacongobbler** [comment]
This works for me. I didn't see the error @mboersma saw while testing:

```
><> git push deis master
-----> Building Docker image
remote: build context to Docker daemon 5.632 kB
remote: build context to Docker daemon
Step 0 : FROM centos:latest
 ---> 88f9454e60dd
Step 1 : MAINTAINER OpDemand <info@opdemand.com>
 ---> Using cache
 ---> 178236a3b415
Step 2 : COPY index.html /app/index.html
 ---> 17b88f073200
Removing intermediate container d4bd7f509837
Step 3 : WORKDIR /app
 ---> Running in 4e2c176f553a
 ---> eb426b2ab98e
Removing intermediate container 4e2c176f553a
Step 4 : CMD python -m SimpleHTTPServer 5000
 ---> Running in 27d1fe652fd2
 ---> 1b3f4b772920
Removing intermediate container 27d1fe652fd2
Step 5 : EXPOSE 5000
 ---> Running in 5b920c1cd125
 ---> 6681c820fc1b
Removing intermediate container 5b920c1cd125
Step 6 : ENV GIT_SHA 9910fe576e089913cf363d08df612d1373efd614
 ---> Running in a00c3c7632e8
 ---> 614e56868830
Removing intermediate container a00c3c7632e8
Successfully built 614e56868830
-----> Pushing image to private registry

-----> Launching...
       done, py:v4 deployed to Deis

       http://py.104.130.74.254.xip.io

       To learn more, use `deis help` or visit http://deis.io

To ssh://git@deis.104.130.74.254.xip.io:2222/py.git
   12e9873..9910fe5  master -> master
><> git ci --allow-empty -m 'hi'
[master 34a36e0] hi
><> git push deis master
Counting objects: 1, done.
Writing objects: 100% (1/1), 181 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)

-----> Building Docker image
remote: build context to Docker daemon 5.632 kB
remote: build context to Docker daemon
Step 0 : FROM centos:latest
 ---> 88f9454e60dd
Step 1 : MAINTAINER OpDemand <info@opdemand.com>
 ---> Using cache
 ---> 178236a3b415
Step 2 : COPY index.html /app/index.html
 ---> Using cache
 ---> 17b88f073200
Step 3 : WORKDIR /app
 ---> Using cache
 ---> eb426b2ab98e
Step 4 : CMD python -m SimpleHTTPServer 5000
 ---> Using cache
 ---> 1b3f4b772920
Step 5 : EXPOSE 5000
 ---> Using cache
 ---> 6681c820fc1b
Step 6 : ENV GIT_SHA 34a36e05c79f354e14e2358e0a72bf79124d0308
 ---> Running in 04446d9209b2
 ---> 58c8792639e7
Removing intermediate container 04446d9209b2
Successfully built 58c8792639e7
-----> Pushing image to private registry

-----> Launching...
```

My Dockerfile:

```
FROM centos:latest
MAINTAINER OpDemand <info@opdemand.com>

COPY index.html /app/index.html
WORKDIR /app
CMD python -m SimpleHTTPServer 5000
EXPOSE 5000
```

**Comment by carmstrong** [comment]
> It does seem very hacky to set the time to some arbitrary value each time and could cause confusion/future issues. I think just waiting for something like this: docker/docker#4351 and being able to support those parameters when building the images would be a better solution.

I'd tend to agree.

**Pull request closed without merging**
