### PR TITLE
checkout submodules present in custom buildpacks

### PR DESCRIPTION
**Pull request by lanej**

### CODE REVIEW

**Comment by lanej** [comment]
custom buildpacks like https://github.com/cloudfoundry/ruby-buildpack rely on pulling in external submodules

**Comment by bacongobbler** [comment]
Hmm... Won't this break buildpacks without submodules or is it a no-op? I guess Jenkins will tell us the answer ;)

**Comment by carmstrong** [comment]
Another implementation: #4417

**Comment by lanej** [comment]
@bacongobbler no-ops when submodules are not present.

**Comment by Joshua-Anderson** [comment]
@carmstrong #4117 pulls submodules in apps. This pulls submodules present in buildpacks and is a simpler change

**Comment by carmstrong** [comment]
Good fix, @lanej. Could you amend your commit so it follows our [commit style guidelines](http://docs.deis.io/en/latest/contributing/standards/#commit-style)? Something like `feat(builder): support submodules in buildpacks` would work well. Thanks!

**Comment by lanej** [comment]
@carmstrong updated.

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by carmstrong** [comment]
Kicked off a new test run: https://ci.deis.io/job/test-ec2/3108/

**Comment by mboersma** [comment]
This looks good, but I'm testing this manually just to ensure it doesn't have any unintended side effects.

**Comment by mboersma** [comment]
LGTM.

**Pull request merged**
