### PR TITLE
fix(builder): return error message as string

### LINKED ISSUE #2883: builder not displaying underlying error
When the builder fails, there is no error output. it just responds with `[remote rejected] master -> master (pre-receive hook declined)` with no reason for the error. This was introduced when we refactored the builder in #2335 to start refactoring the component over to Go.

This has been seen in previous issues such as #2876 and in #1748, so a fixup would help us better determine the underlying issue.

### LINKED ISSUE #2984: ugly error on builder failing to retrieve release values
While testing an unrelated fix, the builder spewed an ugly error message. We were recently able to see builder failures with #2964, but it looks butt-ugly:

```
-----> Launching...
2015/01/28 21:40:07 failed retrieving config from controller: &{%!s(*http.body=&{0xc20800ae10 0xc2080581b0 0xc20805a3c0 true {0 0} false}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error)=0x49c0b0) %!s(func() error=0x49c040)}
To ssh://git@deis.104.236.239.206.xip.io:2222/go.git
```

### PR DESCRIPTION
**Pull request by aledbf**
This change this error message
```
2015/02/23 21:01:47 failed retrieving config from controller: &{%!s(*http.body=&{0xc20800aea0 0xc208058120 0xc208062420 true {0 0} false}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error)=0x49c0b0) %!s(func() error=0x49c040)}
```

with:
```
2015/02/23 22:43:43 failed retrieving config from controller: <h1>Server Error (500)</h1>
```

closes #2883
closes #2984 -- *edited by @bacongobbler*

### CODE REVIEW

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by bacongobbler** [comment]
@aledbf you may want to try rebasing, there were some issues fixed in master last week

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
closes #3290

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by carmstrong** [comment]
@aledbf Try rebasing this, and we'll see if it passes.

**Comment by carmstrong** [comment]
@aledbf Jenkins is failing this pretty consistently, so I think there's something wrong here.

**Comment by aledbf** [comment]
debugging this I found that the error that appears is not the correct one.
It throws `App not started (503)` but the real reason is `failed parsing config from controller` that is inside deis-builder.

```
++ /app/bin/get-app-config -url=http://172.17.8.102:8000/v1/hooks/config -key=...... -user=test -app=appssample
+ RESPONSE='failed parsing config from controller
invalid character '\''H'\'' looking for beginning of value'
To ssh://git@deis.local3.deisapp.com:2222/appssample.git
 * [new branch]      master -> master
ok
--- FAIL: TestApps (29.54s)
  itutils.go:139: App not started (503)
    Body: (<html>
    <head><title>503 Service Temporarily Unavailable</title></head>
    <body bgcolor="white">
    <center><h1>503 Service Temporarily Unavailable</h1></center>
    <hr><center>nginx/1.7.10</center>
    </body>
    </html>
    )
FAIL
exit status 1
```

**Comment by mboersma** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
nice catch there with `ParseConfig`. Code LGTM!

**Pull request merged**
