### PR TITLE
fix(deisctl): improve dock name match

### LINKED ISSUE #4205: `deisctl dock` requires full name of the container
Most other commands rely on `deis-` as a prefix. For example, `deisctl journal controller` will retrieve the logs for the `deis-controller` component. However, `deisctl dock` requires the full name:

```
$ deisctl dock controller
Excuting 'docker exec -it controller sh' on container 'controller'
FATA[0000] Error response from daemon: no such id: controller
$ deisctl dock deis-controller
Excuting 'docker exec -it deis-controller sh' on container 'deis-controller'
/app #
```

### PR DESCRIPTION
**Pull request by krancour**
Fixes #4205

### CODE REVIEW

**Comment by bacongobbler** [comment]
would you mind squashing the commits? :)

**Comment by krancour** [comment]
Oh... that's embarrassing.  That's my lazy convention for commit messages that pass the hook that I _intend_ to squash.  In this case, I forgot!

**Comment by krancour** [comment]
Fixed.

**Comment by bacongobbler** [comment]
code lgtm

**Comment by mboersma** [comment]
LGTM.

**Pull request merged**
