### PR TITLE
feat(contrib/azure/azure-coreos-cluster): add an https enddpoint on c… …reation

### PR DESCRIPTION
**Pull request by sedouard**
Adds a load balanced https endpoint on creation

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by sedouard** [comment]
@timfpark can you take a look?

**Comment by mboersma** [comment]
I don't have Azure access to test this directly, but code LGTM.

**Comment by bacongobbler** [comment]
code LGTM as well

**Pull request merged**
