### PR TITLE
fix(publisher): remove unnecessary BUILD_IMAGE variable from Makefile

### PR DESCRIPTION
**Pull request by karlo57**
I noticed that the `BUILD_IMAGE` variable is not used in the publisher `Makefile`.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by mboersma** [comment]
`BUILD_IMAGE` does appear to be unused in publisher. Thanks! Code LGTM.

**Comment by carmstrong** [comment]
Thanks @karlo57!

**Pull request merged**
