### PR TITLE
chore(deisctl): update stateless warning message

### PR DESCRIPTION
**Pull request by olalonde**
`deis logs` works using the in memory logger component

### CODE REVIEW

**Comment by krancour** [comment]
Nice catch.  I'm wondering if the line about components needing to be configured for use with external storage already describes the situation accurately.  Logs can be drained to the likes of Papertrail or Splunk for longer term archiving.  Especially considering that in-memory log storage isn't yet a default, this line is doubly true-- some configuration is required.

I think the best bet is to only remove the line about `desis logs` not working, and that would be sufficient without adding anything further.

**Comment by olalonde** [comment]
Agreed. Is that better?

> Warning: With a stateless control plane, some components require manual configuration.
> See the official Deis documentation for details on running a stateless control plane.
> http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/

**Comment by krancour** [comment]
Looks great!  Thanks for this!

**Comment by carmstrong** [comment]
Kicked off another test run. Once it passes, we should be good to merge. Thanks, @olalonde!

**Pull request merged**
