### PR TITLE
fix(contrib): fix etcd2 data directory on AWS

### LINKED ISSUE #4310: AWS provisioning process fails in 1.9.0
`gen-json.py` in the AWS provisioning process adds in some AWS-specific user-data and also modifies portions of the user-data for AWS.  In AWS, the CloudFormation templates we use specify launch configuration for CoreOS hosts wherein we mount a few EBS volumes-- among them, we mount one to `/media/etcd`.  One of the corresponding modification to the user-data is to string replace certain instances of `/var/lib/etcd2` with `/media/etcd`

See relevant lines from `gen-json.py` here:

```
# configure etcd to use its EBS volume
dump = dump.replace('-data-dir /var/lib/etcd2', '-data-dir /media/etcd')
dump = dump.replace('--volume=/var/lib/etcd2', '--volume=/media/etcd')
```

https://github.com/deis/deis/blob/master/contrib/aws/gen-json.py#L108-L109

This worked great until v1.9.0 when one of the strings that is ordinarily modified was changed in `user-data.example`.

Here's the relevant commit:

https://github.com/deis/deis/commit/ccb2f9c8ce4dc4d2589bae7ea8f3bc7e87bb315d

What this results in is user-data that's actually used that looks something like this:

```
  - name: etcd.service
    # ...
      [Service]
      # ...
      Environment="ETCD_DATA_DIR=/var/lib/etcd2"
      # ...
      ExecStart=/usr/bin/docker run --net=host --rm \
        --volume=${ETCD_DATA_DIR}:/var/lib/etcd2 \
        # ...
        -data-dir /media/etcd \
        # ...
    # ...
```

As you can see, the wrong directory on the host (should be `/media/etcd`, but is `/var/lib/etcd2`) is mounted into the wrong directory on the container (should be `/media/etcd`, but is `/var/lib/etcd2`).  The containerized etcd2, however, per `-data-dir /media/etcd` is looking for the host's `/media/etcd' to have been mounted into the container's `/media/etcd`... which isn't the case.

This _is_ definitely wrong.  The very odd part about it however, is that whatever issue this actually causes appears to be non-deterministic.  Sometimes this fails spectacularly; sometimes it _somehow_ seems to work (although I'm not sure how).

### PR DESCRIPTION
**Pull request by carmstrong**
@krancour please test this - I haven't been able to get my local environment set up for ec2 again.

closes #4310

### CODE REVIEW

**Comment by carmstrong** [comment]
This passed and is ready for review.

**Comment by mboersma** [comment]
LGTM. Tested on AWS:
```console
core@ip-10-21-2-198 ~ $ ps aux | grep etcd
etcd       682  0.0  0.1 204856 12804 ?        Ssl  14:35   0:00 /usr/bin/docker run --net=host --rm --volume=/media/etcd:/var/lib/etcd2 --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro -p 4001:4001 -p 2380:2380 -p 2379:2379 -p 7001:7001 --name 697da931b78149bbae8e4dea26f2b84a quay.io/coreos/etcd:v2.1.1 -name 697da931b78149bbae8e4dea26f2b84a -data-dir /var/lib/etcd2 -advertise-client-urls http://10.21.2.198:2379,http://10.21.2.198:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls http://10.21.2.198:2380,http://10.21.2.198:7001 -listen-peer-urls http://0.0.0.0:2380,http://0.0.0.0:7001 --heartbeat-interval 400 --election-timeout 2000 --discovery https://discovery.etcd.io/701e4305913ac7fc932b4464a3236269
root       700  0.3  0.2  33376 16864 ?        Ssl  14:35   0:01 /etcd -name 697da931b78149bbae8e4dea26f2b84a -data-dir /var/lib/etcd2 -advertise-client-urls http://10.21.2.198:2379,http://10.21.2.198:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls http://10.21.2.198:2380,http://10.21.2.198:7001 -listen-peer-urls http://0.0.0.0:2380,http://0.0.0.0:7001 --heartbeat-interval 400 --election-timeout 2000 --discovery https://discovery.etcd.io/701e4305913ac7fc932b4464a3236269
core@ip-10-21-2-198 ~ $ systemctl status etcd
● etcd.service - etcd2 container
   Loaded: loaded (/etc/systemd/system/etcd.service; static; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd.service.d
           └─10-oem.conf
        /etc/systemd/system/etcd.service.d
           └─90-after-etcd-volume.conf
   Active: active (running) since Sat 2015-08-22 14:35:30 UTC; 7min ago
 Main PID: 682 (docker)
   Memory: 7.9M
   CGroup: /system.slice/etcd.service
           └─682 /usr/bin/docker run --net=host --rm --volume=/media/etcd:/var/lib/etcd2 --volume=/usr/share/ca-certificates...

Aug 22 14:35:33 ip-10-21-2-198.us-west-2.compute.internal docker[682]: 2015/08/22 14:35:33 etcdserver: added member a5ddd...fb2
Aug 22 14:35:33 ip-10-21-2-198.us-west-2.compute.internal docker[682]: 2015/08/22 14:35:33 etcdserver: added local member...fb2
Aug 22 14:35:33 ip-10-21-2-198.us-west-2.compute.internal docker[682]: 2015/08/22 14:35:33 rafthttp: the connection with ...ive
Aug 22 14:35:33 ip-10-21-2-198.us-west-2.compute.internal docker[682]: 2015/08/22 14:35:33 rafthttp: the connection with ...ive
Aug 22 14:35:36 ip-10-21-2-198.us-west-2.compute.internal docker[682]: 2015/08/22 14:35:36 raft: b47c0ac71d96645e [term: ... 2]
Aug 22 14:35:36 ip-10-21-2-198.us-west-2.compute.internal docker[682]: 2015/08/22 14:35:36 raft: b47c0ac71d96645e became ...m 2
Aug 22 14:35:36 ip-10-21-2-198.us-west-2.compute.internal docker[682]: 2015/08/22 14:35:36 raft: b47c0ac71d96645e [logter...m 2
Aug 22 14:35:36 ip-10-21-2-198.us-west-2.compute.internal docker[682]: 2015/08/22 14:35:36 raft: raft.node: b47c0ac71d966...m 2
Aug 22 14:35:36 ip-10-21-2-198.us-west-2.compute.internal docker[682]: 2015/08/22 14:35:36 etcdserver: published {Name:69...fb2
Aug 22 14:35:36 ip-10-21-2-198.us-west-2.compute.internal docker[682]: 2015/08/22 14:35:36 etcdserver: set the initial cl...1.0
Hint: Some lines were ellipsized, use -l to show in full.
```
I also installed the v1.9.0 platform and did some basic tests.

**Comment by bacongobbler** [comment]
code LGTM

**Comment by krancour** [comment]
LGTM

**Comment by krancour** [comment]
@carmstrong thanks for doing this.  Were there possibly spots in any of the other providers' provisioners that may have needed the same love?

**Comment by carmstrong** [comment]
> Were there possibly spots in any of the other providers' provisioners that may have needed the same love?

I checked them all and this seemed to be the only place we're using an external volume for etcd, but it could always use another set of eyes!

**Pull request merged**
