### PR TITLE
feat(router): use new reuseport option

### PR DESCRIPTION
**Pull request by aledbf**
http://nginx.com/blog/socket-sharding-nginx-release-1-9-1/

### CODE REVIEW

**Comment by carmstrong** [comment]
@aledbf What does this change mean? Is there anything we should look out for, or potential issues from this?

**Comment by aledbf** [comment]
This should be a transparent update. 
We should see less latency per request in when the cluster is under high loads.

**Comment by kalbasit** [comment]
The benchmark looks quite amazing. :+1:

**Comment by carmstrong** [comment]
@aledbf Could you rebase this? @Joshua-Anderson's commit to retry pushes to DockerHub should hopefully help.

**Comment by aledbf** [comment]
@carmstrong done. The problem was that the directive `reuseport` must be specified only once and in the default server.

**Comment by carmstrong** [comment]
We should probably split out the nginx bump commit so it's not hidden.

**Comment by mboersma** [comment]
Code LGTM.

**Comment by carmstrong** [comment]
Code LGTM. Thanks @aledbf!

**Pull request merged**
