### PR TITLE
docs(MAINTAINERS): add Kent Rancourt as a core maintainer

### PR DESCRIPTION
**Pull request by carmstrong**

### CODE REVIEW

**Comment by mboersma** [comment]
LGTM.

**Comment by krancour** [comment]
LGTM :smile:

**Comment by carmstrong** [comment]
> LGTM

Technically that doesn't count until this PR is merged... ;)

**Comment by carmstrong** [comment]
I killed the build so we're not wasting resources to test this beyond docs.

**Comment by mboersma** [comment]
Since it's a markdown file, it's not even touched by docs tests. So let's merge this.

**Pull request merged**
