### PR TITLE
feat(publisher): remove application when is stopped

### LINKED ISSUE #3176: stop publishing an app to etcd when container is stopped
see discussion in #2044

### PR DESCRIPTION
**Pull request by aledbf**
The reason of `/deis/publisher/containers/<id container> -> <app name>/<app type instance>` is required because in the docker stop event only the id of the stopped container is available.

closes #3176

### CODE REVIEW

**Comment by bacongobbler** [comment]
Personally I'd rather keep the IDs in an in-memory map as it's a lot faster and more reliable to access than etcd. We fall back with TTLs so it's not a huge concern if the process is restarted, losing the map's data.

**Comment by aledbf** [comment]
> Personally I'd rather keep the IDs in an in-memory map

that was my first approach but I thought use etcd like in the rest of the services :)
I will change this

**Comment by bacongobbler** [comment]
code LGTM!

**Comment by mboersma** [comment]
That's great cleanup code, thanks @aledbf. Code LGTM, but this needs a manual test after CI.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by aledbf** [comment]
Jenkins, test this please.

**Comment by mboersma** [comment]
Note that this passed testing, although the way that GitHub test statuses stack now doesn't reflect that on the summary page with a green :white_check_mark:

**Comment by mboersma** [comment]
I tested this interactively on vagrant. LGTM.

**Pull request merged**
