### PR TITLE
feat(controller): add host header to healthcheck

### PR DESCRIPTION
**Pull request by pmclanahan**
re: #4585

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

**Comment by bacongobbler** [comment]
Thanks @pmclanahan! Would you mind amending your commit such that it follows the style guide as our bot pointed out? That way your commit will be fetched in the changelog when we cut a new release. Thanks! :)

**Comment by bacongobbler** [comment]
also @jgmize does have a point with https://github.com/deis/deis/issues/4585#issuecomment-146676337 -- we'll need to add the host header there as well.

**Comment by pmclanahan** [comment]
Commit message improved. And yes, @jgmize is correct, but I thought I'd go ahead and get this in since I know how to make this change. I'll look at the other as well, but I've not worked with much golang.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by bacongobbler** [comment]
Unfortunately I don't think there's a way we can get the application's URL from publisher, and I think we need to implement this in both publisher and the controller in one PR. On the plus side, health checks are handled by kubernetes for us in v2, so there is a fix in the future for this as they'll handle all this logic for us, including [HTTP and exec health checks](https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/liveness) which the healthcheck PR was originally inspired by. :)

@pmclanahan would you be okay for closing this PR in favour of v2? You can follow the docs [here](https://github.com/deis/workflow) if you want to play with v2. It's currently in alpha and we're working on a beta release.

**Comment by pmclanahan** [comment]
Sounds good. Thanks.

**Pull request closed without merging**
