### PR TITLE
feat(controller): add CONTAINER_NAME env

### PR DESCRIPTION
**Pull request by vmakhaev**
The idea is to have docker container name inside container. We need it for monitoring of our apps.

### CODE REVIEW

**Comment by deis-admin** [comment]
Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
I think you may want to take a look at the [application hostname feature](http://docs.deis.io/en/latest/customizing_deis/controller_settings/#unit-hostname) which will give you what you are describing here. Does that help?

**Comment by vmakhaev** [comment]
It solves it, thanks. Missed this part of documentation.
Btw, why we need to choose one of variants? Why not just add three different env variables? What is the idea?

**Comment by bacongobbler** [comment]
some agents like New Relice identify instances by hostname rather than a Deis-specific envvar, so for backwards compatibility we chose to do so in that fashion.

**Comment by vmakhaev** [comment]
Ok, got it. Thanks

**Pull request closed without merging**
