### PR TITLE
- Updated Sematext Agent name and Github URL

### PR DESCRIPTION
**Pull request by otisg**

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by bacongobbler** [comment]
@otisg thank you! Would you mind amending your commit to follow our [commit style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide)? That way your changes will get picked up by our release notes script when we cut the next release :)

**Comment by mboersma** [comment]
@otisg do you think you could `git commit --amend` the commit to have a subject like this?
```
docs(contrib,monitoring): update Sematext agent name and URL
```

**Comment by mboersma** [comment]
Closed by #136.

**Comment by bacongobbler** [comment]
@otisg I've gone ahead and rebased your commit in #4873 to follow our style guide as per @mboersma's guidelines. Thanks for the PR!

**Pull request closed without merging**
