### PR TITLE
fix(router): include deis.conf if no match with an SSL cert

### LINKED ISSUE #3470: SSL is broken after upgrade to 1.5.1
After upgrading deis from 1.4.1 to 1.5.1, which introduced application-level certificates (http://docs.deis.io/en/latest/using_deis/app-ssl/), my previous wildcard certificates (http://docs.deis.io/en/latest/managing_deis/ssl-endpoints/#router-ssl) no longer work. Deployed application work via http, but trying to access them via https always give 404. According to deis-router logs, it tries to route all https requests, whatever subdomain they are for, to deis-controller (in my case 192.168.0.1:8000), like:
```
Apr 13 18:15:13 staging-coreos-2 sh[5425]: [INFO] - [13/Apr/2015:18:15:13 +0000] - 46.219.37.191 - - - 301 - "HEAD / HTTP/1.1" - 183 - "-" - "curl/7.41.0" - "staging.example.com" - 192.168.0.2:49159 - staging.example.com - 0.000 - 0.000
Apr 13 18:15:23 staging-coreos-2 sh[5425]: [INFO] - [13/Apr/2015:18:15:23 +0000] - 46.219.37.191 - - - 404 - "HEAD / HTTP/1.1" - 214 - "-" - "curl/7.41.0" - "~^deis\x5C.(?<domain>.+)$" - 192.168.0.1:8000 - staging.example.com - 0.003 - 0.003
```
First request is http, seconds is https. Obviously `staging.example.com` doesn't match `^deis` wildcard, but this upstream is chosen, probably because it is first in nginx.conf.

### PR DESCRIPTION
**Pull request by bacongobbler**
The idea behind not including deis.conf was so that custom domains which
are different from the platform domain would not attach the platform SSL
certificate when it was enabled. However, this has the side effect of
not attaching domains which are subdomains of the platform domain, which
is intentional.

A better fix would be to check if the domain is a subdomain of the platform domain but text/template or confd doesn't have `strings.Contains` included as a function.

closes #3470

### CODE REVIEW

**Comment by bacongobbler** [comment]
filed kelseyhightower/confd#270 for this request

**Comment by carmstrong** [comment]
We should manually test that the catchall router-level certificate takes precedence and is applied for all domains **unless** a domain has an SSL certificate attached, in which case that certificate is served only for that domain.

**Comment by bacongobbler** [comment]
fixed:

```
><> deis info
=== go Application
{
  "updated": "2015-04-20T17:03:24UTC",
  "uuid": "c306b6e2-2192-469e-bf27-3126ed3ad6c8",
  "created": "2015-04-20T17:00:40UTC",
  "url": "go.bacongobbler.com",
  "owner": "bacongobbler",
  "id": "go",
  "structure": {
    "web": 1
  }
}

=== go Processes

--- web:
web.1 up (v2)

=== go Domains
go.23.253.174.228.xip.io
www.bacongobbler.com
foo.fishworks.io
><> deis certs
Common Name       Expires
----------------  ----------------------
foo.fishworks.io  2016-04-19T18:04:53UTC
```

Output of nginx.conf in the routers (only showing the relevant parts): https://gist.github.com/bacongobbler/28f61e38e16474ab9127

Note that every domain except for `foo.fishworks.io` is relying on the default deis.conf, whereas `foo.fishworks.io` is using app SSL.

**Comment by mboersma** [comment]
Code LGTM.

**Comment by carmstrong** [comment]
```console
$ openssl s_client -connect foo.fishworks.io:443
CONNECTED(00000003)
depth=0 /C=CA/ST=British-Columbia/L=Vancouver/O=Fishworks Development and Consulting/CN=*.bacongobbler.com/emailAddress=matthewf@fishworks.io
verify error:num=18:self signed certificate
verify return:1
depth=0 /C=CA/ST=British-Columbia/L=Vancouver/O=Fishworks Development and Consulting/CN=*.bacongobbler.com/emailAddress=matthewf@fishworks.io
verify return:1
---
Certificate chain
 0 s:/C=CA/ST=British-Columbia/L=Vancouver/O=Fishworks Development and Consulting/CN=*.bacongobbler.com/emailAddress=matthewf@fishworks.io
   i:/C=CA/ST=British-Columbia/L=Vancouver/O=Fishworks Development and Consulting/CN=*.bacongobbler.com/emailAddress=matthewf@fishworks.io
---
```

Looks to me like `foo.fishworks.io` is using the wildcard certificate?

**Comment by bacongobbler** [comment]
I see that too when using the openssl client...

```
><> openssl s_client -connect foo.fishworks.io:443
CONNECTED(00000003)
depth=0 /C=CA/ST=British-Columbia/L=Vancouver/O=Fishworks Development and Consulting/CN=*.bacongobbler.com/emailAddress=matthewf@fishworks.io
```

but when I use Chrome:

screen shot 2015-04-20 at 3 11 24 pm

Same for Safari, which I **never** use:

screen shot 2015-04-20 at 3 12 50 pm

Is there something I'm doing wrong here?

**Comment by carmstrong** [comment]
I dunno... are you running multiple routers, some of which may not have the fix? Maybe it's the luck of the draw for a request.

**Comment by bacongobbler** [comment]
Just did a fresh deploy. All three have the same config :S

**Comment by carmstrong** [comment]
Now that I think about it, maybe `s_client` doesn't send a Host header (just connects TCP on port 443), so it makes sense that the router serves the default cert. LGTM.

**Comment by carmstrong** [comment]
https://www.sslshopper.com/ssl-checker.html#hostname=foo.fishworks.io agrees too.

**Comment by carmstrong** [comment]
This has failed twice in a row in the same place:
```
domains:add test.test-7cc8a64e6a.deis.works --app domainsample
Adding test.test-7cc8a64e6a.deis.works to domainsample...  ...  o.. done
ok
certs:add /var/lib/jenkins/jobs/test-ec2/workspace/src/github.com/deis/deis/tests/test.test-7cc8a64e6a.deis.works.cert /var/lib/jenkins/jobs/test-ec2/workspace/src/github.com/deis/deis/tests/test.test-7cc8a64e6a.deis.works.key
Adding SSL endpoint...  ... done
test.test-7cc8a64e6a.deis.works
ok
sleeping for 60 seconds until certs are generated...
ok
SIGQUIT: quit
PC=0x43ec61
```

@bacongobbler I suspect something is wrong with this PR. Can you try running the integration tests locally and see if you see the same issue?

**Comment by bacongobbler** [comment]
The common problem on Jenkins passes for me locally on both Rackspace and EC2:

```
sleeping for 60 seconds until certs are generated...
ok
Powered by Deis

certs:remove test.fishr.pw
Removing test.fishr.pw... Done.
```

**Comment by bacongobbler** [comment]
Gotta love heisenbugs :bug:

**Comment by mboersma** [comment]
Reviewed this again, plus deis/confd@4c50136a8c67a0cd020d93c015bfbb23eef934d6. Code LGTM.

**Comment by carmstrong** [comment]
:ship:

**Pull request merged**
