### PR TITLE
feat(docker): load overlay module

### LINKED ISSUE #3192: Enable OverlayFS kernel module for Docker
See https://github.com/deis/deis/issues/1678#issuecomment-77048129

### PR DESCRIPTION
**Pull request by aledbf**
closes #3192

### CODE REVIEW

**Comment by carmstrong** [comment]
It sounds like we may want to wait for [CoreOS 591](https://coreos.com/releases/#591.0.0) before enabling overlay.

**Comment by mboersma** [comment]
Code LGTM, but I agree we should wait for CoreOS 591 or later to land in stable before merging.

**Comment by mboersma** [comment]
[CoreOS 607.0.0](https://coreos.com/releases/) with Docker 1.5.0 landed in the stable channel just now. We are prepping a PR and then we can revisit this.

**Comment by carmstrong** [comment]
Closing in favor of #3319 - if we intend to enable overlayfs, we'll need to do so in concert with some filesystem changes.

**Pull request closed without merging**
