### PR TITLE
WIP: fix(logspout): Ignore events with short ID

### LINKED ISSUE #5077: logspout does not recover on container restart (V1)
I have noticed this behaviour for quite some while now but never bothered to try to debug it.

I noticed that logspout basically stops logging after service restarts (eg deploys or any other reason why new containers are booted)

Note I am on a stateless V1.13.2 cluster with CoreOS 1068.8.0 and applied fix #5074 (although I do not think that matters)
I believe I had similar issues in V1.12 (stateful cluster) but I blamed that on "deis-logspout now continuously re-discovers the logger’s connection information, should it be re-scheduled onto another host" which got released in V1.13 so I had hoped my problems would go away with V1.13.

At this point I can not tell if this is actually a new issue in V1.13; if it is related to staless vs statefull (I don't think it is by looking at the backtraces), or if it is related to newer CoreOS version, or if the problem exists for a long time already

So here is the complete scenario (complete logs: http://pastebin.com/6a6ksEE6 but I recommend you read the scenario first)

* restart logspout so it is in a working state (eg it logs attaching to nodeABC on startup for all containers)
* Restart a container (eg `deis ps:restart`)
* At the moment the old container is destroyed this gets detected; but logspout crashes
~~~
Aug 06 09:32:51 eu1-cloud-worker-01 sh[5391]: 2016/08/06 09:32:51 event: 417ba0517a81 kill
Aug 06 09:32:51 eu1-cloud-worker-01 sh[5391]: 2016/08/06 09:32:51 event: 417ba0517a81 die
Aug 06 09:32:51 eu1-cloud-worker-01 sh[5391]: 2016/08/06 09:32:51 attach: 417ba0517a81 finished
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]: panic: runtime error: slice bounds out of range
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]: goroutine 84 [running]:
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]: main.NewAttachManager.func1(0xc82009a180, 0xc820011160)
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]:         /home/jenkins/workspace/test-acceptance/src/github.com/deis/deis/logspout/attacher.go:35 +0x3f0
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]: created by main.NewAttachManager
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]:         /home/jenkins/workspace/test-acceptance/src/github.com/deis/deis/logspout/attacher.go:41 +0x313
~~~
* Logspout crashing is "okay"; it gets restarted automatically and can even attach to containers
~~~
Aug 06 09:32:52 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Unit entered failed state.
Aug 06 09:32:52 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Failed with result 'exit-code'.
Aug 06 09:32:57 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Service hold-off time over, scheduling restart.
Aug 06 09:32:57 eu1-cloud-worker-01 systemd[1]: Stopped deis-logspout.
Aug 06 09:32:57 eu1-cloud-worker-01 systemd[1]: Starting deis-logspout...
Aug 06 09:32:58 eu1-cloud-worker-01 systemd[1]: Started deis-logspout.
Aug 06 09:32:58 eu1-cloud-worker-01 sh[7052]: 2016/08/06 09:32:58 attach: 1d6a60f94ff0 deis-logspout success
Aug 06 09:32:58 eu1-cloud-worker-01 sh[7052]: 2016/08/06 09:32:58 attach: 4c745b55f30a bplpp-staging_v109.web.1 success
....
~~~
* Then the new container is started again gets detected by logspout but crashes again in similar way
~~~
Aug 06 09:33:06 eu1-cloud-worker-01 sh[7052]: 2016/08/06 09:33:06 event: 10.133.20.19 pull
Aug 06 09:33:06 eu1-cloud-worker-01 sh[7052]: 2016/08/06 09:33:06 event: 5913ff325cb6 create
Aug 06 09:33:06 eu1-cloud-worker-01 sh[7052]: 2016/08/06 09:33:06 event: 5913ff325cb6 attach
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]: panic: runtime error: slice bounds out of range
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]: goroutine 79 [running]:
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]: main.NewAttachManager.func1(0xc820086180, 0xc820010e80)
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]:         /home/jenkins/workspace/test-acceptance/src/github.com/deis/deis/logspout/attacher.go:35 +0x3f0
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]: created by main.NewAttachManager
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]:         /home/jenkins/workspace/test-acceptance/src/github.com/deis/deis/logspout/attacher.go:41 +0x313
~~~
* Ok so logspout crashes; fleet and/or systemd will handle this for us right?
~~~
Aug 06 09:33:07 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 06 09:33:07 eu1-cloud-worker-01 docker[7394]: Failed to stop container (deis-logspout): Error response from daemon: No such container: deis-logspout
Aug 06 09:33:07 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Unit entered failed state.
Aug 06 09:33:07 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Failed with result 'exit-code'.
Aug 06 09:33:12 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Service hold-off time over, scheduling restart.
Aug 06 09:33:12 eu1-cloud-worker-01 systemd[1]: Stopped deis-logspout.
Aug 06 09:33:12 eu1-cloud-worker-01 systemd[1]: Starting deis-logspout...
Aug 06 09:33:13 eu1-cloud-worker-01 systemd[1]: Started deis-logspout.
Aug 06 09:33:33 eu1-cloud-worker-01 sh[7579]: 2016/08/06 09:33:33 routing all to udp://10.133.20.195:514
Aug 06 09:33:43 eu1-cloud-worker-01 sh[7579]: 2016/08/06 09:33:43 routing all to udp://10.133.20.195:514
Aug 06 09:33:53 eu1-cloud-worker-01 sh[7579]: 2016/08/06 09:33:53 routing all to udp://10.133.20.195:514
~~~

So it did restart the service, but for some reason it did not attach to ANY containers but silently does nothing.

Note that it still listens for events and the same cycle can be repeated again. It is undeterministic if at the end it will actually have attached to containers or not

So I see 2 probably distinct bugs

A) It crashes on a container restart (this seems to be consistent and we get a stacktrace so probably quite easy to debug and solve). At minimum this will give us some missing logs during container restarts (probably the boot logs of a container which is very frustrating if that container is crashing on boot and there is no easy way to see the logs)

B) It does not seem to attach to containers on startup (this is without logs and does not happen every time, I suspect some sort of race condition in the boot sequence)

If there is anything I can do to help debug this issue (eg try out a custom logspout image) I am obviously willing to do so

### PR DESCRIPTION
**Pull request by nathansamson**
Fixes #5077 

When looking at `docker events` I suspect the culprit is network events which don't have an ID

~~~
core@eu1-cloud-worker-01 ~ $ docker events
2016-08-06T10:28:06.778797416Z container kill 33d983e95a5b5b4521135dc578891f6e113efb752adfa372169aab03609e4903 (image=10.133.20.195:5000/errbit:v3, name=errbit_v3.web.1)
2016-08-06T10:28:07.044499686Z container die 33d983e95a5b5b4521135dc578891f6e113efb752adfa372169aab03609e4903 (image=10.133.20.195:5000/errbit:v3, name=errbit_v3.web.1)
2016-08-06T10:28:07.279972839Z network disconnect db40f046c9996eaea47e48f5f1baa8260f2a1add73dba4e9f91dead80e5edf7d (container=33d983e95a5b5b4521135dc578891f6e113efb752adfa372169aab03609e4903, name=bridge, type=bridge)
2016-08-06T10:28:07.342164511Z container stop 33d983e95a5b5b4521135dc578891f6e113efb752adfa372169aab03609e4903 (image=10.133.20.195:5000/errbit:v3, name=errbit_v3.web.1)
2016-08-06T10:28:07.347894586Z container destroy 33d983e95a5b5b4521135dc578891f6e113efb752adfa372169aab03609e4903 (image=10.133.20.195:5000/errbit:v3, name=errbit_v3.web.1)
2016-08-06T10:28:22.034639984Z image pull 10.133.20.195:5000/errbit:v3 (name=10.133.20.195:5000/errbit)
2016-08-06T10:28:22.385835315Z container create ded0cee038a19e4cbc4ca01fbe158c33208696ff6290117a9a9786a7f11bd957 (image=10.133.20.195:5000/errbit:v3, name=errbit_v3.web.1)
2016-08-06T10:28:22.392269189Z container attach ded0cee038a19e4cbc4ca01fbe158c33208696ff6290117a9a9786a7f11bd957 (name=errbit_v3.web.1, image=10.133.20.195:5000/errbit:v3)
2016-08-06T10:28:22.562040399Z network connect db40f046c9996eaea47e48f5f1baa8260f2a1add73dba4e9f91dead80e5edf7d (type=bridge, container=ded0cee038a19e4cbc4ca01fbe158c33208696ff6290117a9a9786a7f11bd957, name=bridge)
2016-08-06T10:28:22.563538052Z container start ded0cee038a19e4cbc4ca01fbe158c33208696ff6290117a9a9786a7f11bd957 (image=10.133.20.195:5000/errbit:v3, name=errbit_v3.web.1)
2016-08-06T10:28:22.789350097Z container attach ded0cee038a19e4cbc4ca01fbe158c33208696ff6290117a9a9786a7f11bd957 (image=10.133.20.195:5000/errbit:v3, name=errbit_v3.web.1)
~~~

~~~
Aug 06 10:28:22 eu1-cloud-worker-01 sh[29275]: 2016/08/06 10:28:22 event: 10.133.20.19 pull
Aug 06 10:28:22 eu1-cloud-worker-01 sh[29275]: 2016/08/06 10:28:22 event: ded0cee038a1 create
Aug 06 10:28:22 eu1-cloud-worker-01 sh[29275]: 2016/08/06 10:28:22 event: ded0cee038a1 attach
Aug 06 10:28:22 eu1-cloud-worker-01 sh[29275]: 2016/08/06 10:28:22 event: (ignored msgID is unknown)
Aug 06 10:28:22 eu1-cloud-worker-01 sh[29275]: 2016/08/06 10:28:22 event: ded0cee038a1 start
Aug 06 10:28:22 eu1-cloud-worker-01 sh[29275]: 2016/08/06 10:28:22 attach: ded0cee038a1 errbit_v3.web.1 success
Aug 06 10:28:22 eu1-cloud-worker-01 sh[29275]: 2016/08/06 10:28:22 event: ded0cee038a1 attach
Aug 06 10:28:30 eu1-cloud-worker-01 sh[29275]: 2016/08/06 10:28:30 routing all to udp://10.133.20.195:514
~~~

### CODE REVIEW

**Comment by bacongobbler** [comment]
This does indeed seem like the issue.

**Comment by mboersma** [comment]
This looks like a good fix. I'm going to test it first.

**Comment by bacongobbler** [comment]
Would you mind applying the same change to line 12 as well?

**Comment by nathansamson** [comment]
@bacongobbler  Are you referring to line 29?

~~~
	for _, listing := range containers {
		m.attach(listing.ID[:12])
}
~~~

I don't believe it is necessary there because you are listing containers, and I would say containers would have an ID longer than 12 characters, just not the all the docker events (which sometimes are not related to a container apparantly)

If you still believe I need to do so I am willing to oblige, just don't fully understand the reason

**Comment by nathansamson** [comment]
Although to fix part B) of #5077 I am thinking of doing a sanity check and count that at least one container exists (as per definition logspout itself should be listed)

I believe this might solve the race condition that on startup no containers are attached to, and a proper restart will be forced

Ideas or objections about that one?

**Comment by bacongobbler** [comment]
Yeah it was just more of an idea to fix your second issue. To be frank this code originally came from [another project](https://github.com/gliderlabs/logspout) so the reasoning/logic behind the 12 character length changes are beyond me, especially since we no longer use logspout in v2.

**Comment by nathansamson** [comment]
@bacongobbler I believe the 12 length IDs are what generally is displayed in docker ps and other logging usages.

So my proposal is actually to use the full ID internally (in the offchance there would be a collision) and indeed only log the short variant (maybe including the name as well) as this is what users generally are customed to and probably displays more nicely in most terninals anyway.

I will have a stab at this tomorrow

**Comment by nathansamson** [comment]
Refactored the code a bit, nothing extraordinary.

So my scenario for trying to debug the second problem (not attaching to containers on boot) I tried the following

A) (on CoreOS-) `docker exec -it deis-logspout sh`
B) (Locally) deis ps:restart (which will generally / always schedule the app to the same node)
C) In the docker containre (shell opened in step A) `kill -15 1` (ensuring that logspout crashes during startup of a process)

In all of the cases (tried 10 times or so) logspout correctly logged that it was attaching to containers on bootup.

In one case I noted the app I was restarting was not in the original list; but also no event was generated once it restarted.

I tried restarting the app again (without killing logspout this time) while monitoring `docker events` as well. Logspout did not log anything about events or attaching; and in fact also did not log anything about this app.
`docker events` showed the events I was expected

Marked as WIP as I want to get to the bottom of this but off for the night at the moment

**Comment by nathansamson** [comment]
I believe my problem that not all events are picked up might be fixed with https://github.com/fsouza/go-dockerclient/pull/206 which was fixed beginning 2015. Our copy of go dockerclient is from late 2014.

Anyone opposes to updating this depency? I feel it might fix a few silent errors we are seeing now...

**Comment by mboersma** [comment]
2014? I think refreshing go-dockerclient would be well worth a try.

**Comment by nathansamson** [comment]
@mboersma I am a bit stuck on updating this.

`godep update github.com/fsouza/go-dockerclient `

worked (although I already had trouble with that) but then the copy of docker opts was out of date ( I got some compilation errots) but I was not able to update that one (just said something like "can not update")

Any ideas? (When I am back on my other computer I can give the exact error messages)

**Comment by mboersma** [comment]
> Any ideas?

Not immediately--go vendoring is a pain (even with `glide`, the best tool). I'll take a look and see if I can get it udpated.

**Comment by mboersma** [comment]
Trying to update just `fsouza/go-dockerclient` is also giving me fits. And even if I throw in the towel and allow `godep` to re-vendor all of docker's stuff, it doesn't work cleanly and won't compile.

**Comment by nathansamson** [comment]
@mboersma maybe we should leave that out? It is obviously not a problem that often (and if it is it is a longstanding bug).

My fix already fixes part of the problem and I believe would already be good to merge on its own.

I propose creating a seperate bug for the dockerclient updating, and maybe someone (me, you or someone else) picks it up in a few weeks / months...


How do you revendor everything? I might have another go (pun not intended) at this later but totally unsure how to work with godep...

**Comment by mboersma** [comment]
> How do you revendor everything?

With `godep` you want to update individual packages in your `$GOPATH` and then `godep save ./...` to make it re-vendor them from `$GOPATH` into `Godeps/_workspace`. But that's not working for me here on my linux box--it complains endlessly about this or that package missing.

**Comment by mboersma** [comment]
> I propose creating a separate bug for the dockerclient updating...

See #5083.

**Comment by dmcnaught** [comment]
Thanks for this @nathansamson - fixed an issue I was seeing running logspout:

```bash
2017/01/03 11:57:16 loading and persisting routes in /var/lib/logspout
2017/01/03 11:57:16 logspout serving http on :8000
panic: runtime error: slice bounds out of range

goroutine 92 [running]:
main.NewAttachManager.func1(0xc8200750e0, 0xc820013e80)
	/home/runner/workspace/src/github.com/welltok/splunkspout/attacher.go:35 +0x3f0
created by main.NewAttachManager
	/home/runner/workspace/src/github.com/welltok/splunkspout/attacher.go:41 +0x326
```

**Pull request merged**
