### PR TITLE
ref(builder): push deis/slugrunner in the background

### PR DESCRIPTION
**Pull request by bacongobbler**
We shouldn't have to wait however long it takes for deis/slugrunner to
be pushed to the registry in order to start serving requests. This is
just an optimization so that the first `git push` with a heroku buildpack
will not have to push the entire cedar stack, though if someone is using
the Dockerfile workflow then this optimization is more of a bane than a
boon.

refs #3395

### CODE REVIEW

**Comment by mboersma** [comment]
If this gives a useful error message when someone does a `git push` and slugrunner is still being pushed in the background, I think it's a better UX overall.

**Comment by aledbf** [comment]
@bacongobbler maybe I'm not clear with the idea in 3395.

I want to download a tgz from s3 that contains the `slugbuilder` and `slugrunner` directly to the registry. 
Not using the builder at all. Not even docker load/push or anything like that.
(something like the cedarish tar download but from the registry)

**Comment by mboersma** [comment]
Unfortunately this failed when I set `DEIS_TEST_APP=example-java-jetty` (the default app doesn't use buildpacks):
```console
-----> Building Docker image
	error at command wait
--- FAIL: TestApps (573.15s)
	itutils.go:288: exit status 1
FAIL
exit status 1
FAIL	github.com/deis/deis/tests	573.192s
godep: go exit status 1
make[1]: *** [test-full] Error 1
make[1]: Leaving directory `/home/jenkins/workspace/test-integration/src/github.com/deis/deis/tests'
make: *** [test-integration] Error 2

>>> Error detected, dumping logs <<<
...

Apr 13 15:08:47 deis-03 sh[3006]: dd795ea47d19: Pushing
Apr 13 15:08:54 deis-03 sh[3006]: dd795ea47d19: Buffering to disk
Apr 13 15:08:55 deis-03 sh[3006]: dd795ea47d19: Image successfully pushed
Apr 13 15:08:55 deis-03 sh[3006]: e1e370efd2a8: Pushing
Apr 13 15:08:59 deis-03 sh[3006]: e1e370efd2a8: Buffering to disk
Apr 13 15:09:00 deis-03 sh[3006]: e1e370efd2a8: Image successfully pushed
Apr 13 15:09:00 deis-03 sh[3006]: fc74463dd1f8: Pushing
Apr 13 15:09:05 deis-03 sh[3006]: fc74463dd1f8: Buffering to disk
Apr 13 15:09:06 deis-03 sh[3006]: fc74463dd1f8: Image successfully pushed
Apr 13 15:09:06 deis-03 sh[3006]: Pushing tag for rev [fc74463dd1f8] on {http://172.17.8.102:5000/v1/repositories/deis/slugrunner/tags/latest}
Apr 13 15:09:07 deis-03 sh[3006]: time="2015-04-13T15:09:07Z" level="info" msg="-job push(172.17.8.102:5000/deis/slugrunner) = OK (0)"
Apr 13 15:10:52 deis-03 sh[3006]: HTTP code 409 while uploading metadata: {"error": "Cannot set this image checksum"}
Apr 13 15:10:52 deis-03 sh[3006]: time="2015-04-13T15:10:52Z" level="info" msg="-job push(172.17.8.102:5000/appssample) = ERR (1)"
Apr 13 15:10:52 deis-03 sh[3006]: Received disconnect from 172.17.8.101: 11: disconnected by user
```

**Comment by bacongobbler** [comment]
Ok thanks @mboersma, I'll take a look into it :)

**Comment by bacongobbler** [comment]
I hit a similar issue. I have a feeling that it was due to a timeout. I was just monitoring the process tree in the builder before it died:

```
><> git push deis master
The authenticity of host '[deis.23.253.21.152.xip.io]:2222 ([23.253.21.152]:2222)' can't be established.
ECDSA key fingerprint is d1:91:26:8a:79:b9:da:d5:cd:e5:68:a8:8e:64:2c:a7.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[deis.23.253.21.152.xip.io]:2222,[23.253.21.152]:2222' (ECDSA) to the list of known hosts.
Counting objects: 32, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (18/18), done.
Writing objects: 100% (32/32), 10.72 KiB | 0 bytes/s, done.
Total 32 (delta 9), reused 32 (delta 9)
-----> Go app detected
-----> Installing go1.2.2... done
-----> Running: godep go install -tags heroku ./...
-----> Discovering process types
       Procfile declares types -> web
-----> Compiled slug size is 1.7M

-----> Building Docker image
remote: Sending build context to Docker daemon 1.799 MB
remote: build context to Docker daemon 
Step 0 : FROM deis/slugrunner
 ---> 8fc0ec00e29d
Step 1 : RUN mkdir -p /app
 ---> Running in f75e832fa5bb
 ---> f6bf7704e2d9
Removing intermediate container f75e832fa5bb
Step 2 : WORKDIR /app
 ---> Running in ac6f126d8793
 ---> 6344cc89d4e3
Removing intermediate container ac6f126d8793
Step 3 : ENTRYPOINT /runner/init
 ---> Running in a37adde0dda9
 ---> 87f34ee87137
Removing intermediate container a37adde0dda9
Step 4 : ADD slug.tgz /app
 ---> 0d255ae8a201
Removing intermediate container d1bdcc3422a0
Step 5 : ENV GIT_SHA 7259e519b91cb6ab9acfec1cae8332085241b9ec
 ---> Running in 5aecd5056ccb
 ---> d0b50b9454c4
Removing intermediate container 5aecd5056ccb
Successfully built d0b50b9454c4
-----> Pushing image to private registry
To ssh://git@deis.23.253.21.152.xip.io:2222/go.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis.23.253.21.152.xip.io:2222/go.git'
```

Process tree for the most part:

```
root@ac065f9c19df:/app# ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      2005  0.3  0.1  18144  3340 ?        S    22:52   0:00 bash
root      2042  0.0  0.1  15568  2172 ?        R+   22:53   0:00  \_ ps faux
root         1  0.0  0.1  18004  3024 ?        Ss   22:42   0:00 /bin/bash /app/bin/boot
root       170  0.1  0.0   9896  1784 ?        Sl   22:43   0:00 confd -node 10.21.12.1:4001 --confdir /app --log-level error --interval 5
root       176 81.6  4.8 772252 99428 ?        Sl   22:43   7:45 docker -d --bip=172.19.42.1/16 --storage-driver=overlay --insecure-registry 10.0.0.0/8 --insecure-registry 172.16.0.0/12 --insecure-registry
root       603  0.0  0.1  17968  2784 ?        S    22:45   0:00 /bin/bash /usr/local/bin/push-images
root       616  0.1  0.5 124096 11596 ?        Sl   22:45   0:00  \_ docker push 10.21.12.3:5000/deis/slugrunner:latest
root       604  0.0  0.2  61372  5192 ?        S    22:45   0:00 /usr/sbin/sshd -D -e
root       837  0.0  0.2  88892  5436 ?        Ss   22:47   0:00  \_ sshd: git [priv]       
git        848  0.0  0.1  88892  3108 ?        S    22:47   0:00      \_ sshd: git@notty        
git        849  0.0  0.0   4448   744 ?        Ss   22:47   0:00          \_ sh -c /usr/local/bin/gitreceive run bacongobbler c7:e8:c0:2f:37:8e:e2:87:d2:7a:0c:bc:bb:2d:27:85
git        850  0.0  0.1   9556  2684 ?        S    22:47   0:00              \_ /bin/bash /usr/local/bin/gitreceive run bacongobbler c7:e8:c0:2f:37:8e:e2:87:d2:7a:0c:bc:bb:2d:27:85
git        863  0.0  0.1  23184  2492 ?        Sl   22:47   0:00                  \_ git receive-pack go.git
git        868  0.0  0.1   9528  2344 ?        S    22:47   0:00                      \_ /bin/bash hooks/pre-receive
git        870  0.0  0.1   9556  2636 ?        S    22:47   0:00                          \_ /bin/bash /usr/local/bin/gitreceive pre-receive
git        875  0.0  0.1   9568  2648 ?        S    22:47   0:00                              \_ bash /home/git/builder bacongobbler go.git 7259e519b91cb6ab9acfec1cae8332085241b9ec
git       1198  0.1  0.5 124096 11628 ?        Sl   22:47   0:00                              |   \_ docker push 10.21.12.3:5000/go:git-7259e519
git        876  0.0  0.0   9556  1832 ?        S    22:47   0:00                              \_ /bin/bash /usr/local/bin/gitreceive pre-receive
git        877  0.0  0.0  10980  1408 ?        S    22:47   0:00                                  \_ sed -u s/^/.[1G/
root      2035  0.0  0.0   4348   664 ?        S    22:52   0:00 sleep 5
```

And before the job failed, PID 603 had finished. After the failure, I tried pushing the image and noticed that a few layers still needed to be pushed:

```
root@ac065f9c19df:/app# docker push 10.21.12.3:5000/go:git-7259e519
The push refers to a repository [10.21.12.3:5000/go] (len: 1)
Sending image list
Pushing repository 10.21.12.3:5000/go (1 tags)
Image 44cd487a09bd already pushed, skipping
Image 52dc3ac34171 already pushed, skipping
Image 70b0d11fad2d already pushed, skipping
Image 423dce5daa60 already pushed, skipping
Image 30c30c9934b1 already pushed, skipping
Image 1dacbe3f6e05 already pushed, skipping
Image 2470a58be133 already pushed, skipping
Image 8647e1c10631 already pushed, skipping
Image 98e3b0e2fed4 already pushed, skipping
Image 27e3802eb861 already pushed, skipping
Image 8fc0ec00e29d already pushed, skipping
Image 14a4112c9089 already pushed, skipping
Image 66ccf2758f57 already pushed, skipping
f6bf7704e2d9: Image successfully pushed 
6344cc89d4e3: Image successfully pushed 
87f34ee87137: Image successfully pushed 
0d255ae8a201: Image successfully pushed 
d0b50b9454c4: Image successfully pushed 
Pushing tag for rev [d0b50b9454c4] on {http://10.21.12.3:5000/v1/repositories/go/tags/git-7259e519}
```

Looking closely at the actual logs in the builder, I indeed hit the same issue as you did:

```
Pushing tag for rev [8fc0ec00e29d] on {http://10.21.12.3:5000/v1/repositories/deis/slugrunner/tags/latest}
time="2015-04-22T22:53:19Z" level="info" msg="-job push(10.21.12.3:5000/deis/slugrunner) = OK (0)" 
HTTP code 409 while uploading metadata: {"error": "Cannot set this image checksum"}
time="2015-04-22T22:54:10Z" level="info" msg="-job push(10.21.12.3:5000/go) = ERR (1)" 
Received disconnect from 172.17.42.1: 11: disconnected by user
```

**Comment by bacongobbler** [comment]
Haven't looked too deep in the code, but this is the error: https://github.com/docker/docker-registry/blob/ca53d728fb57302606892362820dfaa8aed105c5/docker_registry/images.py#L245-L246

**Comment by bacongobbler** [comment]
The root issue here is https://github.com/docker/docker-registry/issues/593, so this is something that's not supported with the v1 registry. :(

**Comment by bacongobbler** [comment]
Maybe we could add some retry logic to the `docker push`? This is a pretty huge optimization to the builder, cutting down the startup time by **half**. I'd hate to see that there's no native workaround for this

**Comment by bacongobbler** [comment]
The v2 docker registry seems to be able to handle concurrent pushes. We're currently blocked from updating to that because of `deis pull`, but that would help us solve this problem:

```
docker@boot2docker:~$ docker push localhost/bacon/foo:latest
6941bfcbbfca: Image successfully pushed
41459f052977: Image successfully pushed
fd44297e2ddb: Image already exists
0ae6eb24ab7f: Image successfully pushed
```

In another terminal, pushing concurrently:

```
docker@boot2docker:~$ docker push localhost/bacon/bar:latest
6941bfcbbfca: Image successfully pushed
41459f052977: Image successfully pushed
fd44297e2ddb: Image already exists
1f7956a0c895: Image successfully pushed
```

```
docker@boot2docker:~$ docker history localhost/bacon/foo
IMAGE               CREATED             CREATED BY                                      SIZE
0ae6eb24ab7f        2 minutes ago       touch foo                                       0 B
fd44297e2ddb        36 hours ago        /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B
41459f052977        36 hours ago        /bin/sh -c #(nop) ADD file:be2a22bb15fbbbf24b   215.7 MB
6941bfcbbfca        36 hours ago        /bin/sh -c #(nop) MAINTAINER The CentOS Proje   0 B
docker@boot2docker:~$ docker history localhost/bacon/bar
IMAGE               CREATED             CREATED BY                                      SIZE
1f7956a0c895        2 minutes ago       touch bar                                       0 B
fd44297e2ddb        36 hours ago        /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B
41459f052977        36 hours ago        /bin/sh -c #(nop) ADD file:be2a22bb15fbbbf24b   215.7 MB
6941bfcbbfca        36 hours ago        /bin/sh -c #(nop) MAINTAINER The CentOS Proje   0 B
```

**Comment by bacongobbler** [comment]
closing. Will re-open as an issue to keep track of this

**Pull request closed without merging**
