### PR TITLE
chore(*): bump confd to v0.11.0

### PR DESCRIPTION
**Pull request by carmstrong**

### CODE REVIEW

**Comment by carmstrong** [comment]
This still needs an audit to ensure any commits we've made to https://github.com/deis/confd/commits/master are reflected upstream.

**Comment by bacongobbler** [comment]
looks like the change never occurred in master. I'll PR it into a fix upstream.

https://github.com/kelseyhightower/confd/compare/master...deis:73f7489

**Comment by bacongobbler** [comment]
This is blocked until https://github.com/kelseyhightower/memkv/pull/8 is merged and a new version of confd with that fix is implemented.

**Comment by mboersma** [comment]
@carmstrong @bacongobbler is this something that is fixed in [confd v0.12.0-alpha3](https://github.com/kelseyhightower/confd/releases/tag/v0.12.0-alpha3), or should we close this PR? I'm hoping to wrap this and other LTS issues up this week.

**Comment by carmstrong** [comment]
There's really no point in rocking the boat by updating confd, methinks. It really has no bearing on LTS. I'll close.

**Comment by laurrentt** [comment]
@carmstrong @bacongobbler Nooooo ! I was really looking forward for confd v0.12.0 on LTS. It fixes the incompatibility with etcd proxies https://github.com/kelseyhightower/confd/issues/319

**Comment by laurrentt** [comment]
I ended up forking and fixing deis/confd on deis-0.9.0 and deis-0.10.0. Thanks anyway !

**Pull request closed without merging**
