### PR TITLE
chore(*): bump CoreOS to 899.13.0

### LINKED ISSUE #4937: bug(ceph): do not upgrade to 4.3+ linux kernels
This is just a warning in case a stable CoreOS upgrade. 
http://tracker.ceph.com/issues/14360

### PR DESCRIPTION
**Pull request by mboersma**
Includes #4985.

Closes #4937.
Refs coreos/bugs#1092

### CODE REVIEW

**Comment by carmstrong** [comment]
One concern I have with the fix in #4985 is that it seems to be a workaround for SELinux interaction... so I want to see if it's upgrade-compatible for folks upgrading to the LTS release.

**Comment by carmstrong** [comment]
closes #4937

**Comment by mboersma** [comment]
This needs to be tested on an upgrade from v1.12.3.

**Comment by mboersma** [comment]
I've tested this on an upgrade from v1.12.3 without any issues.

**Comment by carmstrong** [comment]
> I've tested this on an upgrade from v1.12.3 without any issues.

:+1:

**Comment by jgmize** [comment]
After running CoreOS 899.13.0 + Deis 1.12.3 on a 5-node test cluster for a few days and doing some heavy load testing, we're now running that combo on 2 production clusters, with no problems so far.

**Comment by carmstrong** [comment]
> we're now running that combo on 2 production clusters, with no problems so far.

:+1:

**Pull request merged**
