### PR TITLE
fix(flannel): use default iface for starting flannel except vagrant

### LINKED ISSUE #4217: GCE provisioning fails with flannel errors
As reported on IRC, the Deis v1.9 flannel service reports "Error looking up interface eth0: no such network interface" on a newly provisioned GCE cluster. Potentially having the create-gce-user-data script remove eth0 would fix this (ens4v1 is apparently preferred).

See the [original conversation](https://botbot.me/freenode/deis/2015-08-05/?msg=46498456&page=3) for more detail.

### PR DESCRIPTION
**Pull request by kmala**
fixes #4217

### CODE REVIEW

**Comment by mboersma** [comment]
LGTM. I tested and verified this fixes things on GCE and works on vagrant.

**Comment by carmstrong** [comment]
> I tested and verified this fixes things on GCE and works on vagrant.

Thanks @mboersma. Once this passes, I'm good to merge. Code LGTM.

**Comment by rimusz** [comment]
btw this approach - quay.io/coreos/flannel:${FLANNEL_VER} /opt/bin/flanneld --ip-masq=true did not help on GCE

**Comment by carmstrong** [comment]
> did not help on GCE

Can you elaborate on what you're seeing? Is it a specific error?

**Comment by rimusz** [comment]
@carmstrong  Need to provision a new testing cluster and check errors

**Comment by rimusz** [comment]
right now even etcd does not start with that small flannel fix, tried latest stable, beta and alpha versions, still the same problem

**Comment by mboersma** [comment]
@rimusz I provisioned from master + this PR and followed our docs to install coreos-stable-647-2-0-v20150528 on GCE. I didn't see any problems and got Deis installed and working with `deisctl`. I'm doing some other tests right now but I'll try GCE again in a bit and see if I can reproduce what you ran into.

**Comment by rimusz** [comment]
@mboersma I did use the latest versions of coreos

**Comment by rimusz** [comment]
that's crazy, provisioned (fresh pull) from master + this PR and it did work this time

**Comment by carmstrong** [comment]
> and it did work this time

Well, that's good to confirm! Thank you!

**Comment by carmstrong** [comment]
@mboersma Are you good to ship?

**Comment by mboersma** [comment]
:SHIP:

**Pull request merged**
