### PR TITLE
s/deis push/deis pull/

### PR DESCRIPTION
**Pull request by sbuss**
Noticed a minor typo in the process types docs.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
nice catch. LGTM

**Comment by carmstrong** [comment]
Thanks @sbuss! Sorry for the nitpick, but could you amend your commit so it follows our style guidelines? Something like `docs(process-types): fix typo` would be great. Thanks!

**Comment by sbuss** [comment]
@carmstrong yep, no problem. Updated the commit message.

**Comment by mboersma** [comment]
Code LGTM.

**Pull request merged**
