### PR TITLE
fix(controller): return 403 when a user does not have permission

### LINKED ISSUE #2858: Some API calls return 404 instead of 403 when a user doesn't have permission
The following CLI commands will return 404 instead of 403 (as they should):
* info
* scale
* logs
* run
* destroy

Related: #2854

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #2858 

rebased off of #2898 since those are the main blockers for this change.

### CODE REVIEW

**Comment by mboersma** [comment]
This needs to be rebased, but LGTM!

**Comment by bacongobbler** [comment]
rebased

**Comment by bacongobbler** [comment]
note that the code comes straight from https://github.com/tomchristie/django-rest-framework/blob/a7567efa8d6fd008ba0a48f0e8fa7028703af386/rest_framework/mixins.py#L39-L46

**Comment by carmstrong** [comment]
:ship:

**Pull request merged**
