### PR TITLE
feat(deis client): add ssl-verify parameter to deis register command

### PR DESCRIPTION
**Pull request by rvaralda**
I've just copied and pasted from deis login command.

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by carmstrong** [comment]
I'd really like to see if we can pull this outside of these functions and make this a global flag, so we don't maintain the code in two places. Does that seem feasible?

**Comment by rvaralda** [comment]
@carmstrong where should you think put this?
I checked the deis script and found that the methods is straight called, like auth_register. (correct me if I am wrong)

Do you think to call auth method, include all these global flags, and then call its sub method like auth:register inside it?

**Comment by carmstrong** [comment]
@bacongobbler @mboersma what do you guys think? Maybe we *do* really only need this on login/register? I would have thought that we want to hook in anywhere we're building a request.

**Comment by bacongobbler** [comment]
Once you login, `ssl_verify` is read from ~/.deis/client.json so it is used for every other authenticated request. The only one that's missing are the requests which do not require authentication (in this case, anything under `/v1/auth`). I think it's only necessary on login/register :)

**Comment by carmstrong** [comment]
> We could eventually clean up some of the code in here and in register at a later date (using docopt to specify default behaviour etc.) but this LGTM.

Fair enough. Thanks @rvaralda!

**Comment by mboersma** [comment]
This slipped through with trailing whitespace that broke `make test-style`. Fixed in 0b4b5eef4b8601d4665a8cd7399e32a71ed8cad2, just noted here to justify that commit.

**Comment by bacongobbler** [comment]
Thanks @mboersma

**Comment by rvaralda** [comment]
Thanks guys

**Pull request merged**
