### PR TITLE
Use official docker/dind image

### PR DESCRIPTION
**Pull request by nathansamson**
This seems to have resolved the problems with newer CoreOS versions

### CODE REVIEW

**Comment by nathansamson** [comment]
Note I tried this with 2 buildpack applications and did not see any problems after a combined 5 deploys

When using the default image it would error out after one or 2 pushes max.

I only tested buildpacks and not docker build (as I don't use this feature myself)

**Comment by mboersma** [comment]
Awesome, thanks @nathansamson. I was considering this change to fix up #5068, although I first started by updating the `wrapdocker` script itself from jpetazzo's master (didn't work).

**Comment by mboersma** [comment]
```console
$ docker run -it --privileged dbuilder:v1.13.2 docker --version
Docker version 1.8.3, build f4bf5c7
$ docker run -it docker:1.8-dind docker --version
Docker version 1.8.3, build f4bf5c7
```

**Comment by nathansamson** [comment]
Could be closed in favor of #5074

**Comment by nathansamson** [comment]
Closing this as I believe this is not essential to the fix of the problem. Even if so, it currently is included in #5074  as well

**Pull request closed without merging**
