### PR TITLE
docs(reference): Add procfile as a option parameter to builds

### PR DESCRIPTION
**Pull request by Joshua-Anderson**

### CODE REVIEW

**Comment by mboersma** [comment]
Thanks for the doc clarification. Sorry to be pedantic, but could you amend the subject to [not capitalize](http://docs.deis.io/en/latest/contributing/standards/#subject-line) the verb `Add`? tyvm :bowtie:

**Comment by mboersma** [comment]
Docs LGTM.

**Comment by carmstrong** [comment]
LGTM.

**Comment by mboersma** [comment]
Passed doc tests, so merging...

**Pull request merged**
