### PR TITLE
Minor doc updates for GCE

### PR DESCRIPTION
**Pull request by dhilipsiva**

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

**Comment by sgoings** [comment]
Could you rebase this PR into one commit please, as per https://github.com/deis/deis/blob/master/CONTRIBUTING.md?

**Comment by dhilipsiva** [comment]
@sgoings Apologies on not going through CONTRIBUTING docs earlier. Fixed it.

**Comment by dhilipsiva** [comment]
@sgoings Also would it be okay if I refactor the python scripts to be compatible with both Python3 and Python2 and send another PR? Currently, its compatible only with Py2.

**Comment by dhilipsiva** [comment]
@sgoings I just realised something about my previous comment. I did not wanted to refactor the controller's or any other part of python code except for the python files in found in `contrib` folder.

**Comment by bacongobbler** [comment]
@dhilipsiva thanks for the doc fixes! One more thing needs to change with the commit before we merge, though. We need the commit message to follow the [commit style](http://docs.deis.io/en/latest/contributing/standards/#commit-style) so the release scripts can pick up your commit properly. Would you mind amending it to something like `docs(installing_deis): fixup command invocations for GCE`? That would be very helpful. :)

As for your other comment

> would it be okay if I refactor the python scripts to be compatible with both Python3 and Python2 and send another PR?

I don't see why not, so long as py2 is the default. Keep in mind that we've removed most of the code in `contrib` in deis/workflow (the eventual successor to deis v1) in favour of relying on kubernetes' docs for provisioning the hosts, so I wouldn't put too much effort into it unless you absolutely need to have the provision scripts working with python 3.

**Comment by dhilipsiva** [comment]
@bacongobbler Is the commit Body and Footer Mandatory? Or would a message just suffice?

**Comment by dhilipsiva** [comment]
@bacongobbler Sorry for multiple comments. Not too much of an effort. I changed AWS and Google contribs locally already as I am provisioning servers on both the places. Thanks for the Heads up.

**Comment by bacongobbler** [comment]
the commit body and footer isn't necessary for such a small fix. For larger features it's strongly recommended, but not required.

**Comment by dhilipsiva** [comment]
@bacongobbler Done! Thanks!

**Comment by carmstrong** [comment]
Thanks!

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Pull request merged**
