### PR TITLE
[WIP] ref(controller): log raw output of "docker inspect" on error

### PR DESCRIPTION
**Pull request by mboersma**
This is to investigate the raw output that is causing #3913 failures, it doesn't fix anything (yet). 

Apologies for submitting an exploratory PR, but the network bandwidth here at DockerCon 2015 doesn't permit me to test this locally.

### CODE REVIEW

**Comment by carmstrong** [comment]
Code LGTM.

**Comment by bacongobbler** [comment]
this is blocking most PRs from going green (#3874 just hit this as well). From the logs it doesn't look like the error we're looking for isn't showing itself. I have a cluster up so I'll see what I can dig up :)

**Comment by mboersma** [comment]
> I'll see what I can dig up

That would be great. If we can just trigger the error and catch the raw text I think it will illuminate what's going wrong, but this has been quite the Heisenbug.

**Comment by mboersma** [comment]
Closing in favor of #3930.

**Pull request closed without merging**
