### PR TITLE
chore(registry): bump docker-registry

### LINKED ISSUE #2916: Cannot pull image - tag not found
Trying to deploy the go-example app from the documentation : http://docs.deis.io/en/latest/using_deis/using-docker-images/#using-docker-images

I am skipping the "Prepare the application" bit and trying to deploy the example docker app gabrtv/example-go

I run the following to do the deployment :

deis pull gabrtv/example-go:latest
Does not work I get the following :

"GET Image Error (404: {\"error\": \"Tag not found\"})"
Looking at https://registry.hub.docker.com/u/gabrtv/example-go/tags/manage/

The latest tag is there. Pulling it with

docker pull gabrtv/example-go
it get's pulled correctly. So I am not really sure what I am doing wrong.

Using the controller API with curl gives me the same result :

     curl -i -X POST \
     -H "Authorization: token $TOKEN" \
     -H "Content-Type: application/json" \
     -d '{"image":"gabrtv/example-go"}' \
     http://$IP:$PORT/v1/apps/dummyapp2/builds/

### PR DESCRIPTION
**Pull request by bacongobbler**
replaces #3049 
closes #2916

### CODE REVIEW

**Comment by carmstrong** [comment]
This implements https://github.com/deis/docker-registry/pull/10.

**Comment by bacongobbler** [comment]
anecdotal evidence shows that `deis pull` operations seem to work a lot better with this PR. I have not been able to repro on my Rackspace cluster.

pinging @daemonza @glogiotatidis @rjcoleman @aledbf from #2916 -- if you guys have some spare cycles, we'd really appreciate if you can confirm that this is our smoking gun :)

**Comment by carmstrong** [comment]
Code LGTM. Reviewed https://github.com/deis/docker-registry/pull/10

**Comment by mboersma** [comment]
Code LGTM.

**Comment by daemonza** [comment]
I just tried this against a stack on AWS. Getting the same error. Deployed v1.3.0
Build a registry using this sources pushed to docker hub (https://registry.hub.docker.com/u/daemonza/docker-registry/)

deisctl config registry set image=daemonza/docker-registry:latest

stopped, uninstalled, install and started the registry. Tested with 

    mkdir ./tmp; cd ./tmp; git init; deis create; 
    deis pull gabrtv/example-go:latest

Still getting : 

    Creating build... 503 SERVICE UNAVAILABLE
    Detail:
    GET Image Error (404: {"error": "Tag not found"})

**Comment by bacongobbler** [comment]
@daemonza this PR is in master -- you'll have to follow the [hacking guide](http://docs.deis.io/en/latest/contributing/hacking/) if you want to take this for a spin.

**Pull request merged**
