### PR TITLE
fix(registry): retrieve bucket name from etcd

### LINKED ISSUE #3429: Registry can't get BUCKET_NAME from etcd
This causes issues setting up registry on Amazon S3 instead of Ceph

Ref #2252 / #2812

### PR DESCRIPTION
**Pull request by krancour**
Fixes #3429

### CODE REVIEW

**Comment by mboersma** [comment]
I guess registry wasn't actually using `BUCKET_NAME` anywhere? That looked like a bit of copy-paste in the first place. Code LGTM.

**Comment by bacongobbler** [comment]
I'd truly be surprised if someone used $BUCKET_NAME originally. In any case, it makes more sense to read it from etcd. Code LGTM.

**Comment by carmstrong** [comment]
Code LGTM. My only other thought is that we should also make this change to database for consistency, but that doesn't block this PR.

**Comment by carmstrong** [comment]
Actually, why did the mode of the template change to '755'? We should revert that - the template should be 644, and the mode of the resulting file should be handled by confd.

**Comment by krancour** [comment]
That isn't anything I changed in this PR.

**Comment by krancour** [comment]
Whoops.  Looks like I did??  But how?

**Comment by krancour** [comment]
I amended the PR with corrected mode on the template.

**Comment by carmstrong** [comment]
Code LGTM. Thanks @krancour.

**Comment by carmstrong** [comment]
Jenkins died due to an unrelated error pulling from the Ubuntu mirror. Kicked off a new run: https://ci.deis.io/job/test-ec2/657/

**Comment by krancour** [comment]
Still learning my way around the automation that you guys have in place.  Is there some magic comment I can leave to make Jenkins re-run the tests?

**Comment by mboersma** [comment]
> Is there some magic comment I can leave to make Jenkins re-run the tests?

I think Jenkins will ignore anyone but its admins if you comment "Jenkins, test this please." You can always rebase + push your branch to fire off a job, or just ask us.

**Pull request merged**
