### PR TITLE
docs(contrib): add link to deis-phppgadmin

### PR DESCRIPTION
**Pull request by CloudSide**
docs(contrib): add link to deis-phppgadmin

Add deis-phppgadmin (An addon for deis-databas) to contrib/README.md (custom components)

[deis-phppgadmin](https://github.com/HeheCloud/deis-phppgadmin) by [hehecloud](https://github.com/HeheCloud) - An addon for deis-database (phpPgAdmin)

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

Your Pull Request can earn you credit at DigitalOcean! See http://docs.deis.io/en/latest/contributing/hacking/#digitalocean-credit for details.

**Comment by bacongobbler** [comment]
Looks like the commits are mixed up. Would you please amend them according to our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide)?

**Comment by CloudSide** [comment]
docs(contrib) ?

**Comment by bacongobbler** [comment]
Yeah. Something like `docs(contrib): add link to deis-phppgadmin`.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Pull request merged**
