### PR TITLE
test(deisctl): add race detection to deisctl

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
The deisctl client didn't have race detection enabled on the tests while the rest of deis did. It can't hurt to have it and it could catch some nasty bugs.

### CODE REVIEW

**Comment by mboersma** [comment]
The [race detector](https://golang.org/doc/articles/race_detector.html) should definitely be on for `go test`, but it looks like Deis defines `GOTEST = $(GO) test --cover --race -v` in includes.mk and then only uses it in logger tests. So the `-race` flag isn't actually on for most of our tests.

This PR LGTM as-is, but either we should add to it or open another one to try to get all Deis tests using the `-race` flag.

**Comment by bacongobbler** [comment]
indeed. Standardization for tests across components is key. :key:

**Comment by Joshua-Anderson** [comment]
Didn't look carefully enough at the other unit tests. Sorry :frowning:. I'll open a new PR that better fixes the problem in a sec.

**Comment by mboersma** [comment]
No apologies necessary--it's very helpful that you noticed this in the first place and pounced on it.

**Pull request closed without merging**
